CREATE TABLE dbo.DB_PATCHES
 (
	PATCH_NAME varchar(1000) not null primary key,
	DEPLOYED_DATE date not null
 );

 CREATE TABLE dbo.USERS	
 (
	USER_NAME VARCHAR(128) NOT NULL PRIMARY KEY,
	PASSWORD VARCHAR(128) NOT NULL
 );
 
 CREATE TABLE dbo.ROLES
 (
	ROLE VARCHAR(20) NOT NULL PRIMARY KEY
 );
 
 CREATE TABLE dbo.USER_ROLES
 (
	ROLE VARCHAR(20) NOT NULL,
	USER_NAME VARCHAR(128) NOT NULL
 );
 CREATE TABLE dbo.CONSTANTS
 (
 NAME VARCHAR(128) NOT NULL PRIMARY KEY,
 INT_VALUE INT NULL,
 STRING_VALUE VARCHAR(10000),
 DECIMAL_VALUE decimal(8,2)
 );

 ALTER TABLE dbo.USER_ROLES ADD CONSTRAINT USER_NAME_FK FOREIGN KEY(USER_NAME) 
 REFERENCES dbo.USERS (USER_NAME);
 
 ALTER TABLE dbo.USER_ROLES ADD CONSTRAINT ROLE_FK FOREIGN KEY(ROLE) 
 REFERENCES dbo.ROLES (ROLE);
 