
CREATE TABLE OUTPUT_FILE_TEMPLATE_TABLE
( 
NAME varchar(200) not null,
TYPE varchar(50) not null,
TEMPLATE_DETAIL varchar(10000) not null,
PREFIX_OUTPUT_NAME varchar(200) not null,
CREATE_DATE DATE not null,
 constraint OUTPUT_FILE_TEMPLATE_TABLE_PK primary key (NAME,TYPE)
);

 
INSERT INTO OUTPUT_FILE_TEMPLATE_TABLE
(
	NAME,
	TYPE,
	TEMPLATE_DETAIL,
	PREFIX_OUTPUT_NAME,
	CREATE_DATE
)
VALUES
('ANIM_PARENTAGE_VERIF_RECORD',
'JSON',
'   {      
        "ANIMAL_ID": "<ANIMAL_ID>",
		"ANIMAL_SOURCE_CODE": "<ANIMAL_SOURCE_CODE>",
		"SAMPLE_ID": "<SAMPLE_ID>",
		"REQUESTER_ID": "<REQUESTER_ID>",
		"CHIP_TYPE": "<CHIP_TYPE>",
		"SIRE_ID": "<SIRE_ID>",
		"SIRE_SOURCE_CODE": "<SIRE_SOURCE_CODE>",
		"SIRE_STATUS_CODE": "<SIRE_STATUS_CODE>",
		"SUGGESTED_SIRE": "<SUGGESTED_SIRE>",
		"DAM_ID": "<DAM_ID>",
		"DAM_SOURCE_CODE": "<DAM_SOURCE_CODE>",
		"DAM_STATUS_CODE": "<DAM_STATUS_CODE>",
		"SUGGESTED_DAM": "<SUGGESTED_DAM>",
		"MGS_ID": "<MGS_ID>",
		"MGS_STATUS_CODE": "<MGS_STATUS_CODE>",
		"MGS_SUGG_1": "<MGS_SUGG_1>",
		"MGS_STAT_1: "<MGS_STAT_1>",
		"MGS_SUGG_2": "<MGS_SUGG_2>",
		"MGS_STAT_2": "<MGS_STAT_2>",
		"MGS_SUGG_3": "<MGS_SUGG_3>",
		"MGS_STAT_3": "<MGS_STAT_3>",
		"MGS_SUGG_4": "<MGS_SUGG_4>",
		"MGS_STAT_4": "<MGS_STAT_4>",
		"USABILITY_INDICATOR": "<USABILITY_INDICATOR>",
		"PARENTAGE_INDICATOR": "<PARENTAGE_INDICATOR>",
		"FEE_CODE": "<FEE_CODE>",
		"DATE": "<DATE>",
		"GETS_EVAL": "<GETS_EVAL>"
   }',
'Parentage_Ver_Records',
CURRENT DATE 
)
;