 
 CREATE INDEX NIX_BULL_EVL_TABLE_EVAL_PDATE
ON BULL_EVL_TABLE (
   EVAL_PDATE
   )   ALLOW REVERSE SCANS;
	
CREATE INDEX NIX_BULL_EVL_TABLE_EVAL_BREED_CODE
ON BULL_EVL_TABLE (
   EVAL_BREED_CODE
   )ALLOW REVERSE SCANS; 
   CREATE INDEX NIX_BULL_EVL_TABLE_EVAL_STATUS_CODE
ON BULL_EVL_TABLE (
   STATUS_CODE
   )ALLOW REVERSE SCANS; 
CREATE INDEX NIX_BULL_EVL_TABLE_EVAL_SOURCE_CODE
ON BULL_EVL_TABLE (
   SOURCE_CODE
   )ALLOW REVERSE SCANS; 
   
  CREATE INDEX NIX_BULL_EVL_TABLE_EVAL_SAMP_STATUS_CODE
ON BULL_EVL_TABLE (
   SAMP_STATUS_CODE
   )ALLOW REVERSE SCANS;  
     
       CREATE INDEX NIX_BULL_EVL_TABLE_EVAL_GENOMICS_IND
ON BULL_EVL_TABLE (
   GENOMICS_IND
   )ALLOW REVERSE SCANS;  
   
    
 CREATE INDEX NIX_BULL_EVL_TABLE_TRAIT_PTA_QTY_SEG
ON BULL_EVL_TABLE (
   TRAIT_PTA_QTY_SEG
   )   ALLOW REVERSE SCANS;
    
    
    
 CREATE INDEX NIX_BULL_EVL_TABLE_BREED_GENOMICS_IND
ON BULL_EVL_TABLE (
   EVAL_PDATE,EVAL_BREED_CODE,GENOMICS_IND
   )   ALLOW REVERSE SCANS;
