ALTER TABLE PTA_COW_TABLE_COMPACT
ADD COLUMN PTA_GL_QTY VARCHAR(10) NULL
ADD COLUMN PTA_GL_REL_PCT VARCHAR(10) NULL
ADD COLUMN PTA_MFV_QTY VARCHAR(10) NULL
ADD COLUMN PTA_MFV_REL_PCT VARCHAR(10) NULL 
ADD COLUMN PTA_DAB_QTY VARCHAR(10) NULL
ADD COLUMN PTA_DAB_REL_PCT VARCHAR(10) NULL
ADD COLUMN PTA_KET_QTY VARCHAR(10) NULL
ADD COLUMN PTA_KET_REL_PCT VARCHAR(10) NULL
ADD COLUMN PTA_MAS_QTY VARCHAR(10) NULL
ADD COLUMN PTA_MAS_REL_PCT VARCHAR(10) NULL
ADD COLUMN PTA_MET_QTY VARCHAR(10) NULL
ADD COLUMN PTA_MET_REL_PCT VARCHAR(10) NULL
ADD COLUMN PTA_RPL_QTY VARCHAR(10) NULL
ADD COLUMN PTA_RPL_REL_PCT VARCHAR(10) NULL
ADD COLUMN PTA_EFC_QTY VARCHAR(10) NULL
ADD COLUMN PTA_EFC_REL_PCT VARCHAR(10) NULL;

MERGE INTO PTA_COW_TABLE_COMPACT AS A
USING  dbo.COW_NEW  B
ON A.ANIM_KEY = B.ANIM_KEY
WHEN MATCHED THEN
UPDATE 
SET A.PTA_GL_QTY = B.glpta
	,A.PTA_GL_REL_PCT = B.glptarel
	,A.PTA_MFV_QTY = B.mfvpta
	,A.PTA_MFV_REL_PCT = B.mfvptarel
	,A.PTA_DAB_QTY = B.dabpta
	,A.PTA_DAB_REL_PCT = B.dabptarel
	,A.PTA_KET_QTY = B.ketpta
	,A.PTA_KET_REL_PCT = B.ketptarel
	,A.PTA_MAS_QTY = B.maspta
	,A.PTA_MAS_REL_PCT = B.masptarel
	,A.PTA_MET_QTY = B.metpta
	,A.PTA_MET_REL_PCT = B.metptarel
	,A.PTA_RPL_QTY = B.rplpta
	,A.PTA_RPL_REL_PCT = B.rplptarel
	,A.PTA_EFC_QTY = B.efcpta
	,A.PTA_EFC_REL_PCT = B.efcptarel
;


 
		  
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_DAB_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_DAB_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_DAB_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_DAB_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_EFC_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_EFC_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_EFC_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_EFC_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_GL_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_GL_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_GL_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_GL_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_KET_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_KET_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_KET_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_KET_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_MAS_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_MAS_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_MAS_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_MAS_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_MET_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_MET_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_MET_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_MET_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_MFV_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_MFV_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_MFV_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_MFV_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_RPL_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_RPL_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_RPL_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_RPL_REL_PCT varchar(10) null;



 merge into pta_cow_table A
 using dbo.cow_new B
 on A.anim_key = B.anim_key
 AND A.eval_pdate = 21762
 WHEN MATCHED THEN
 UPDATE SET 
  PA_DAB_QTY = B.DABPA
 ,PA_DAB_REL_PCT = B.DABPAREL
 ,PTA_DAB_QTY = B.DABPTA
 ,PTA_DAB_REL_PCT = B.DABPTAREL
 ,PA_EFC_QTY = B.EFCPA
 ,PA_EFC_REL_PCT = B.EFCPAREL
 ,PTA_EFC_QTY = B.EFCPTA
 ,PTA_EFC_REL_PCT = B.EFCPTAREL
 ,PA_GL_QTY = B.GLPA
 ,PA_GL_REL_PCT = B.GLPAREL
 ,PTA_GL_QTY = B.GLPTA
 ,PTA_GL_REL_PCT = B.GLPTAREL
 ,PA_KET_QTY = B.KETPA
 ,PA_KET_REL_PCT = B.KETPAREL
 ,PTA_KET_QTY = B.KETPTA
 ,PTA_KET_REL_PCT = B.KETPTAREL
 ,PA_MAS_QTY = B.MASPA
 ,PA_MAS_REL_PCT = B.MASPAREL
 ,PTA_MAS_QTY = B.MASPTA
 ,PTA_MAS_REL_PCT = B.MASPTAREL
 ,PA_MET_QTY = B.METPA
 ,PA_MET_REL_PCT = B.METPAREL
 ,PTA_MET_QTY = B.METPTA
 ,PTA_MET_REL_PCT = B.METPTAREL
 ,PA_MFV_QTY = B.MFVPA
 ,PA_MFV_REL_PCT = B.MFVPAREL
 ,PTA_MFV_QTY = B.MFVPTA
 ,PTA_MFV_REL_PCT = B.MFVPTAREL
 ,PA_RPL_QTY = B.RPLPA
 ,PA_RPL_REL_PCT = B.RPLPAREL
 ,PTA_RPL_QTY = B.RPLPTA
 ,PTA_RPL_REL_PCT = B.RPLPTAREL
;

 
	   