CREATE TABLE dbo.COW_NEW
(
	anim_key INT
	,sire CHAR(17)
	,dam CHAR(17)
	,xref CHAR(17)	
	,birth INT
	,status	SMALLINT
	,regstat VARCHAR(20)	
	,lastctr INT
	,lastctrl INT	
	,lastherd INT	
	,lastfresh INT	
	,lastdim INT	
	,lasttc	INT
	,idchng	INT
	,anceschng INT	
	,frgncont INT	
	,evalcode INT	
	,oscode	INT
	,ripind	INT
	,inbpct	INT
	,sumlwgt INT	
	,nmpctl	INT
	,mfprel	INT
	,ptamilk INT	
	,mfrelpct INT	
	,ptafat INT	
	,fatpct INT	
	,prorelpct INT	
	,ptapro	INT
	,propct	INT
	,pedcomp INT	
	,genind INT	
	,ptaplrel INT	
	,ptapl INT	
	,ptascsrel INT	
	,ptascs	INT
	,nmrel INT	
	,nm_amt	INT
	,firstherd INT	
	,mfdaueq INT	
	,prodaueq INT	
	,mfherds INT	
	,proherds INT	
	,mfrelat INT	
	,prorelat INT	
	,plagewt INT	
	,mflact INT	
	,prolact INT	
	,mfmgmt INT	
	,promgmt INT	
	,stdmilk INT	
	,stdfat INT	
	,stdmp INT	
	,stdpro INT	
	,plmim INT	
	,stdscs INT	
	,devmilk INT	
	,devfat INT	
	,devmp INT	
	,devpro INT	
	,ppamilk INT	
	,ppafat INT	
	,ppapro INT	
	,mfpparel INT	
	,pamilk INT	
	,mfparel INT	
	,pafat INT	
	,proparel INT	
	,papro INT	
	,g1 INT	
	,gm INT	
	,milkbullcon INT	
	,fatbullcon	INT 
	,probullcon INT	
	,cowmsk INT	
	,distmsk1 INT	
	,distmsk2 INT	
	,futdauinb INT	
	,fmdoll INT	
	,cmdoll INT	
	,ptadpr INT	
	,ptadprrel INT	
	,stddpr INT	
	,papl INT	
	,paplrel INT	
	,pascs INT	
	,pascsrel INT	
	,padpr INT	
	,padprrel INT	
	,panm INT	
	,panmrel INT	
	,dominbrd INT	
	,dominpct INT	
	,het_pct INT	
	,hcrpta INT	
	,hcrptani INT	
	,hcrptarel INT	
	,hcrpa INT	
	,hcrpani INT	
	,hcrparel INT	
	,ccrpta INT	
	,ccrptani INT	
	,ccrptarel INT	
	,ccrpa INT	
	,ccrpani INT	
	,ccrparel INT	
	,chip_num INT	
	,gen_inbrd_pct INT	
	,future_gen_inbrd_pct INT	
	,livpta INT	
	,livptarel INT	
	,livpa INT	
	,livparel INT	
	,glpta INT	
	,glptarel INT	
	,glpa INT	
	,glparel INT	
	,hthpta INT	
	,hthptarel INT	
	,hthpa INT	
	,hthparel INT	
	,rfipta INT	
	,rfiptarel INT	
	,rfipa INT	
	,rfiparel INT	
	,mfvpta INT	
	,mfvptarel INT	
	,mfvpa INT	
	,mfvparel INT	
	,dabpta INT	
	,dabptarel INT	
	,dabpa INT	 
	,dabparel INT	
	,ketpta	INT
	,ketptarel INT	
	,ketpa INT	
	,ketparel INT	
	,maspta INT	
	,masptarel INT	
	,maspa INT	
	,masparel INT	
	,metpta INT	
	,metptarel INT	
	,metpa INT	
	,metparel INT	
	,rplpta INT	
	,rplptarel INT	
	,rplpa INT	 
	,rplparel INT	
	,efcpta	INT  
	,efcptarel INT	
	,efcpa INT	
	,efcparel INT
)


/*
db2 connect to cdcbdb
db2 load from /home/shared/Data/datagene_cowout1912.csv of del insert into dbo.COW_NEW
*/