 
CREATE TABLE ANIM_KEY_HERD_CTRL_NUM
(

INT_ID char(17) not null,
SPECIES_CODE char(1) not null,
HERD_CODE int not null,
CTRL_NUM int not null,
SEX_CODE char(1) not null,
ANIM_KEY int  null,
constraint ANIM_KEY_HERD_CTRL_NUM_PK PRIMARY KEY ( INT_ID,SPECIES_CODE,HERD_CODE,CTRL_NUM,SEX_CODE)
);
create index ANIM_KEY_HERD_CTRL_NUM_HRD_INDEX               on ANIM_KEY_HERD_CTRL_NUM                 (HERD_CODE asc, CTRL_NUM asc) allow reverse scans;
create index ANIM_KEY_HERD_CTRL_NUM_HRD_INDEX_CONCAT               on ANIM_KEY_HERD_CTRL_NUM                 (HERD_CODE ||' '||CTRL_NUM ) allow reverse scans;
 

INSERT INTO ANIM_KEY_HERD_CTRL_NUM
(
INT_ID,
SPECIES_CODE,
HERD_CODE,
CTRL_NUM,
SEX_CODE 
)

 
SELECT distinct   
id.INT_ID,
l.SPECIES_CODE, 
l.HERD_CODE, 
l.CTRL_NUM,
id.SEX_CODE
FROM LACTA90_TABLE l
INNER JOIN ID_XREF_TABLE id 
ON l.anim_key = id.anim_key
and id.SEX_CODE ='F'
and id.SPECIES_CODE =l.SPECIES_CODE
and id.PREFERRED_CODE =1
 
UNION

SELECT  DISTINCT 
BREED_CODE||COUNTRY_CODE||ANIM_ID_NUM as INT_ID,
substring(BASE_RECORD,1,1) AS SPECIES_CODE, 
HERD_CODE, 
CTRL_NUM,
substring(BASE_RECORD,2,1) AS SEX_CODE
FROM ERROR4_TABLE

union
SELECT  DISTINCT  
BREED_CODE||COUNTRY_CODE||ANIM_ID_NUM as INT_ID,
SPECIES_CODE, 
HERD_CODE, 
CTRL_NUM,
'F' AS SEX_CODE

FROM ERROR5_TABLE;
 
 
CREATE TABLE ANIM_KEY_HAS_ERROR
(

INT_ID char(17) not null,
SPECIES_CODE char(1) not null,
ANIM_KEY int not null,
constraint ANIM_KEY_HAS_ERROR_PK PRIMARY KEY ( INT_ID,SPECIES_CODE)
);
INSERT INTO ANIM_KEY_HAS_ERROR
 (
  INT_ID,
  SPECIES_CODE,
  ANIM_KEY
 )
 
 SELECT INT_ID,SPECIES_CODE, MAX(ANIM_KEY) ANIM_KEY
 FROM (
 SELECT DISTINCT
 ANIM_KEY, 
 BREED_CODE||COUNTRY_CODE||ANIM_ID_NUM as INT_ID,
 SUBSTRING(BASE_RECORD,1,1)AS SPECIES_CODE
 FROM ERROR1_TABLE
 UNION
 SELECT DISTINCT
	 ANIM_KEY,
     BREED_CODE||COUNTRY_CODE||ANIM_ID_NUM as INT_ID,
     SUBSTRING(BASE_RECORD,1,1)AS SPECIES_CODE
 FROM ERROR4_TABLE  
 
 UNION
 SELECT DISTINCT
	 ANIM_KEY,
     BREED_CODE||COUNTRY_CODE||ANIM_ID_NUM as INT_ID,
     SPECIES_CODE
 FROM ERROR5_TABLE
 )a
 GROUP BY INT_ID,SPECIES_CODE;
 
 

-- ADD ERROR 6
MERGE INTO ANIM_KEY_HERD_CTRL_NUM AS A
USING 
(
SELECT  DISTINCT  
BREED_CODE||COUNTRY_CODE||ANIM_ID_NUM as INT_ID,
SPECIES_CODE, 
HERD_CODE, 
CTRL_NUM,
'F' AS SEX_CODE
FROM ERROR6_TABLE WITH UR
)
AS B
ON A.INT_ID = B.INT_ID
AND A.SPECIES_CODE = B.SPECIES_CODE
AND A.HERD_CODE = B.HERD_CODE
AND A.CTRL_NUM = B.CTRL_NUM
AND A.SEX_CODE = B.SEX_CODE
WHEN NOT MATCHED THEN
INSERT 
(
INT_ID,
SPECIES_CODE,
HERD_CODE,
CTRL_NUM,
SEX_CODE 
)
VALUES 
(
B.INT_ID,
B.SPECIES_CODE,
B.HERD_CODE,
B.CTRL_NUM,
B.SEX_CODE 
);
 
MERGE INTO ANIM_KEY_HAS_ERROR AS A
USING 
(
SELECT MAX(ANIM_KEY) AS ANIM_KEY,
     BREED_CODE||COUNTRY_CODE||ANIM_ID_NUM as INT_ID,
     SPECIES_CODE
FROM ERROR6_TABLE
GROUP BY BREED_CODE||COUNTRY_CODE||ANIM_ID_NUM ,SPECIES_CODE
 WITH UR
)
AS B
ON A.INT_ID = B.INT_ID
AND A.SPECIES_CODE = B.SPECIES_CODE
 
WHEN NOT MATCHED THEN
INSERT 
(
INT_ID,
SPECIES_CODE,
ANIM_KEY 
)
VALUES 
(
B.INT_ID,
B.SPECIES_CODE,
B.ANIM_KEY 
);

 -- Update anim
merge into ANIM_KEY_HERD_CTRL_NUM as a
using  ID_XREF_TABLE as b
on a.INT_ID = b.INT_ID
and a.SPECIES_CODE = b.SPECIES_CODE
when matched then
update set ANIM_KEY = b.ANIM_KEY;
 
 -- add index to error table

 create index ERROR5_TABLE_INDEX_INT_ID              on ERROR5_TABLE                 (BREED_CODE||COUNTRY_CODE||ANIM_ID_NUM ) allow reverse scans;
 create index ERROR4_TABLE_INDEX_INT_ID              on ERROR4_TABLE                 (BREED_CODE||COUNTRY_CODE||ANIM_ID_NUM ) allow reverse scans;
 create index ERROR1_TABLE_INDEX_INT_ID              on ERROR1_TABLE                 (BREED_CODE||COUNTRY_CODE||ANIM_ID_NUM ) allow reverse scans;
create index ERROR6_TABLE_INDEX_INT_ID              on ERROR6_TABLE                 (BREED_CODE||COUNTRY_CODE||ANIM_ID_NUM ) allow reverse scans;
 
  create index ER4B_SOURCE_FILE_NAME_INDEX   on ERROR4_TABLE    (SOURCE_FILE_NAME DESC, TRIM(SUBSTRING(BASE_RECORD,80,8)) desc, CALV_PDATE DESC  ,DIM_QTY DESC) allow reverse scans;
  create index ER5B_SOURCE_FILE_NAME_INDEX   on ERROR5_TABLE    (SOURCE_FILE_NAME DESC, PROC_PDATE desc, CALV_PDATE DESC) allow reverse scans;
  