

CREATE USER TEMPORARY TABLESPACE "UTMP4K" 
         PAGESIZE 32K MANAGED BY AUTOMATIC STORAGE
         USING STOGROUP "IBMSTOGROUP"
         EXTENTSIZE 4
         PREFETCHSIZE AUTOMATIC
         BUFFERPOOL "IBMDEFAULTBP"
         OVERHEAD INHERIT
         TRANSFERRATE INHERIT
         FILE SYSTEM CACHING
         DROPPED TABLE RECOVERY OFF;
		  
	CREATE BUFFERPOOL BP8K pagesize 8K;
CREATE SYSTEM TEMPORARY TABLESPACE STB_8 PAGESIZE 8K BUFFERPOOL BP8K;
CREATE BUFFERPOOL BP16K pagesize 16K;
CREATE SYSTEM TEMPORARY TABLESPACE STB_16 PAGESIZE 16K BUFFERPOOL BP16K;
CREATE BUFFERPOOL BP32K pagesize 32K;
CREATE SYSTEM TEMPORARY TABLESPACE STB_32 PAGESIZE 32K BUFFERPOOL BP32K; 
 
 
CREATE GLOBAL TEMPORARY TABLE SESSION.animals -- DROP TABLE SESSION.animals
	   (
         ANIM_KEY INT NULL
        ,SEX_CODE CHAR(1)
        ,SPECIES_CODE CHAR(1)
		,SIRE_KEY INT NULL
		,DAM_KEY INT NULL	
		,GENERATION INT NULL
		,ROOT_ANIM_KEY  INT
      ) 
      on commit preserve rows;
      
      
     
	CREATE GLOBAL TEMPORARY TABLE SESSION.animal_0 --DROP TABLE SESSION.animal_0
	   (
        ANIM_KEY INT NULL
        ,SEX_CODE CHAR(1)
        ,SPECIES_CODE CHAR(1)
		,SIRE_KEY INT NULL
		,DAM_KEY INT NULL	
		,GENERATION INT NULL
		,ROOT_ANIM_KEY  INT
       
      ) 
      on commit preserve rows;
      