CREATE TABLE ARCHIVE_GROUP_TABLE (
	GROUP_KEY INT NOT NULL ,
	GROUP_SHORT_NAME VARCHAR(10)  NULL,
	GROUP_NAME VARCHAR(100)   NULL,
	STATUS_CODE VARCHAR(1)  NULL,
	ARCHIVED_TIME TIMESTAMP NOT  NULL
	);

	
CREATE TABLE ARCHIVE_GROUP_FEATURE_COMPONENT_TABLE (
	GROUP_KEY INT NOT NULL,
	COMPONENT_KEY INT  NULL,
	CREATED_TIME TIMESTAMP   NULL,
	MODIFIED_TIME TIMESTAMP  NULL ,
	MODIFIED_BY VARCHAR(50)  NULL ,
	ARCHIVED_TIME TIMESTAMP NOT  NULL
	);