CREATE TABLE ARCHIVE_DATA_SOURCE_TABLE (
	DATA_SOURCE_KEY INT NOT NULL ,
	CLASS_CODE VARCHAR(1) NULL,
	HEALTH_SOURCE_CODE VARCHAR(1) NULL,
	SOURCE_SHORT_NAME VARCHAR(12) NULL,
	SOURCE_NAME VARCHAR(40) NULL,
	STATUS_CODE VARCHAR(1) NULL,
	WITHIN_CLASS_KEY INT NULL,
	CDDR_IND VARCHAR(1) NULL,
	CONTACT_NAME VARCHAR(200) NULL,
	EMAIL_ADDR VARCHAR(320) NULL,
	PATH_ADDR VARCHAR(320) NULL,
	MODIFY_TIMESTAMP TIMESTAMP NULL,
	COMMENT VARCHAR(200) NULL,
	ARCHIVED_TIME TIMESTAMP NOT NULL
);