CREATE TABLE ANIM_KEY_HAS_ERROR
(

INT_ID char(17) not null,
SPECIES_CODE char(1) not null,
ANIM_KEY int not null,
SEX_CODE char(1) not null,
constraint ANIM_KEY_HAS_ERROR_PK PRIMARY KEY ( INT_ID,SPECIES_CODE)
);

INSERT INTO ANIM_KEY_HAS_ERROR
 (
  INT_ID,
  SPECIES_CODE,
  ANIM_KEY,
  SEX_CODE
 )
 
 SELECT INT_ID,SPECIES_CODE, MAX(ANIM_KEY) ANIM_KEY, max(SEX_CODE) as SEX_CODE
 FROM (
 SELECT DISTINCT
	 ANIM_KEY, 
	 BREED_CODE||COUNTRY_CODE||ANIM_ID_NUM as INT_ID,
	 SUBSTRING(BASE_RECORD,1,1)AS SPECIES_CODE,
	 SUBSTRING(BASE_RECORD,2,1)AS SEX_CODE
 FROM ERROR1_TABLE
 UNION
 SELECT DISTINCT
	 ANIM_KEY,
     BREED_CODE||COUNTRY_CODE||ANIM_ID_NUM as INT_ID,
     SUBSTRING(BASE_RECORD,1,1)AS SPECIES_CODE,
     SUBSTRING(BASE_RECORD,2,1)AS SEX_CODE
 FROM ERROR4_TABLE  
 
 UNION
 SELECT DISTINCT
	 ANIM_KEY,
     BREED_CODE||COUNTRY_CODE||ANIM_ID_NUM as INT_ID,
     SPECIES_CODE,
     'F' AS SEX_CODE
 FROM ERROR5_TABLE
 
  UNION
 SELECT DISTINCT
	 ANIM_KEY,
     BREED_CODE||COUNTRY_CODE||ANIM_ID_NUM as INT_ID,
     SPECIES_CODE,
     'F' AS SEX_CODE
 FROM ERROR6_TABLE
 )a
 GROUP BY INT_ID,SPECIES_CODE 
 ;
  
  
 -- Update anim
merge into ANIM_KEY_HERD_CTRL_NUM as a
using  ID_XREF_TABLE as b
on a.INT_ID = b.INT_ID
and a.SPECIES_CODE = b.SPECIES_CODE
when matched then
update set ANIM_KEY = b.ANIM_KEY;