CREATE TABLE ARCHIVE_ROLE_TABLE (
	ROLE_KEY INT NOT NULL ,
	ROLE_SHORT_NAME VARCHAR(10)  NULL,
	ROLE_NAME VARCHAR(100)   NULL,
	STATUS_CODE VARCHAR(1)  NULL,
	ARCHIVED_TIME TIMESTAMP NOT  NULL
	);

	
CREATE TABLE ARCHIVE_ROLE_FEATURE_COMPONENT_TABLE (
	ROLE_KEY INT NOT NULL,
	COMPONENT_KEY INT  NULL,
	CREATED_TIME TIMESTAMP   NULL,
	MODIFIED_TIME TIMESTAMP  NULL ,
	MODIFIED_BY VARCHAR(50)  NULL ,
	ARCHIVED_TIME TIMESTAMP NOT  NULL
	);
	