	CREATE GLOBAL TEMPORARY TABLE SESSION.TmpDataExchangeInputTables -- drop table SESSION.TmpDataExchangeInputTables
	(
		tabname VARCHAR(200),
		query VARCHAR(30000),
		template VARCHAR(30000),
		alias varchar(50),
		order smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
		level smallint 
	)  ON COMMIT PRESERVE ROWS;
  
  