
DROP TABLE PTA_COW_TABLE;
CREATE TABLE "DB2INST2"."PTA_COW_TABLE"  (
		  "ANIM_KEY" INTEGER NOT NULL , 
		  "EVAL_PDATE" SMALLINT NOT NULL , 
		  "EVAL_BREED_CODE" CHAR(2) NOT NULL , 
		  "ELITE_STATUS_CODE" CHAR(1) NOT NULL , 
		  "FOREIGN_CNTRB_CODE" CHAR(1) NOT NULL , 
		  "EVAL_CODE" CHAR(1) NOT NULL , 
		  "OWNER_SAMP_DATA_CODE" CHAR(1) NOT NULL , 
		  "INBRD_PCT" SMALLINT NOT NULL , 
		  "FUTURE_DAU_INBRD_PCT" SMALLINT NOT NULL , 
		  "SUM_LACT_WGT_QTY" SMALLINT , 
		  "PTA_MLK_QTY" SMALLINT , 
		  "PTA_FAT_QTY" SMALLINT , 
		  "PTA_FAT_PCT" CHAR(1) FOR BIT DATA , 
		  "PTA_PRO_QTY" SMALLINT , 
		  "PTA_PRO_PCT" CHAR(1) FOR BIT DATA , 
		  "PTA_PL_QTY" CHAR(1) , 
		  "PTA_SCS_QTY" SMALLINT , 
		  "PTA_DPR_QTY" CHAR(1) , 
		  "PTA_MF_REL_PCT" CHAR(1) , 
		  "PTA_MFP_REL_PCT" CHAR(1) , 
		  "PTA_PRO_REL_PCT" CHAR(1) , 
		  "PTA_PL_REL_PCT" CHAR(1) , 
		  "PTA_SCS_REL_PCT" CHAR(1) , 
		  "PTA_DPR_REL_PCT" CHAR(1) , 
		  "NM_AMT" SMALLINT NOT NULL , 
		  "NM_REL_PCT" CHAR(1) NOT NULL , 
		  "FM_AMT" SMALLINT , 
		  "CM_AMT" SMALLINT , 
		  "STD_MLK_QTY" INTEGER , 
		  "STD_FAT_QTY" SMALLINT , 
		  "STD_MP_QTY" SMALLINT , 
		  "STD_PRO_QTY" SMALLINT , 
		  "MIM_PL_QTY" SMALLINT , 
		  "STD_SCS_QTY" SMALLINT , 
		  "STD_DPR_QTY" SMALLINT , 
		  "PA_MLK_QTY" SMALLINT , 
		  "PA_FAT_QTY" SMALLINT , 
		  "PA_PRO_QTY" SMALLINT , 
		  "PA_PL_QTY" CHAR(1) , 
		  "PA_SCS_QTY" SMALLINT , 
		  "PA_DPR_QTY" CHAR(1) , 
		  "PA_MF_REL_PCT" CHAR(1) , 
		  "PA_MFP_REL_PCT" CHAR(1) , 
		  "PA_PRO_REL_PCT" CHAR(1) , 
		  "PA_PL_REL_PCT" CHAR(1) , 
		  "PA_SCS_REL_PCT" CHAR(1) , 
		  "PA_DPR_REL_PCT" CHAR(1) , 
		  "PA_NM_AMT" SMALLINT , 
		  "PA_NM_REL_PCT" CHAR(1) , 
		  "NM_PCTL" CHAR(2) NOT NULL WITH DEFAULT '  ' , 
		  "GENOMICS_IND" CHAR(1) NOT NULL WITH DEFAULT '0' , 
		  "PTA_HCR_QTY" SMALLINT WITH DEFAULT NULL , 
		  "PTA_HCR_REL_PCT" SMALLINT WITH DEFAULT NULL , 
		  "PTA_CCR_QTY" SMALLINT WITH DEFAULT NULL , 
		  "PTA_CCR_REL_PCT" SMALLINT WITH DEFAULT NULL , 
		  "PA_HCR_QTY" SMALLINT WITH DEFAULT NULL , 
		  "PA_HCR_REL_PCT" SMALLINT WITH DEFAULT NULL , 
		  "PA_CCR_QTY" SMALLINT WITH DEFAULT NULL , 
		  "PA_CCR_REL_PCT" SMALLINT WITH DEFAULT NULL , 
		  "PTA_LIV_QTY" SMALLINT WITH DEFAULT NULL , 
		  "PTA_LIV_REL_PCT" SMALLINT WITH DEFAULT NULL , 
		  "PA_LIV_QTY" SMALLINT WITH DEFAULT NULL , 
		  "PA_LIV_REL_PCT" SMALLINT WITH DEFAULT NULL , 
		  "GM_AMT" SMALLINT WITH DEFAULT NULL )   
		 IN "INDEX1"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Primary Key on Table "DB2INST2"."PTA_COW_TABLE"

ALTER TABLE "DB2INST2"."PTA_COW_TABLE" 
	ADD CONSTRAINT "PTA_COW_PK" PRIMARY KEY
		("ANIM_KEY",
		 "EVAL_PDATE",
		 "EVAL_BREED_CODE");



-- DDL Statements for Indexes on Table "DB2INST2"."PTA_COW_TABLE"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "DB2INST2"."PTA_COW_INDEX" ON "DB2INST2"."PTA_COW_TABLE" 
		("EVAL_PDATE" DESC,
		 "EVAL_BREED_CODE" ASC,
		 "ANIM_KEY" DESC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;


--load from \home\shared\extract\PTA_COW_TABLE.ixf of ixf warningcount 1 messages msg.txt insert into PTA_COW_TABLE nonrecoverable;


 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_DAB_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_DAB_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_DAB_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_DAB_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_EFC_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_EFC_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_EFC_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_EFC_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_GL_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_GL_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_GL_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_GL_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_KET_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_KET_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_KET_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_KET_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_MAS_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_MAS_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_MAS_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_MAS_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_MET_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_MET_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_MET_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_MET_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_MFV_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_MFV_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_MFV_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_MFV_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_RPL_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PA_RPL_REL_PCT varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_RPL_QTY varchar(10) null;
 ALTER TABLE PTA_COW_TABLE ADD COLUMN PTA_RPL_REL_PCT varchar(10) null;



 merge into pta_cow_table A
 using dbo.cow_new B
 on A.anim_key = B.anim_key
 AND A.eval_pdate = 21762
 WHEN MATCHED THEN
 UPDATE SET 
  PA_DAB_QTY = B.DABPA
 ,PA_DAB_REL_PCT = B.DABPAREL
 ,PTA_DAB_QTY = B.DABPTA
 ,PTA_DAB_REL_PCT = B.DABPTAREL
 ,PA_EFC_QTY = B.EFCPA
 ,PA_EFC_REL_PCT = B.EFCPAREL
 ,PTA_EFC_QTY = B.EFCPTA
 ,PTA_EFC_REL_PCT = B.EFCPTAREL
 ,PA_GL_QTY = B.GLPA
 ,PA_GL_REL_PCT = B.GLPAREL
 ,PTA_GL_QTY = B.GLPTA
 ,PTA_GL_REL_PCT = B.GLPTAREL
 ,PA_KET_QTY = B.KETPA
 ,PA_KET_REL_PCT = B.KETPAREL
 ,PTA_KET_QTY = B.KETPTA
 ,PTA_KET_REL_PCT = B.KETPTAREL
 ,PA_MAS_QTY = B.MASPA
 ,PA_MAS_REL_PCT = B.MASPAREL
 ,PTA_MAS_QTY = B.MASPTA
 ,PTA_MAS_REL_PCT = B.MASPTAREL
 ,PA_MET_QTY = B.METPA
 ,PA_MET_REL_PCT = B.METPAREL
 ,PTA_MET_QTY = B.METPTA
 ,PTA_MET_REL_PCT = B.METPTAREL
 ,PA_MFV_QTY = B.MFVPA
 ,PA_MFV_REL_PCT = B.MFVPAREL
 ,PTA_MFV_QTY = B.MFVPTA
 ,PTA_MFV_REL_PCT = B.MFVPTAREL
 ,PA_RPL_QTY = B.RPLPA
 ,PA_RPL_REL_PCT = B.RPLPAREL
 ,PTA_RPL_QTY = B.RPLPTA
 ,PTA_RPL_REL_PCT = B.RPLPTAREL
;

 