CREATE TABLE dbo.DB_PATCHES
 (
	PATCH_NAME varchar(1000) not null primary key,
	DEPLOYED_DATE date not null
 );

 CREATE TABLE dbo.USERS	
 (
	USER_NAME VARCHAR(128) NOT NULL PRIMARY KEY,
	PASSWORD VARCHAR(128) NOT NULL
 );
 
 CREATE TABLE dbo.ROLES
 (
	ROLE VARCHAR(20) NOT NULL PRIMARY KEY
 );
 
 CREATE TABLE dbo.USER_ROLES
 (
	ROLE VARCHAR(20) NOT NULL,
	USER_NAME VARCHAR(128) NOT NULL
 );
 
 ALTER TABLE dbo.USER_ROLES ADD CONSTRAINT USER_NAME_FK FOREIGN KEY(USER_NAME) 
 REFERENCES dbo.USERS (USER_NAME);
 
 ALTER TABLE dbo.USER_ROLES ADD CONSTRAINT ROLE_FK FOREIGN KEY(ROLE) 
 REFERENCES dbo.ROLES (ROLE);

 CREATE TABLE dbo.TRAITS
 (
	TRAIT VARCHAR(10) NOT NULL PRIMARY KEY,
	DESCRIPTION VARCHAR(200)  NULL,
	UNIT VARCHAR(50) NULL
 );


CREATE TABLE dbo.ANIMALS
 (
 ANIMAL_ID VARCHAR(128) NOT NULL PRIMARY KEY,
SIRE_ID VARCHAR(128) NULL,
DAM_ID VARCHAR(128) NULL,
SEX VARCHAR(128) NULL,
LONG_NAME VARCHAR(500) NULL,
SHORT_NAME VARCHAR(200) NULL,
BREED_CODE VARCHAR(128) NULL,
BIRTH_DATE DATE,
SRC  VARCHAR(128) NULL,
MODIFY_DATE  DATE,
MBC  VARCHAR(128) NULL,
REG VARCHAR(128) NULL,
CODES VARCHAR(128) NULL,
RHA VARCHAR(128) NULL,
RECESSIVES VARCHAR(128) NULL
 );

 
 
 CREATE TABLE dbo.ANIMAL_ALIAS
 (
 ALIAS_ID VARCHAR(128) NOT NULL,
 SRC VARCHAR(128) NOT NULL,
KEY VARCHAR(128) NULL,
ANIMAL_ID VARCHAR(128) NOT NULL,
ALIAS_NAME VARCHAR(500) NULL,
SEX VARCHAR(128) NULL,
PREG VARCHAR(128) NULL,
REG_CODES VARCHAR(128) NULL,
MODIFY_DATE DATE,
PRIMARY KEY (ALIAS_ID,SRC)
);


 ALTER TABLE dbo.ANIMAL_ALIAS  ADD  CONSTRAINT ANIMAL_ALIAS_FK FOREIGN KEY(ANIMAL_ID)
REFERENCES dbo.ANIMALS (ANIMAL_ID);

 
 CREATE TABLE dbo.BV_RUNS
 (
	RUN_ID VARCHAR(200) NOT NULL PRIMARY KEY,
	RUN_NAME VARCHAR(200) NOT NULL,
	RUN_TYPE VARCHAR(128) NULL,
	RUN_DATE DATE NULL 
 );
 
 CREATE TABLE dbo.BULL_EVAL_PED_COMP
 (
 RUN_ID VARCHAR(200) NOT NULL,
ANIMAL_ID VARCHAR(128) NOT NULL,
SIRE_ID VARCHAR(128) NULL,
DAM_ID VARCHAR(128) NULL,
BIRTH_DATE DATE NULL,
PED_COMP INT NULL,
ITB_ID VARCHAR(128) NULL,
EVAL_BREED VARCHAR(128) NULL
 );
 
 ALTER TABLE dbo.BULL_EVAL_PED_COMP  ADD  CONSTRAINT BULL_EVAL_PED_COMP_RUN_ID_FK FOREIGN KEY(RUN_ID)
REFERENCES dbo.BV_RUNS (RUN_ID);
 

 ALTER TABLE dbo.BULL_EVAL_PED_COMP  ADD  CONSTRAINT BULL_EVAL_PED_COMP_ANIMAL_ID_FK FOREIGN KEY(ANIMAL_ID)
REFERENCES dbo.ANIMALS (ANIMAL_ID);
  
CREATE TABLE dbo.BULL_EVAL_PED_GENOMIC
 (
 RUN_ID VARCHAR(200) NOT NULL,
ANIMAL_ID VARCHAR(128) NOT NULL,
PED_GEN VARCHAR(128) NULL,
INBRD decimal(8,2) NULL,
EXP_FUT_INBRD decimal(8,2) NULL,
DAU_INBRD decimal(8,2) NULL,
RECESSIVE_CODES VARCHAR(128) NULL 
 );
 
ALTER TABLE dbo.BULL_EVAL_PED_GENOMIC  ADD  CONSTRAINT BULL_EVAL_PED_GENOMIC_RUN_ID_FK FOREIGN KEY(RUN_ID)
REFERENCES dbo.BV_RUNS (RUN_ID);


 ALTER TABLE dbo.BULL_EVAL_PED_GENOMIC  ADD  CONSTRAINT BULL_EVAL_PED_GENOMIC_ANIMAL_ID_FK FOREIGN KEY(ANIMAL_ID)
REFERENCES dbo.ANIMALS (ANIMAL_ID);

CREATE TABLE dbo.BULL_EVAL_PED_NAAB
 (
 RUN_ID VARCHAR(200) NOT NULL,
 ANIMAL_ID VARCHAR(128) NOT NULL,
CURRENT_STATUS VARCHAR(128) NULL,
CNTRL_STUD INT NULL,
SAMPLING_STATUS VARCHAR(128) NULL,
ORIG_STUD INT NULL,
ENTERED_AI_YM VARCHAR(128) NULL,
SHORT_NAME VARCHAR(128) NULL,
PRIMARY_STUD_CODE VARCHAR(128) NULL
 );

 ALTER TABLE dbo.BULL_EVAL_PED_NAAB  ADD  CONSTRAINT BULL_EVAL_PED_NAAB_RUN_ID_FK FOREIGN KEY(RUN_ID)
REFERENCES dbo.BV_RUNS (RUN_ID);


 ALTER TABLE dbo.BULL_EVAL_PED_NAAB  ADD  CONSTRAINT BULL_EVAL_PED_NAAB_ANIMAL_ID_FK FOREIGN KEY(ANIMAL_ID)
REFERENCES dbo.ANIMALS (ANIMAL_ID);

CREATE TABLE dbo.BULL_EVAL_PED_TRAITS_DTRS
 (
 RUN_ID VARCHAR(200) NOT NULL,
 ANIMAL_ID VARCHAR(128) NOT NULL,
COUNTRY VARCHAR(128) NULL,
YIELD_HERDS INT  NULL,
YIELD_DAUS INT NULL,
PROD_LIFE_HERDS INT NULL,
PROD_LIFE_DAUS INT NULL,
SCS_HERDS INT NULL,
SCS_DAUS INT NULL,
MAS_HERDS INT NULL,
MAS_DAUS INT NULL,
DPR_HERDS INT NULL,
DPR_DAUS INT NULL,
SIRE_CE_HERDS INT NULL,
SIRE_CE_CALV INT NULL,
DAU_CE_HERDS INT NULL,
DAU_CE_DAUS INT NULL,
SIRE_SB_HERDS INT NULL,
SIRE_SB_CALV INT NULL,
DAU_SB_HERDS INT NULL,
DAU_SB_DAUS INT NULL
 );

 ALTER TABLE dbo.BULL_EVAL_PED_TRAITS_DTRS  ADD  CONSTRAINT BULL_EVAL_PED_TRAITS_DTRS_RUN_ID_FK FOREIGN KEY(RUN_ID)
REFERENCES dbo.BV_RUNS (RUN_ID);


 ALTER TABLE dbo.BULL_EVAL_PED_TRAITS_DTRS  ADD  CONSTRAINT BULL_EVAL_PED_TRAITS_DTRS_ANIMAL_ID_FK FOREIGN KEY(ANIMAL_ID)
REFERENCES dbo.ANIMALS (ANIMAL_ID);

  
 CREATE TABLE dbo.BULL_EVAL_PED_TRAITS_MERIT
 (
 RUN_ID VARCHAR(200) NOT NULL,
 ANIMAL_ID VARCHAR(128) NOT NULL,
TRAIT VARCHAR(128) NULL,
PTA decimal(8,2) NULL,
REL decimal(8,2) NULL,
PA decimal(8,2) NULL,
RELPA decimal(8,2) NULL
 );

 ALTER TABLE dbo.BULL_EVAL_PED_TRAITS_MERIT  ADD  CONSTRAINT BULL_EVAL_PED_TRAITS_MERIT_RUN_ID_FK FOREIGN KEY(RUN_ID)
REFERENCES dbo.BV_RUNS (RUN_ID);


 ALTER TABLE dbo.BULL_EVAL_PED_TRAITS_MERIT  ADD  CONSTRAINT BULL_EVAL_PED_TRAITS_MERIT_ANIMAL_ID_FK FOREIGN KEY(ANIMAL_ID)
REFERENCES dbo.ANIMALS (ANIMAL_ID);
 
 
CREATE TABLE dbo.BULL_EVAL_PED_TRAITS_PERCENTILE
 (
 RUN_ID VARCHAR(200) NOT NULL,
 ANIMAL_ID VARCHAR(128) NOT NULL,
PERCENTILE VARCHAR(128) NULL,
GENOMICS_IND INT NULL
 );

 ALTER TABLE dbo.BULL_EVAL_PED_TRAITS_PERCENTILE ADD  CONSTRAINT BULL_EVAL_PED_TRAITS_PERCENTILE_RUN_ID_FK FOREIGN KEY(RUN_ID)
REFERENCES dbo.BV_RUNS (RUN_ID);


 ALTER TABLE dbo.BULL_EVAL_PED_TRAITS_PERCENTILE  ADD  CONSTRAINT BULL_EVAL_PED_TRAITS_PERCENTILE_ANIMAL_ID_FK FOREIGN KEY(ANIMAL_ID)
REFERENCES dbo.ANIMALS (ANIMAL_ID);

CREATE TABLE dbo.BULL_EVAL_PED_TRAITS_PIA
 (
 RUN_ID VARCHAR(200) NOT NULL,
 ANIMAL_ID VARCHAR(128) NOT NULL,
TRAIT VARCHAR(128) NULL,
PTA decimal(8,2) NULL,
REL  decimal(8,2) NULL,
DAUS int NULL,
HERDS INT NULL,
SRC VARCHAR(128) NULL,
MEAN decimal(8,2)  NULL,
DAUDEV decimal(8,2)  NULL,
PA decimal(8,2)  NULL,
RELPA decimal(8,2) NULL
 );

 ALTER TABLE dbo.BULL_EVAL_PED_TRAITS_PIA  ADD  CONSTRAINT BULL_EVAL_PED_TRAITS_PIA_RUN_ID_FK FOREIGN KEY(RUN_ID)
REFERENCES dbo.BV_RUNS (RUN_ID);


 ALTER TABLE dbo.BULL_EVAL_PED_TRAITS_PIA   ADD  CONSTRAINT BULL_EVAL_PED_TRAITS_PIA_ANIMAL_ID_FK FOREIGN KEY(ANIMAL_ID)
REFERENCES dbo.ANIMALS (ANIMAL_ID);

  
 CREATE TABLE dbo.BULL_EVAL_PED_TRAITS_SCR
 (
 RUN_ID VARCHAR(200) NOT NULL,
 ANIMAL_ID VARCHAR(128) NOT NULL,
PA decimal(8,2) NULL,
REL decimal(8,2) NULL,
BREEDINGS decimal(8,2) NULL
 );

 ALTER TABLE dbo.BULL_EVAL_PED_TRAITS_SCR ADD  CONSTRAINT BULL_EVAL_PED_TRAITS_SCR_RUN_ID_FK FOREIGN KEY(RUN_ID)
REFERENCES dbo.BV_RUNS (RUN_ID);


 ALTER TABLE dbo.BULL_EVAL_PED_TRAITS_SCR ADD  CONSTRAINT BULL_EVAL_PED_TRAITS_SCR_ANIMAL_ID_FK FOREIGN KEY(ANIMAL_ID)
REFERENCES dbo.ANIMALS (ANIMAL_ID);

 CREATE TABLE dbo.BULL_EVAL_TYPE_PIA
 (
 RUN_ID VARCHAR(200) NOT NULL,
 ANIMAL_ID VARCHAR(128) NOT NULL,
TRAIT VARCHAR(128) NULL,
DAU_AVG decimal(8,2) NULL,
PTA decimal(8,2)  NULL,
REL decimal(8,2)  NULL
 );

 ALTER TABLE dbo.BULL_EVAL_TYPE_PIA   ADD  CONSTRAINT BULL_EVAL_TYPE_PIA_RUN_ID_FK FOREIGN KEY(RUN_ID)
REFERENCES dbo.BV_RUNS (RUN_ID);


 ALTER TABLE dbo.BULL_EVAL_TYPE_PIA  ADD  CONSTRAINT BULL_EVAL_TYPE_PIA_ANIMAL_ID_FK FOREIGN KEY(ANIMAL_ID)
REFERENCES dbo.ANIMALS (ANIMAL_ID);


 
 CREATE TABLE dbo.CHIPS
 (
 BAR_CODE VARCHAR(128) NOT NULL PRIMARY KEY,
 CHIP_NAME VARCHAR(200) NOT NULL
 );
 
 CREATE TABLE dbo.GENOTYPE_SAMPLES
 (
 SAMPLE_ID VARCHAR(128) NOT NULL PRIMARY KEY 
 );
 
 CREATE TABLE dbo.ANIMAL_GENOTYPE_SAMPLE_NONIMATIONS
 (
    NOMINATION_ID INT  GENERATED BY DEFAULT AS IDENTITY 
      (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
	ANIMAL_ID VARCHAR(128) NOT NULL,
	SAMPLE_ID VARCHAR(128) NOT NULL,
	BAR_CODE VARCHAR(128) NOT NULL,
	POSITION VARCHAR(128) NOT NULL,
	USER_IND VARCHAR(128),
	PEND VARCHAR(128),
	FEE_CODE VARCHAR(128),
	PO VARCHAR(128),
	SIRE_STAT VARCHAR(128),
	DAM_STAT VARCHAR(128),
	NO_PROG int,
	TISSUE_SOURCE VARCHAR(128),
	LAB VARCHAR(128),
	REQ VARCHAR(128),
	SCAN_DATE DATE,
	EVAL_USE_DATE DATE,
	SNP_READ int,
	BREED_SNP_CONFLICTS int 
 );
 
  

  ALTER TABLE dbo.ANIMAL_GENOTYPE_SAMPLE_NONIMATIONS  ADD  CONSTRAINT ANIMAL_GENOTYPE_SAMPLE_NONIMATIONS_ANIMAL_ID_FK FOREIGN KEY(ANIMAL_ID)
REFERENCES dbo.ANIMALS (ANIMAL_ID);
  ALTER TABLE dbo.ANIMAL_GENOTYPE_SAMPLE_NONIMATIONS  ADD  CONSTRAINT ANIMAL_GENOTYPE_SAMPLE_NONIMATIONS_SAMPLE_ID_FK FOREIGN KEY(SAMPLE_ID)
REFERENCES dbo.GENOTYPE_SAMPLES (SAMPLE_ID);
  ALTER TABLE dbo.ANIMAL_GENOTYPE_SAMPLE_NONIMATIONS  ADD  CONSTRAINT ANIMAL_GENOTYPE_SAMPLE_NONIMATIONS_BAR_CODE_FK FOREIGN KEY(BAR_CODE)
REFERENCES dbo.CHIPS (BAR_CODE);


 CREATE UNIQUE INDEX AK_ANIMAL_GENOTYPE_SAMPLE_NONIMATIONS_Businesskey 
   ON dbo.ANIMAL_GENOTYPE_SAMPLE_NONIMATIONS (ANIMAL_ID,SAMPLE_ID,BAR_CODE,POSITION);   


 
 CREATE TABLE dbo.ANIMAL_GENOTYPE_CONFLICTS
 (
	ID INT  GENERATED BY DEFAULT AS IDENTITY 
      (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    NOMINATION_ID INT  NOT NULL,
	PEDIGREE_CHANGED VARCHAR(128),
	CONFLICT_TYPE VARCHAR(200),
	CONFLICT_CODE VARCHAR(128),
	CONFLICT_BARCODE VARCHAR(128),
	CONFLICT_POSITION VARCHAR(128),
	CONFLICT_AIMAL_ID VARCHAR(128),
	CONFLICT_SEX VARCHAR(128),
	INDICATOR_IN_USE VARCHAR(128) 
 );

 ALTER TABLE dbo.ANIMAL_GENOTYPE_CONFLICTS  ADD  CONSTRAINT ANIMAL_GENOTYPE_CONFLICTS_NOMINATION_ID_BAR_CODE_FK FOREIGN KEY(NOMINATION_ID)
REFERENCES dbo.ANIMAL_GENOTYPE_SAMPLE_NONIMATIONS (NOMINATION_ID);



CREATE TABLE dbo.ANIMAL_BLEND_CODE
 (
 RUN_ID VARCHAR(200) NOT NULL,
 ANIMAL_ID VARCHAR(128) NOT NULL,
BLEND_CODE VARCHAR(128) NULL 
 );

 ALTER TABLE dbo.ANIMAL_BLEND_CODE  ADD  CONSTRAINT ANIMAL_BLEND_CODE_RUN_ID_FK FOREIGN KEY(RUN_ID)
REFERENCES dbo.BV_RUNS (RUN_ID);


 ALTER TABLE dbo.ANIMAL_BLEND_CODE   ADD  CONSTRAINT ANIMAL_BLEND_CODE_ANIMAL_ID_FK FOREIGN KEY(ANIMAL_ID)
REFERENCES dbo.ANIMALS (ANIMAL_ID);

CREATE TABLE dbo.CONSTANTS
 (
 NAME VARCHAR(128) NOT NULL PRIMARY KEY,
 INT_VALUE INT NULL,
 STRING_VALUE VARCHAR(10000),
 DECIMAL_VALUE decimal(8,2)
 );



  
 CREATE INDEX NIX_ANIMAL_ALIAS_ANIMAL_ID
ON dbo.ANIMAL_ALIAS (
   ANIMAL_ID
) CLUSTER;
 
 
 CREATE INDEX NIX_ANIMAL_BLEND_CODE_ANIMAL_ID
ON dbo.ANIMAL_BLEND_CODE (
   ANIMAL_ID
) CLUSTER;
 
 
 CREATE INDEX NIX_ANIMAL_GENOTYPE_SAMPLE_NONIMATIONS_ANIMAL_ID
ON dbo.ANIMAL_GENOTYPE_SAMPLE_NONIMATIONS (
   ANIMAL_ID
) CLUSTER;
 
 
 CREATE INDEX NIX_BULL_EVAL_PED_COMP_ANIMAL_ID
ON dbo.BULL_EVAL_PED_COMP (
   ANIMAL_ID
) CLUSTER;
 
 
 CREATE INDEX NIX_BULL_EVAL_PED_GENOMIC_ANIMAL_ID
ON dbo.BULL_EVAL_PED_GENOMIC (
   ANIMAL_ID
) CLUSTER;
 
 
 CREATE INDEX NIX_BULL_EVAL_PED_NAAB_ANIMAL_ID
ON dbo.BULL_EVAL_PED_NAAB (
   ANIMAL_ID
) CLUSTER;
 
 
 CREATE INDEX NIX_BULL_EVAL_PED_TRAITS_DTRS_ANIMAL_ID
ON dbo.BULL_EVAL_PED_TRAITS_DTRS (
   ANIMAL_ID
) CLUSTER;
 
 
 CREATE INDEX NIX_BULL_EVAL_PED_TRAITS_MERIT_ANIMAL_ID
ON dbo.BULL_EVAL_PED_TRAITS_MERIT (
   ANIMAL_ID
) CLUSTER;
 
 
 CREATE INDEX NIX_BULL_EVAL_PED_TRAITS_PERCENTILE_ANIMAL_ID
ON dbo.BULL_EVAL_PED_TRAITS_PERCENTILE (
   ANIMAL_ID
) CLUSTER;
 
 
 CREATE INDEX NIX_BULL_EVAL_PED_TRAITS_PIA_ANIMAL_ID
ON dbo.BULL_EVAL_PED_TRAITS_PIA (
   ANIMAL_ID
) CLUSTER;
 
 
 CREATE INDEX NIX_BULL_EVAL_PED_TRAITS_SCR_ANIMAL_ID
ON dbo.BULL_EVAL_PED_TRAITS_SCR (
   ANIMAL_ID
) CLUSTER;
 
 
 CREATE INDEX NIX_BULL_EVAL_TYPE_PIA_ANIMAL_ID
ON dbo.BULL_EVAL_TYPE_PIA (
   ANIMAL_ID
) CLUSTER;
 