CREATE USER TEMPORARY TABLESPACE "UTMP4K" 
         PAGESIZE 4096 MANAGED BY AUTOMATIC STORAGE
         USING STOGROUP "IBMSTOGROUP"
         EXTENTSIZE 4
         PREFETCHSIZE AUTOMATIC
         BUFFERPOOL "IBMDEFAULTBP"
         OVERHEAD INHERIT
         TRANSFERRATE INHERIT
         FILE SYSTEM CACHING
         DROPPED TABLE RECOVERY OFF;
		  
	CREATE BUFFERPOOL BP8K pagesize 8K;
CREATE SYSTEM TEMPORARY TABLESPACE STB_8 PAGESIZE 8K BUFFERPOOL BP8K;
CREATE BUFFERPOOL BP16K pagesize 16K;
CREATE SYSTEM TEMPORARY TABLESPACE STB_16 PAGESIZE 16K BUFFERPOOL BP16K;
CREATE BUFFERPOOL BP32K pagesize 32K;
CREATE SYSTEM TEMPORARY TABLESPACE STB_32 PAGESIZE 32K BUFFERPOOL BP32K; 
 
 
	CREATE GLOBAL TEMPORARY TABLE SESSION.TmpAnimalLists 
	(
		ANIMAL_ID VARCHAR(128),
		ORDER INT
	)  ON COMMIT PRESERVE ROWS;
  
   CREATE GLOBAL TEMPORARY TABLE SESSION.TmpAnimalListsInvalid 
	(
		ANIMAL_ID VARCHAR(128),
		ORDER INT
	)  ON COMMIT PRESERVE ROWS;
  
	CREATE GLOBAL TEMPORARY TABLE SESSION.TmpAnimalLists_Infor 
	(
		ROOT_ANIMAL_ID varchar(128),
		ID_PREFERED varchar(139),
		ANIMAL_ID varchar(128),
		LONG_NAME varchar(500),
		SHORT_NAME varchar(200),
		BIRTH_DATE VARCHAR(10),
		SEX VARCHAR(1),
		MBC INT,
		RECODES varchar(128),
		SRC varchar(128),
		MODIFY_DATE VARCHAR(10),
		EVAL_BREED varchar(128),
		RUN_NAME varchar(200),
		RECESSIVES varchar(128),
		HAS_CROSS_REFERENCE varchar(1),
		PED_COMP int,
		PRIMARY_STUD_CODE varchar(128),
		CURRENT_STATUS varchar(128),
		ENTERED_AI_YM varchar(128),
		CNTRL_STUD int,
		ORIG_STUD int,
		SAMPLING_STATUS varchar(128),
		SCR_PA decimal(8,2),
		SCR_REL decimal(8,2),
		SCR_BREEDINGS decimal(8,2),
		BLEND_CODE varchar(128),
		PERCENTILE VARCHAR(128) NULL,
		GENOMICS_IND INT NULL
	) ON COMMIT PRESERVE ROWS;
	 
	 
	CREATE GLOBAL TEMPORARY TABLE SESSION.TmpAnimalLists_Alias
	(
		ROOT_ANIMAL_ID VARCHAR(128),
		ANIMAL_ID VARCHAR(128),
		ALIAS_ID VARCHAR(128),
		ALIAS_NAME VARCHAR(200),
		MODIFY_DATE VARCHAR(10),
		REG_CODES VARCHAR(128),
		SEX VARCHAR(1)
		 
	)  ON COMMIT PRESERVE ROWS;
	 
	 
	CREATE GLOBAL TEMPORARY TABLE SESSION.TmpAnimalLists_Ped
	(
		ROOT_ANIMAL_ID VARCHAR(128),
		ANIMAL_ID VARCHAR(128),
		SIRE_ID VARCHAR(128),
		DAM_ID VARCHAR(128),
		GENERATION int,
		BIRTH_DATE VARCHAR(10),
		LONG_NAME VARCHAR(200),
		Genotyped VARCHAR(1),
		SRC VARCHAR(128),
		IS_EXIST VARCHAR(1)
		 
	) ON COMMIT PRESERVE ROWS;

	CREATE GLOBAL TEMPORARY TABLE SESSION.TmpAnimalLists_BV_Merit 
	(
		ROOT_ANIMAL_ID varchar(128),
		TRAIT varchar(128),
		PTA decimal(8,2),
		REL decimal(8,2),
		PA decimal(8,2),
		RELPA decimal(8,2)
	) ON COMMIT PRESERVE ROWS;
	
	CREATE GLOBAL TEMPORARY TABLE SESSION.TmpAnimalLists_BV_indicator 
	(
		ROOT_ANIMAL_ID varchar(128),
		PED_GEN varchar(128),
		INBRD decimal(8,2),
		EXP_FUT_INBRD decimal(8,2),
		DAU_INBRD decimal(8,2)
	) ON COMMIT PRESERVE ROWS;
	
	CREATE GLOBAL TEMPORARY TABLE SESSION.TmpAnimalLists_BV_PIA
	(
		ROOT_ANIMAL_ID varchar(128),
		TRAIT varchar(128),
		PTA decimal(8,2),
		REL decimal(8,2),
		DAUS int,
		HERDS int,
		SRC varchar(128),
		MEAN decimal(8,2),
		DAUDEV decimal(8,2),
		PA decimal(8,2),
		RELPA decimal(8,2)
	) ON COMMIT PRESERVE ROWS;
	 
	 
	 CREATE GLOBAL TEMPORARY TABLE SESSION.TmpAnimalLists_BV_type_PIA
	(
		ROOT_ANIMAL_ID varchar(128),
		TRAIT varchar(128),
		DAU_AVG decimal(8,2),
		PTA decimal(8,2),
		REL decimal(8,2)
	) ON COMMIT PRESERVE ROWS;
	 
	 
	  CREATE GLOBAL TEMPORARY TABLE SESSION.TmpAnimalLists_BV_dtrs
	(
		ROOT_ANIMAL_ID varchar(128),
		COUNTRY varchar(128),
		YIELD_HERDS int,
		YIELD_DAUS int,
		PROD_LIFE_HERDS int,
		PROD_LIFE_DAUS int,
		SCS_HERDS int,
		SCS_DAUS int,
		MAS_HERDS int,
		MAS_DAUS int,
		DPR_HERDS int,
		DPR_DAUS int,
		SIRE_CE_HERDS int,
		SIRE_CE_CALV int,
		DAU_CE_HERDS int,
		DAU_CE_DAUS int,
		SIRE_SB_HERDS int,
		SIRE_SB_CALV int,
		DAU_SB_HERDS int,
		DAU_SB_DAUS int
	) ON COMMIT PRESERVE ROWS;
	 
	 
	 
	 CREATE GLOBAL TEMPORARY TABLE SESSION.TmpAnimalLists_Geno_Group
	   (
       ROOT_ANIMAL_ID VARCHAR(128),
		PI VARCHAR(128),
		GROUP VARCHAR(1),
		HRC VARCHAR(1),
		FEE_CODE VARCHAR(128),
		PAID VARCHAR(1),
		REQUESTOR VARCHAR(128)
       
      ) 
      on commit preserve rows;
      
       CREATE GLOBAL TEMPORARY TABLE SESSION.TmpAnimalLists_Geno_Sample
	   (
        ROOT_ANIMAL_ID VARCHAR(128),
		USER_IND VARCHAR(128),
		NOM_DATE VARCHAR(10),
		SAMPLE_ID VARCHAR(128),
		BAR_CODE VARCHAR(128),
		POSITION VARCHAR(128),
		CHIP_NAME VARCHAR(200),
		PEND VARCHAR(128),
		LAB VARCHAR(128),
		REQUESTOR VARCHAR(128),
		GNO_ARRIVAL_DATE VARCHAR(10),
		SNP_READ INT,
		BREED_SNP_CONFLICTS INT,
		EVAL_USE_DATE VARCHAR(10),
		HAS_CONFLICT VARCHAR(1)
       
      ) 
      on commit preserve rows;
      
     
	 CREATE GLOBAL TEMPORARY TABLE SESSION.TmpAnimalLists_Geno_Sample_Conflict
	   (
	   ROOT_ANIMAL_ID VARCHAR(128),
        PEDIGREE_CHANGED VARCHAR(128),
		CONFLICT_TYPE VARCHAR(200),
		CONFLICT_CODE VARCHAR(128),
		CONFLICT_BARCODE VARCHAR(128),
		CONFLICT_POSITION VARCHAR(128),
		CONFLICT_AIMAL_ID VARCHAR(258),
		INDICATOR_IN_USE VARCHAR(128),
		CONFLICT_GROUP VARCHAR(3000)
       
      )  
      on commit preserve rows;
      
CREATE GLOBAL TEMPORARY TABLE SESSION.animals
	   (
        ANIMAL_ID VARCHAR(128) NULL
		,SIRE_ID VARCHAR(128) NULL
		,DAM_ID VARCHAR(128) NULL	
		,GENERATION INT NULL
		,ROOT_ANIMAL_ID  VARCHAR(128)
       
      ) 
      on commit preserve rows;
      
      
     
	CREATE GLOBAL TEMPORARY TABLE SESSION.animal_0
	   (
        ANIMAL_ID VARCHAR(128) NULL
		,SIRE_ID VARCHAR(128) NULL
		,DAM_ID VARCHAR(128) NULL	
		,GENERATION INT NULL
		,ROOT_ANIMAL_ID  VARCHAR(128)
       
      ) 
      on commit preserve rows;
      
      

