CREATE OR REPLACE PROCEDURE rpt_Avg_Evl_By_Most_Daugter_Country
--======================================================================================
--Author: Nghi Ta
--Created Date: 2020-07-06
--Description: Get average evaluations by country of most daughters
--Output: 
--       +Ds1: data include: country, yield, scs, longevity, type, and calving ease
--======================================================================================
( in @input_char varchar(10000),
  in @is_export smallint default 0,
  in @v_export_id varchar(128)
)
 
 dynamic result sets  10
BEGIN
    
    DECLARE input_xml XML;
      
   DECLARE V_EVAL_PDATE SMALLINT;
   DECLARE v_BREED_CODE CHAR(2); 
   DECLARE DEFAULT_DATE VARCHAR(10); 
   
   DECLARE v_IS_SHOW_YIELD CHAR(1); 
   DECLARE v_IS_SHOW_SCS CHAR(1); 
   DECLARE v_IS_SHOW_LONGEVITY CHAR(1); 
   DECLARE v_IS_SHOW_TYPE CHAR(1); 
   DECLARE v_IS_SHOW_CEASE CHAR(1);  
   DECLARE v_data clob(2M); 
   DECLARE EXPORT_PATH varchar(200);
   DECLARE EXPORT_FILE_NAME varchar(300); 
   DECLARE EXPORT_ID varchar(128);
   
   DECLARE sql_query_country_list varchar(10000); 
   DECLARE sql_query varchar(30000); 
   DECLARE sql_query_2 varchar(30000); 
   DECLARE sql_query_exp_header varchar(10000);  
   DECLARE sql_query_get_report_data varchar(30000); 
   
   DECLARE C1 CURSOR WITH RETURN FOR D1; 

    DECLARE GLOBAL TEMPORARY TABLE SESSION.TmpFilterInputs 
	(
		Field      VARCHAR(50),
		Value       VARCHAR(50)
	) WITH REPLACE ON COMMIT PRESERVE ROWS;
	
	DECLARE GLOBAL TEMPORARY TABLE SESSION.TmpFilterInputsMultiSelect 
	(
		Field      VARCHAR(128),
		Value       VARCHAR(128),
		Order  smallint  GENERATED BY DEFAULT AS IDENTITY  (START WITH 1 INCREMENT BY 1)  
	) WITH REPLACE ON COMMIT PRESERVE ROWS;
	
	
	 DECLARE GLOBAL TEMPORARY TABLE SESSION.v_TmpCountryList
	(
		COUNTRY_CODE  varchar(10) 
	) WITH REPLACE ON COMMIT PRESERVE ROWS;

    DECLARE GLOBAL TEMPORARY TABLE SESSION.v_TmpTraitGroups
	(
		TRAIT_GROUP  varchar(30) ,
		ORDER smallint
	) WITH REPLACE ON COMMIT PRESERVE ROWS; 

   DECLARE GLOBAL TEMPORARY TABLE SESSION.TmpReportData 
	(
		MOST_DAU_COUNTRY_CODE   char(3)
		,NUM_BULL_YEILD   char(15)
		,MEAN_DAUS  char(10)
		,MEAN_NM  char(10)
		,MEAN_NM_REL  char(10)
		,MEAN_MILK  char(10)
		,MEAN_FAT  char(10)
		,MEAN_PROT  char(10)
		,NUM_BULL_SCS  char(15)
		,MEAN_SCS  char(10)
		,NUM_BULL_LONGEVITY  char(15)
		,MEAN_PL  char(10)
		,NUM_BULL_TYPE  char(15)
		,MEAN_SIZE  char(10)
		,MEAN_UDDER  char(10)
		,MEAN_FEET_LEGS  char(10)
		,NUM_BULL_SCE  char(15)
		,MEAN_SCE_DBH  char(10)
		,NUM_BULL_DCE  char(15)
		,MEAN_DCE_DBH  char(10)
	) WITH REPLACE ON COMMIT PRESERVE ROWS;
  
 IF @is_export= 0 then
 
	SET input_xml =  xmlparse(document @input_char); 
	 
	INSERT INTO SESSION.TmpFilterInputs 
	(    
		Field,
		Value
	)
	 SELECT  
		 XML_BOOKS.Field,
		 XML_BOOKS.Value		 
		FROM  
		XMLTABLE(
		'$doc/Inputs/Item' 
		PASSING input_xml AS "doc"
		COLUMNS 
		 
		Field      VARCHAR(128)  PATH 'Field',
		Value       VARCHAR(3000)  PATH 'Value' 
		) AS XML_BOOKS;     
		 
		 
   INSERT INTO SESSION.TmpFilterInputsMultiSelect 
	(    
		Field,
		Value 
	)
   SELECT  
		 XML_BOOKS.Field,
		 XML_BOOKS.Value		 
		FROM  
		XMLTABLE(
		'$doc/Inputs/Multi_Item/Item' 
		PASSING input_xml AS "doc"
		COLUMNS 
		 
		Field      VARCHAR(128)  PATH 'Field',
		Value       VARCHAR(3000)  PATH 'Value' 
		) AS XML_BOOKS;  
	
	
	
	INSERT INTO SESSION.v_TmpCountryList
	   (
	   COUNTRY_CODE 
	   )
	
	SELECT VALUE 
   FROM SESSION.TmpFilterInputsMultiSelect
   WHERE FIELD ='COUNTRY_CODE';
   
   
   INSERT INTO SESSION.v_TmpTraitGroups
	   (
	   TRAIT_GROUP 
	   )
	
	SELECT VALUE 
   FROM SESSION.TmpFilterInputsMultiSelect
   WHERE FIELD ='TRAIT_GROUP';
    
   
   SET v_BREED_CODE = (SELECT VALUE FROM SESSION.TmpFilterInputs WHERE FIELD ='BREED_CODE' limit 1); 
   SET v_EVAL_PDATE = (SELECT MAX(RUN_PDATE) FROM TABLE (fn_Get_List_Run_Date()));
    
   SET v_IS_SHOW_YIELD = (SELECT '1' FROM SESSION.v_TmpTraitGroups WHERE TRAIT_GROUP ='Yield' limit 1);
   SET v_IS_SHOW_SCS = (SELECT '1' FROM SESSION.v_TmpTraitGroups WHERE TRAIT_GROUP ='SCS' limit 1);
   SET v_IS_SHOW_LONGEVITY = (SELECT '1' FROM SESSION.v_TmpTraitGroups WHERE TRAIT_GROUP ='Longevity' limit 1);
   SET v_IS_SHOW_TYPE = (SELECT '1' FROM SESSION.v_TmpTraitGroups WHERE TRAIT_GROUP ='Type' limit 1);
   SET v_IS_SHOW_CEASE = (SELECT '1' FROM SESSION.v_TmpTraitGroups WHERE TRAIT_GROUP ='Calving Ease' limit 1);  
     
   SET EXPORT_ID = (select varchar_format(current date,'YYYYMMDD') || replace(cast(current time as varchar(10)),':','') from sysibm.sysdummy1);   
   
   select   substr(xmlserialize(xmlagg(xmltext( ','''||COUNTRY_CODE||''''
										 	 ) ) as VARCHAR(30000)),2) 
	       
		 into  sql_query_country_list 
   from  SESSION.v_TmpCountryList  
    ; 
   
      
     
   DECLARE GLOBAL TEMPORARY TABLE SESSION.TmpReportData 
	(
		MOST_DAU_COUNTRY_CODE   char(3)
		,NUM_BULL_YEILD   char(15)
		,MEAN_DAUS  char(10)
		,MEAN_NM  char(10)
		,MEAN_NM_REL  char(10)
		,MEAN_MILK  char(10)
		,MEAN_FAT  char(10)
		,MEAN_PROT  char(10)
		,NUM_BULL_SCS  char(15)
		,MEAN_SCS  char(10)
		,NUM_BULL_LONGEVITY  char(15)
		,MEAN_PL  char(10)
		,NUM_BULL_TYPE  char(15)
		,MEAN_SIZE  char(10)
		,MEAN_UDDER  char(10)
		,MEAN_FEET_LEGS  char(10)
		,NUM_BULL_SCE  char(15)
		,MEAN_SCE_DBH  char(10)
		,NUM_BULL_DCE  char(15)
		,MEAN_DCE_DBH  char(10)
	) WITH REPLACE ON COMMIT PRESERVE ROWS;
  
  SET sql_query ='
insert into SESSION.TmpReportData 
(
	MOST_DAU_COUNTRY_CODE 
	'||case when v_IS_SHOW_YIELD ='1' then '
	,NUM_BULL_YEILD 
	,MEAN_DAUS
	,MEAN_NM
	,MEAN_NM_REL
	,MEAN_MILK
	,MEAN_FAT
	,MEAN_PROT'
	        else ''
	   end
	||case when v_IS_SHOW_SCS ='1' then '
	,NUM_BULL_SCS
	,MEAN_SCS'
	        else ''
	   end
	||case when v_IS_SHOW_LONGEVITY ='1' then '
	,NUM_BULL_LONGEVITY
	,MEAN_PL'
	        else ''
	   end
	||case when v_IS_SHOW_TYPE ='1' then '
	,NUM_BULL_TYPE
	,MEAN_SIZE
	,MEAN_UDDER
	,MEAN_FEET_LEGS'
	        else ''
	   end
	||case when v_IS_SHOW_CEASE ='1' then '
	,NUM_BULL_SCE
	,MEAN_SCE_DBH
	,NUM_BULL_DCE
	,MEAN_DCE_DBH'
	        else ''
	   end
	||' 
)

select c.COUNTRY_CODE as MOST_DAU_COUNTRY_CODE
	'||case when v_IS_SHOW_YIELD ='1' then '
	,bv.NUM_BULL_YIELD 
	,bv.MEAN_DAUS
	,bv.MEAN_NM
	,bv.MEAN_NM_REL
	,bv.MEAN_MILK
	,bv.MEAN_FAT
	,bv.MEAN_PROT'
	        else ''
	   end
	||case when v_IS_SHOW_SCS ='1' then '
	,bv.NUM_BULL_SCS 
	,float2char(bv.MEAN_SCS,0.01) as MEAN_SCS'
	        else ''
	   end
	||case when v_IS_SHOW_LONGEVITY ='1' then '
	,bv.NUM_BULL_LONGEVITY 
	,float2char(bv.MEAN_PL,0.1) as MEAN_PL'
	        else ''
	   end
	||case when v_IS_SHOW_TYPE ='1' then '
	,bv.NUM_BULL_TYPE
	,float2char(bv.MEAN_SIZE,0.01) as MEAN_SIZE
	,float2char(bv.MEAN_UDDER,0.01) as MEAN_UDDER
	,float2char(bv.MEAN_FEET_LEGS,0.01) as MEAN_FEET_LEGS'
	        else ''
	   end
	||case when v_IS_SHOW_CEASE ='1' then '
	,sce.NUM_BULL as NUM_BULL_SCE
	,float2char(sce.MEAN_SCE_DBH,0.01) as MEAN_SCE_DBH
	,dce.NUM_BULL as NUM_BULL_DCE
	,float2char(dce.MEAN_DCE_DBH,0.01) as MEAN_DCE_DBH'
	        else ''
	   end
	||'
	 
from  SESSION.v_TmpCountryList c
'||case when v_IS_SHOW_YIELD ='1' 
             or v_IS_SHOW_SCS = '1'
             or v_IS_SHOW_LONGEVITY = '1'
             or v_IS_SHOW_TYPE = '1' 
 then '
left join  
(
select  
		MOST_DAU_COUNTRY_CODE
		'||case when v_IS_SHOW_YIELD ='1' then '
		,sum(case when str2int(substring(bv.TRAIT_PTA_QTY_SEG,1,2)) is not null then 1 else 0 end) as NUM_BULL_YIELD  
		,avg(str2int(substring(bv.TRAIT_DAU_QTY_SEG,1,4))) as MEAN_DAUS
		,avg(cast(bbv.NM_AMT as int)) as MEAN_NM
		,avg(cast(bbv.NM_REL_PCT as int)) as MEAN_NM_REL
		,avg(str2int(substring(bv.TRAIT_PTA_QTY_SEG,1,2))) as MEAN_MILK
		,avg(str2int(substring(bv.TRAIT_PTA_QTY_SEG,3,2))) as MEAN_FAT
		,avg(str2int(substring(bv.TRAIT_PTA_QTY_SEG,5,2))) as MEAN_PROT'
		        else ''
		   end 
		 || 
		 case when v_IS_SHOW_SCS ='1' then '
		,sum(case when str2int(substring(bv.TRAIT_PTA_QTY_SEG,9,2)) is not null then 1 else 0 end) as NUM_BULL_SCS
		,avg(str2int(substring(bv.TRAIT_PTA_QTY_SEG,9,2)))*0.01 as MEAN_SCS'
		        else ''
		   end 
		 || 
		 case when v_IS_SHOW_LONGEVITY ='1' then '
		,sum(case when str2int(substring(bv.TRAIT_PTA_QTY_SEG,7,2)) is not null then 1 else 0 end) as NUM_BULL_LONGEVITY
		,avg(str2int(substring(bv.TRAIT_PTA_QTY_SEG,7,2)))*0.1 as MEAN_PL'
		        else ''
		   end 
		 ||
		 case when v_IS_SHOW_TYPE ='1' then '
		,sum(case when tcpst.anim_key is not null then 1 else 0 end) as NUM_BULL_TYPE 
		,avg(tcpst.SIZE_CPST) AS MEAN_SIZE
		,avg(tcpst.UDDER_CPST) AS MEAN_UDDER
		,avg(tcpst.FEET_LEGS_CPST) AS MEAN_FEET_LEGS '
		        else ''
		   end 
		 || 
		 ' 
from  interbull_table bv 
inner join pedigree_table ped 
   on ped.anim_key = bv.anim_key
   and ped.species_code = ''0''
   and bv.eval_pdate = '||v_EVAL_PDATE||'
   and (bv.eval_pdate - ped.birth_pdate) between 2372.5 and 3102.5  /** bulls 6.5 - 8.5 yrs old **/ 
   and bv.MOST_DAU_COUNTRY_CODE in ('||sql_query_country_list||')
   and bv.EVAL_BREED_CODE = '''||v_BREED_CODE||'''
inner join bull_evl_table_decode bbv
   on bv.anim_key = bbv.anim_key
   and bv.eval_pdate = bbv.eval_pdate  
   and coalesce(bbv.MLK_DAUS_QTY,0) >0
   
'||case when v_IS_SHOW_TYPE ='1' then '
left join  TYPE_CPST_TABLE tcpst
   on tcpst.anim_key = bv.anim_key
   and tcpst.eval_pdate = bv.eval_pdate
   and tcpst.source_code =''I'' 
'
        else ''
   end 
||' 
group by bv.MOST_DAU_COUNTRY_CODE
 
)bv 
on c.COUNTRY_CODE = bv.MOST_DAU_COUNTRY_CODE 
 
'
        else ''
   end
||
case when v_IS_SHOW_CEASE ='1' then ' 
left join 
(
select  
		SCE_COUNTRY_MOST_CALVINGS,
		count(1) as NUM_BULL,
		avg(SCE_DIFF_BIRTH_PCT) AS MEAN_SCE_DBH  
from  CT_ITB_TABLE tcpst
inner join pedigree_table ped 
   on ped.anim_key = tcpst.anim_key
   and ped.species_code = ''0''
   and tcpst.eval_pdate = '||v_EVAL_PDATE||'  
   and (tcpst.eval_pdate - ped.birth_pdate) between 2372.5 and 3102.5  /** bulls 6.5 - 8.5 yrs old **/   
   and tcpst.EVAL_BREED_CODE = '''||v_BREED_CODE||'''
   and tcpst.SCE_COUNTRY_MOST_CALVINGS in ('||sql_query_country_list||')
   and tcpst.SCE_SOURCE_CODE = ''I'' 
      
group by SCE_COUNTRY_MOST_CALVINGS
 
)sce
on c.COUNTRY_CODE =  sce.SCE_COUNTRY_MOST_CALVINGS

left join 
(
select  
		DCE_COUNTRY_MOST_CALVINGS,
		count(1) as NUM_BULL,
		avg(DCE_DIFF_BIRTH_PCT) AS MEAN_DCE_DBH  
from  CT_ITB_TABLE tcpst
inner join pedigree_table ped 
   on ped.anim_key = tcpst.anim_key
   and ped.species_code = ''0''
   and tcpst.eval_pdate = '||v_EVAL_PDATE||'  
   and (tcpst.eval_pdate - ped.birth_pdate) between 2372.5 and 3102.5  /** bulls 6.5 - 8.5 yrs old **/   
   and tcpst.EVAL_BREED_CODE = '''||v_BREED_CODE||'''
   and tcpst.DCE_COUNTRY_MOST_CALVINGS in ('||sql_query_country_list||')
   and tcpst.DCE_SOURCE_CODE = ''I'' 
      
group by DCE_COUNTRY_MOST_CALVINGS
 
)dce
on c.COUNTRY_CODE =  dce.DCE_COUNTRY_MOST_CALVINGS 

 '
        else ''
   end
||'

order by  '||
           ( select substr(xmlserialize(xmlagg(xmltext ( ','|| case when trait_group ='Calving Ease' then 'sce.NUM_BULL desc nulls last, dce.NUM_BULL desc nulls last'
                                                                    else 'bv.NUM_BULL_'||UPPER(trait_group) || ' desc nulls last'
                                                                end
                                                             
	                                             )  ) as VARCHAR(30000)),2) 
			 from SESSION.v_TmpTraitGroups
			 )

 ; 

set sql_query_2 = '
select MOST_DAU_COUNTRY_CODE 
	'||case when v_IS_SHOW_YIELD ='1' then '
	,NUM_BULL_YEILD 
	,MEAN_DAUS
	,MEAN_NM
	,MEAN_NM_REL
	,MEAN_MILK
	,MEAN_FAT
	,MEAN_PROT'
	        else ''
	   end
	||case when v_IS_SHOW_SCS ='1' then '
	,NUM_BULL_SCS
	,MEAN_SCS'
	        else ''
	   end
	||case when v_IS_SHOW_LONGEVITY ='1' then '
	,NUM_BULL_LONGEVITY
	,MEAN_PL'
	        else ''
	   end
	||case when v_IS_SHOW_TYPE ='1' then '
	,NUM_BULL_TYPE
	,MEAN_SIZE
	,MEAN_UDDER
	,MEAN_FEET_LEGS'
	        else ''
	   end
	||case when v_IS_SHOW_CEASE ='1' then '
	,NUM_BULL_SCE
	,MEAN_SCE_DBH
	,NUM_BULL_DCE
	,MEAN_DCE_DBH'
	        else ''
	   end
	||' 
 from SESSION.TmpReportData';
 
 -- Prepare for export data
 set sql_query_exp_header = '
Average PTA for Recently Progeny-Tested Bulls by Country of Most Daughters
 
'||cast('' as char(10))||
 (select substr(xmlserialize(xmlagg(xmltext (case   when trait_group ='Yield' then CenterAlign(trait_group,75)
													 when trait_group ='SCS' then CenterAlign(trait_group,25) 
													 when trait_group ='Longevity' then CenterAlign(trait_group,30)
													 when trait_group ='Type' then CenterAlign(trait_group,45)
													 when trait_group ='Calving Ease' then CenterAlign(trait_group,50)
										      end
                                                             
	                                             )  ) as VARCHAR(30000)),1) 
	 from SESSION.v_TmpTraitGroups
	 )
	||
'
'||LeftAlignWithChar('Country',10,'')||
	(select substr(xmlserialize(xmlagg(xmltext(case  when trait_group ='Yield' then RightAlign('Bulls(no.)',15)||RightAlign('Daus',10)||RightAlign('NM$',10)||RightAlign('NM$ REL',10)||RightAlign('Milk',10)||RightAlign('Fat',10)||RightAlign('Protein',10)
													 when trait_group ='SCS' then RightAlign('Bulls(no.)',15)||RightAlign('SCS',10) 
													 when trait_group ='Longevity' then RightAlign('Bulls(no.)',15)||RightAlign('Productive Life',15)
													 when trait_group ='Type' then RightAlign('Bulls(no.)',15)||RightAlign('Size',10)||RightAlign('Udder',10)||RightAlign('Feet Legs',10)
													 when trait_group ='Calving Ease' then RightAlign('SCE Bulls(no.)',15)||RightAlign('Sire %DBH',10)||RightAlign('DCE Bulls(no.)',15)||RightAlign('Daus %DBH',10)
										      end
                                                             
	                                             )  ) as VARCHAR(30000)),1) 
	 from SESSION.v_TmpTraitGroups
	 ) ||
'
'
	 ;
 
 
 set sql_query_get_report_data = '
 
      insert into EXPORT_DATA_HISTORICAL(ExportID, Data)
  	  select '''||EXPORT_ID||''', '''||sql_query_exp_header||''' ||
  	  
  	   (select substr(xmlserialize(xmlagg(xmltext (cast( MOST_DAU_COUNTRY_CODE as char(10))  
  	  '||
  	  (select substr(xmlserialize(xmlagg(xmltext(case  when trait_group ='Yield' then '||RightAlign(NUM_BULL_YEILD,15)||RightAlign(MEAN_DAUS,10)||RightAlign(MEAN_NM,10)||RightAlign(MEAN_NM_REL,10)||RightAlign(MEAN_MILK,10)||RightAlign(MEAN_FAT,10)||RightAlign(MEAN_PROT,10)'
														 when trait_group ='SCS' then '||RightAlign(NUM_BULL_SCS,15)||RightAlign(MEAN_SCS,10)'
														 when trait_group ='Longevity' then '||RightAlign(NUM_BULL_LONGEVITY,15)||RightAlign(MEAN_PL,15)'
														 when trait_group ='Type' then '||RightAlign(NUM_BULL_TYPE,15)||RightAlign(MEAN_SIZE,10)||RightAlign(MEAN_UDDER,10)||RightAlign(MEAN_FEET_LEGS,10)'
														 when trait_group ='Calving Ease' then '||RightAlign(NUM_BULL_SCE,15)||RightAlign(MEAN_SCE_DBH,10)||RightAlign(NUM_BULL_DCE,15)||RightAlign(MEAN_DCE_DBH,10)'
										          end
                                                             
	                                             )  ) as VARCHAR(30000)),1) 
	 from SESSION.v_TmpTraitGroups
	 ) 
  	  ||'
  	  ||''
''
	  
	     )) as VARCHAR(30000)),1) 
	  from SESSION.TmpReportData bv
	  )
	  from sysibm.sysdummy1 
	'; 
 
     EXECUTE IMMEDIATE sql_query;
     EXECUTE IMMEDIATE sql_query_get_report_data;
    
     PREPARE D1 FROM  sql_query_2;
     OPEN C1; 

	   BEGIN 
			DECLARE cursor4  CURSOR WITH RETURN for 
		     
		     SELECT EXPORT_ID 
		     FROM SYSIBM.SYSDUMMY1;
		    
			OPEN cursor4;
			  
		END;
		 
 ELSE  
	 
	  set v_data = ( select Data from EXPORT_DATA_HISTORICAL where ExportID = @v_export_id);
	    
      set EXPORT_PATH = (select string_value from dbo.constants where name ='Export_Folder');
		 
	  set EXPORT_FILE_NAME =   'AveragePTAbyCountry_'  ||(select varchar_format(current date,'YYYYMMDD') || replace(cast(current time as varchar(10)),':','') from sysibm.sysdummy1); 
	  set EXPORT_FILE_NAME =  EXPORT_PATH||'/'||EXPORT_FILE_NAME||'.txt';
        
      call usp_common_export_long_text(v_data, EXPORT_FILE_NAME);
       
          -- Retrieve data 
      
        begin
  		        declare cir cursor with return for
  		        select EXPORT_FILE_NAME  from sysibm.sysdummy1;
  		        open cir;
  	     end;
  	       
   END IF;
END