CREATE OR REPLACE PROCEDURE usp_Get_Herd_Owner_Info_By_ID
--======================================================
--Author: Nghi Ta
--Created Date: 2020-06-18
--Description: Get herd owner information: INT_ID, name, 
--birth date, cross reference...
--Output: 
--        +Ds1: herd general information: owner, address, center, privacy code, modify date 
--======================================================
( 
   IN @HERD_CODE INT
)
DYNAMIC RESULT SETS 1
    
BEGIN
   
	DECLARE DEFAULT_DATE DATE; 
	 
	DECLARE GLOBAL TEMPORARY TABLE SESSION.Tmp
	(	
		INPUT_VALUE VARCHAR(10000),
		ORDER INT  GENERATED BY DEFAULT AS IDENTITY 
      (START WITH 1 INCREMENT BY 1)
	
	)WITH REPLACE ON COMMIT PRESERVE ROWS;
	
	  
	SET DEFAULT_DATE = (select STRING_VALUE FROM dbo.constants where name ='Default_Date_Value' LIMIT 1 with UR);
      
     begin
		 	DECLARE cursor3 CURSOR WITH RETURN for
		 	
					 	
			with cte_herd
			as
			(
			  SELECT trim(OWNER_NAME) as OWNER_NAME,
					trim(FARM_NAME) as FARM_NAME,
					trim(STREET_ADDR) AS  STREET_ADDR, 
					trim(TOWN_ADDR) as TOWN_ADDR,
					trim(STATE_CODE) as STATE_CODE,
					substring(ZIP_CODE,1,5)|| coalesce('-'||nullif(substring(ZIP_CODE,6,4),'0000'),'')  as ZIP_CODE, 
					trim(COUNTRY_CODE) AS  COUNTRY_CODE,  
					HERD_CODE,
					CTR_CODE  ,
					PRIVACY_CODE,
					MODIFY_PDATE 
			  FROM HERDOWNER_TABLE 
			  WHERE HERD_CODE = @HERD_CODE 
			)		    
			, cte_town_state_zip as
			(
				select herd_code, 
					   LISTAGG(coalesce(' '|| nullif(t.TOWN_STATE_ZIP,''),''), '') AS TOWN_STATE_ZIP  
				from cte_herd ,
				lateral(VALUES (cte_herd.TOWN_ADDR), (cte_herd.STATE_CODE), (cte_herd.ZIP_CODE) ) AS t(TOWN_STATE_ZIP)
				group by herd_code
			) 
			,cte_location as
			(
				select cte_herd.herd_code, 
					   LISTAGG(coalesce('     '|| nullif(t2.ITEM,''),''), '') AS LOCATION     
				from cte_herd  
				left join  cte_town_state_zip  
					on cte_herd.herd_code = cte_town_state_zip.herd_code 
				,LATERAL(VALUES (cte_herd.FARM_NAME), (cte_herd.STREET_ADDR), (cte_town_state_zip.TOWN_STATE_ZIP) )  AS t2(ITEM)
				group by  cte_herd.herd_code
			
			)
			SELECT cte_herd.OWNER_NAME, 
			      TRIM( cte_location.LOCATION) AS LOCATION,
			      cte_herd.HERD_CODE,
				  cte_herd.CTR_CODE  ,
				  cte_herd.PRIVACY_CODE, 
				  varchar_format(DEFAULT_DATE+ cte_herd.MODIFY_PDATE,'YYYY-MM-DD') AS MODIFY_DATE 
			
			FROM cte_herd 
			INNER JOIN cte_location
			ON cte_herd.HERD_CODE = cte_location.HERD_CODE
			WITH UR;
 
		    OPEN cursor3;
	   end;
	   
     
END
