CREATE OR REPLACE PROCEDURE usp_Account_Approve_Account_Request
--======================================================
--Author: Tri Do
--Created Date: 2021-01-05
--Description: Approve Account Request
--Output: None
--======================================================
(
	@REQUEST_KEY INT,
	@inputs VARCHAR(30000) 
)
	DYNAMIC RESULT SETS 10
P1: BEGIN
 
	DECLARE SQLCODE INTEGER DEFAULT 0; 
    DECLARE RETCODE INTEGER DEFAULT 0;
	DECLARE ERR_MESSAGE VARCHAR(300);

 

	-- VALIDATION
 
	-- BEGIN TRANSACTION
	
	BEGIN
	
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION, SQLWARNING, NOT FOUND
		SET retcode = SQLCODE;

		CALL usp_Account_Add_Edit_Account(@inputs,'1');
		
		UPDATE ACCOUNT_REQUEST_TABLE
		SET STATUS = 'Approved'
			,MODIFIED_TIME = current timestamp
		WHERE REQUEST_KEY = @REQUEST_KEY;				          
				 
	END;

		IF RETCODE < 0 THEN
			ROLLBACK;
			
			SET ERR_MESSAGE = (SELECT SYSPROC.SQLERRM (CAST(RETCODE AS VARCHAR(20))) FROM SYSIBM.SYSDUMMY1);
			SIGNAL SQLSTATE '65000' SET MESSAGE_TEXT = ERR_MESSAGE;
		ELSE
			COMMIT;
			BEGIN
				DECLARE CURSOR1 CURSOR WITH RETURN FOR
				SELECT 1 AS RESULT
				FROM SYSIBM.SYSDUMMY1;
				
				OPEN CURSOR1;
			END;
		END IF;
END P1