CREATE OR REPLACE PROCEDURE usp_get_herd_ids_for_search
--=================================================================================================
--Author: Nghi Ta
--Created Date: 2020-06-18
--Description: Get list herd id from string input
--Output:
--        +Ds1: valid herd code
--        +Ds2: invalid herd code 
--=================================================================================================
(
	IN @INPUT_VALUE VARCHAR(10000)
	,@FILTER_TYPE VARCHAR(128) default 'HERD_CODE'
	,@DELIMITER VARCHAR(1) default ','
)
	DYNAMIC RESULT SETS 3
	LANGUAGE SQL
BEGIN
	   
	DECLARE GLOBAL TEMPORARY TABLE SESSION.TmpInputs
	(	
		INPUT_VALUE VARCHAR(128),
		ORDER INT  GENERATED BY DEFAULT AS IDENTITY 
      (START WITH 1 INCREMENT BY 1)
	
	)WITH REPLACE ON COMMIT PRESERVE ROWS;
	
	DECLARE GLOBAL TEMPORARY TABLE SESSION.TmpHerdCodeList
	(
		HERD_CODE int,
		ORDER smallint
	) WITH REPLACE  ON COMMIT PRESERVE ROWS;
   
	 
	INSERT INTO SESSION.TmpInputs(INPUT_VALUE)
	SELECT  ITEM FROM table(fn_Split_String (@INPUT_VALUE,@DELIMITER));
	
	-- Remove duplicate input
	MERGE INTO SESSION.TmpInputs as A
	 using
	 (
  
		 SELECT INPUT_VALUE, MIN(ORDER) AS MIN_ORDER
		 FROM SESSION.TmpInputs t	
		 GROUP BY INPUT_VALUE
		 with UR
	 )AS B
	 ON  A.INPUT_VALUE = B.INPUT_VALUE and A.ORDER <> B.MIN_ORDER 
	 WHEN MATCHED THEN
	 DELETE
	 ;
	 
	 INSERT INTO SESSION.TmpHerdCodeList
		(
			HERD_CODE,
			ORDER
		)
		  
		 SELECT 
		 h.HERD_CODE,
		 t.ORDER
		 FROM  SESSION.TmpInputs t
		 JOIN HERDOWNER_TABLE h 
		 	ON t.INPUT_VALUE = cast(h.HERD_CODE as varchar(128))
		 with UR; 
		 
	 --DS1: Herd code list
     	begin
		 	DECLARE cursor0 CURSOR WITH RETURN for
		 		
		 	SELECT  
			 	HERD_CODE, 
			 	row_number()over(order by ORDER )-1  as INDEX 
		 	FROM  SESSION.TmpHerdCodeList 
			ORDER BY  ORDER
			 with UR;
		  
		 	OPEN cursor0;
		 	 
	   end;
	 
	   
	  	-- DS2: invalid input
     	begin
		 	DECLARE cursor1_1 CURSOR WITH RETURN for
		 		
		 	SELECT DISTINCT i.INPUT_VALUE
		 	FROM SESSION.TmpInputs i
		 	LEFT JOIN SESSION.TmpHerdCodeList valid
		 	ON i.INPUT_VALUE = cast(valid.HERD_CODE as varchar(128))
		 	WHERE valid.HERD_CODE IS NULL
		 	AND i.INPUT_VALUE <> '' with UR;
		 	OPEN cursor1_1;
		 	 
	   end;
	    
END
