 
CREATE OR REPLACE PROCEDURE usp_Login_Register_New_Account
--======================================================
--Author: Linh Pham
--Created Date: 2020-12-28
--Description: Get imformation of Register New Account 
--Output:
--        +Ds1: 1 if success. Failed will raise exception
--======================================================
(
	@Inputs VARCHAR(30000)
)
	DYNAMIC RESULT SETS 1
	LANGUAGE SQL
P1: BEGIN
	DECLARE input_xml XML;
	
	DECLARE v_FIRT_NAME VARCHAR(30);
	DECLARE v_LAST_NAME VARCHAR(50);
	DECLARE v_ORGANIZATION VARCHAR(200);
	DECLARE v_TITLE VARCHAR(200);
	DECLARE v_EMAIL_ADDRESS CHAR(200);
	DECLARE v_PHONE VARCHAR(30);
	DECLARE v_EMAIL_USE_IND VARCHAR(1);
	DECLARE v_USERNAME VARCHAR(128);
	DECLARE v_PASSWORD VARCHAR(128);
	DECLARE v_REQUESTED_CREDENTIALS CHAR(128);
	DECLARE v_STATUS VARCHAR(10);
	DECLARE CREATED_TIME TIMESTAMP;
	DECLARE MODIFIED_TIME TIMESTAMP;
	DECLARE v_MODIFIED_BY VARCHAR(50);
	
	DECLARE GLOBAL TEMPORARY TABLE SESSION.TmpGetInputs 
	(
		Field      VARCHAR(128),
		Value       VARCHAR(3000)
	) WITH REPLACE ON COMMIT PRESERVE ROWS;
 	

	SET input_xml =  xmlparse(document @Inputs);

	INSERT INTO SESSION.TmpGetInputs 
	(    
		Field,
		Value
	)
	 SELECT  
			 XML_BOOKS.Field,
			 XML_BOOKS.Value		 
	FROM  
		XMLTABLE(
			'$doc/Inputs/Item' 
			PASSING input_xml AS "doc"
			COLUMNS 
			 
			Field      VARCHAR(128)  PATH 'Field',
			Value       VARCHAR(3000)  PATH 'Value' 
			) AS XML_BOOKS;
			
	SET v_FIRT_NAME = (SELECT VALUE FROM SESSION.TmpGetInputs WHERE UPPER(Field) ='FRIST_NAME' LIMIT 1 with UR);
	SET v_LAST_NAME = (SELECT VALUE FROM SESSION.TmpGetInputs WHERE UPPER(Field) ='LAST_NAME' LIMIT 1 with UR);
	SET v_ORGANIZATION = (SELECT VALUE FROM SESSION.TmpGetInputs WHERE UPPER(Field) ='ORGANIZATION' LIMIT 1 with UR);
	SET v_TITLE = (SELECT VALUE FROM SESSION.TmpGetInputs WHERE UPPER(Field) ='TITLE' LIMIT 1 with UR);
	SET v_EMAIL_ADDRESS = (SELECT VALUE FROM SESSION.TmpGetInputs WHERE UPPER(Field) ='EMAIL_ADDRESS' LIMIT 1 with UR);
	SET v_PHONE = (SELECT VALUE FROM SESSION.TmpGetInputs WHERE UPPER(Field) ='PHONE' LIMIT 1 with UR);
	SET v_EMAIL_USE_IND = (SELECT VALUE FROM SESSION.TmpGetInputs WHERE UPPER(Field) ='INCLUDE_EMAIL' LIMIT 1 with UR);
--	SET v_USERNAME = (SELECT VALUE FROM SESSION.TmpGetInputs WHERE UPPER(Field) ='USERNAME' LIMIT 1 with UR);
--	SET v_PASSWORD = (SELECT VALUE FROM SESSION.TmpGetInputs WHERE UPPER(Field) ='PASSWORD' LIMIT 1 with UR);
	SET v_REQUESTED_CREDENTIALS = (SELECT VALUE FROM SESSION.TmpGetInputs WHERE UPPER(Field) ='REQUESTED_CREDENTIALS' LIMIT 1 with UR);
	
	SET CREATED_TIME=(SELECT current timestamp  from sysibm.sysdummy1);
	SET MODIFIED_TIME = (SELECT current timestamp  from sysibm.sysdummy1)  ;
	SET v_MODIFIED_BY= (SELECT VALUE FROM SESSION.TmpGetInputs WHERE UPPER(Field) ='MODIFIED_BY' LIMIT 1 with UR);
	SET v_STATUS=(SELECT VALUE FROM SESSION.TmpGetInputs WHERE UPPER(Field) ='STATUS' LIMIT 1 with UR);
	--INSERT TABLE
	INSERT INTO ACCOUNT_REQUEST_TABLE
	(
		FIRST_NAME,
		LAST_NAME,
		EMAIL_ADDR,
		ORGANIZATION,
		TITLE,
		PHONE,
		EMAIL_USE_IND,
		STATUS, -- Approved, Rejected, New
		REQUESTED_CREDENTIAL,
		CREATED_TIME,
		MODIFIED_TIME,
		MODIFIED_BY
	)
	VALUES
	(
		v_FIRT_NAME,
		v_LAST_NAME,
		v_ORGANIZATION,
		v_EMAIL_ADDRESS,
		v_TITLE,
		v_PHONE,
		v_EMAIL_USE_IND,
		v_STATUS,
		v_REQUESTED_CREDENTIALS,
		CREATED_TIME,
		MODIFIED_TIME,
		v_MODIFIED_BY 
	);
        COMMIT;
	BEGIN
	DECLARE cursor1 CURSOR WITH RETURN for
	SELECT 
		1 AS RESULT
	FROM sysibm.sysdummy1;

	-- Cursor left open for client application
	OPEN cursor1;
	END;
END P1 
