ALTER TABLE TRAIT_TABLE ADD COMPARISON_THRESHOLD VARCHAR(10);
 
 UPDATE TRAIT_TABLE SET COMPARISON_THRESHOLD = '9' WHERE TRAIT_SHORT_NAME ='Mlk';
 UPDATE TRAIT_TABLE SET COMPARISON_THRESHOLD = '9' WHERE TRAIT_SHORT_NAME ='Fat';
 UPDATE TRAIT_TABLE SET COMPARISON_THRESHOLD = '9' WHERE TRAIT_SHORT_NAME ='Pro';
 UPDATE TRAIT_TABLE SET COMPARISON_THRESHOLD = '0.5' WHERE TRAIT_SHORT_NAME ='PL';
 UPDATE TRAIT_TABLE SET COMPARISON_THRESHOLD = '0.5' WHERE TRAIT_SHORT_NAME ='SCS';
 UPDATE TRAIT_TABLE SET COMPARISON_THRESHOLD = '0.5' WHERE TRAIT_SHORT_NAME ='DPR';
 UPDATE TRAIT_TABLE SET COMPARISON_THRESHOLD = '0.5' WHERE TRAIT_SHORT_NAME ='HCR';
 UPDATE TRAIT_TABLE SET COMPARISON_THRESHOLD = '0.5' WHERE TRAIT_SHORT_NAME ='CCR';
 UPDATE TRAIT_TABLE SET COMPARISON_THRESHOLD = '0.5' WHERE TRAIT_SHORT_NAME ='LIV';
 UPDATE TRAIT_TABLE SET COMPARISON_THRESHOLD = '0.5' WHERE TRAIT_SHORT_NAME ='GL';
 UPDATE TRAIT_TABLE SET COMPARISON_THRESHOLD = '0.5' WHERE TRAIT_SHORT_NAME ='MFV';
 UPDATE TRAIT_TABLE SET COMPARISON_THRESHOLD = '0.5' WHERE TRAIT_SHORT_NAME ='DAB';
 UPDATE TRAIT_TABLE SET COMPARISON_THRESHOLD = '0.5' WHERE TRAIT_SHORT_NAME ='KET';
 UPDATE TRAIT_TABLE SET COMPARISON_THRESHOLD = '0.5' WHERE TRAIT_SHORT_NAME ='MAS';
 UPDATE TRAIT_TABLE SET COMPARISON_THRESHOLD = '0.5' WHERE TRAIT_SHORT_NAME ='MET';
 UPDATE TRAIT_TABLE SET COMPARISON_THRESHOLD = '0.5' WHERE TRAIT_SHORT_NAME ='RPL';
 UPDATE TRAIT_TABLE SET COMPARISON_THRESHOLD = '0.5' WHERE TRAIT_SHORT_NAME ='EFC';
 UPDATE TRAIT_TABLE SET COMPARISON_THRESHOLD = '0.05' WHERE TRAIT_SHORT_NAME ='Fat%';
 UPDATE TRAIT_TABLE SET COMPARISON_THRESHOLD = '0.05' WHERE TRAIT_SHORT_NAME ='Pro%';


ALTER TABLE INDEX_TABLE ADD COMPARISON_THRESHOLD VARCHAR(10);

 UPDATE INDEX_TABLE SET COMPARISON_THRESHOLD = '50' WHERE INDEX_SHORT_NAME ='NM$';
 UPDATE INDEX_TABLE SET COMPARISON_THRESHOLD = '50' WHERE INDEX_SHORT_NAME ='FM$';
 UPDATE INDEX_TABLE SET COMPARISON_THRESHOLD = '50' WHERE INDEX_SHORT_NAME ='CM$';
 UPDATE INDEX_TABLE SET COMPARISON_THRESHOLD = '50' WHERE INDEX_SHORT_NAME ='GM$';

  INSERT INTO dbo.CONSTANTS(NAME,STRING_VALUE)
 VALUES('COMPARISON_THRESHOLD_SCR','0.5'),
 ('COMPARISON_THRESHOLD_REL','5'),
 ('COMPARISON_THRESHOLD_DAUS','10'),
 ('COMPARISON_THRESHOLD_HERDS','10') ;	