--- Migrate cdcb users
  create table mgr_cdcb_users
 ( 
  primary_affil varchar(128),
  drpc varchar(128), 
  email varchar(128), 
  lab varchar(128), 
  name varchar(128), 
  name_org varchar(128), 
  namefirst varchar(128), 
  namelast varchar(128), 
  phone varchar(128), 
  title varchar(128), 
  affiliates varchar(128), 
  roles varchar(128), 
  group varchar(128), 
  pass varchar(300) 
 );
  
  
   create table TMP_USER_INFO_TABLE
 ( 
 USER_KEY INT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  primary_affil varchar(128),
  drpc varchar(128), 
  email varchar(128), 
  lab varchar(128), 
  name varchar(128), 
  name_org varchar(128), 
  namefirst varchar(128), 
  namelast varchar(128), 
  phone varchar(128), 
  title varchar(128), 
  affiliates varchar(128), 
  roles varchar(128), 
  group varchar(128), 
  pass varchar(300) 
 );
  
  INSERT INTO TMP_USER_INFO_TABLE(
  primary_affil,
	  drpc,
	  email,
	  lab,
	  name,
	  name_org ,
	  namefirst,
	  namelast,
	  phone,
	  title ,
	  affiliates,
	  roles,
	  group,
	  pass  
  )
  SELECT 
	  primary_affil ,
	  drpc,
	  email,
	  lab,
	  name,
	  name_org ,
	  namefirst,
	  namelast,
	  phone,
	  title ,
	  affiliates,
	  roles,
	  group,
	  pass  
   FROM mgr_cdcb_users;

   
  /* 
  db2 connect to cdcbdb
 db2 IMPORT FROM "/home/db2inst1/Data/users.csv" OF DEL skipcount 1 INSERT INTO mgr_cdcb_users
 */
  
 ------USER_ACCOUNT_TABLE------
 INSERT INTO USER_INFO_TABLE
 ( USER_KEY,
 	FIRST_NAME,
	LAST_NAME,
	EMAIL_ADDR,
	ORGANIZATION,
	STATUS_CODE,
	TITLE,
	PHONE,
	EMAIL_USE_IND,
	CREATED_TIME,
	MODIFIED_TIME 
 )
 select USER_KEY,
	    namefirst AS FIRST_NAME,
		namelast AS LAST_NAME,
		email AS EMAIL_ADDR,
		name_org AS ORGANIZATION,
		'A' AS STATUS_CODE,
		TITLE,
		PHONE,
		'Y' AS EMAIL_USE_IND,
		CURRENT timestamp AS CREATED_TIME,
	    CURRENT timestamp AS MODIFIED_TIME
   
 from TMP_USER_INFO_TABLE; 

 ALTER TABLE USER_INFO_TABLE ALTER COLUMN USER_KEY RESTART WITH 4457;
 
 
 -----USER_ACCOUNT_TABLE--------   
 INSERT INTO USER_ACCOUNT_TABLE
 (
    USER_KEY,
	USER_NAME,
	PASSWORD,
	CREATED_TIME,
	MODIFIED_TIME
 ) 
 
 select USER_KEY,
         name,
         pass,
         CURRENT timestamp AS CREATED_TIME,
	     CURRENT timestamp AS MODIFIED_TIME
       
 from TMP_USER_INFO_TABLE
 where user_key <>3563;
 
 
 