UPDATE INDEX_TABLE SET INDEX_FULL_NAME = REPLACE(INDEX_FULL_NAME,'Amount','');

UPDATE TRAIT_TABLE SET TRAIT_FULL_NAME ='Fat Percent'
WHERE TRAIT_NAME ='Fat%';
UPDATE TRAIT_TABLE SET TRAIT_FULL_NAME ='Protein Percent' , trait_name ='Protein%'
WHERE TRAIT_NAME ='Pro%';