
  drop table COW_EVL_TABLE_DUMMY;
  CREATE TABLE COW_EVL_TABLE_DUMMY
 (
 ID INT  GENERATED BY DEFAULT AS IDENTITY 
      (START WITH 1 INCREMENT BY 1) NOT NULL,
 COW_ID char(17),
ANIM_KEY int not null,
EVAL_BREED_CODE char(2),
EVAL_PDATE smallint not null,
NM_REL_PCT smallint,
NM_PCTL char(2),
INDEX_AMT_SEG varchar(20),
TRAIT_PTA_REL_PCT_SEG varchar(100),
TRAIT_PTA_QTY_SEG varchar(100),
constraint COW_EVL_TABLE_DUMMY_pk primary key (ANIM_KEY,EVAL_PDATE)
);
 
insert into COW_EVL_TABLE_DUMMY
(
COW_ID,
ANIM_KEY, 
EVAL_BREED_CODE,
EVAL_PDATE,
NM_REL_PCT,
NM_PCTL,
INDEX_AMT_SEG,
TRAIT_PTA_REL_PCT_SEG,
TRAIT_PTA_QTY_SEG 
)
select 
e.BULL_ID,
e.ANIM_KEY, 
e.EVAL_BREED_CODE,
e.EVAL_PDATE,
e.NM_REL_PCT,
e.NM_PCTL,
e.INDEX_AMT_SEG,
e.TRAIT_PTA_REL_PCT_SEG,
e.TRAIT_PTA_QTY_SEG 
from bull_evl_table e   where EVAL_PDATE= 21884  limit 1000;
  


  drop table tmp_animal_lact;
  CREATE TABLE tmp_animal_lact
 (
 ID INT  GENERATED BY DEFAULT AS IDENTITY 
      (START WITH 1 INCREMENT BY 1) NOT NULL,
 COW_ID char(17),
 ANIM_KEY int not null 
);

  insert into tmp_animal_lact(COW_ID,ANIM_KEY)
SELECT    min(a.int_id) as int_id, a.anim_key
FROM   
(
SELECT DISTINCT ANIM_KEY 
FROM LACTA90_TABLE
LIMIT 1000
)lac
inner join id_xref_table a
 on a.anim_key = lac.anim_key 
 and a.sex_code ='F' 
 and a.species_code=0
 group by a.anim_key;
 
 MERGE into COW_EVL_TABLE_DUMMY AS a
 using tmp_animal_lact as b
 on a.id = b.id
 when matched then
 update set 
  cow_id = b.cow_id ,
  anim_key = b.anim_key;
  