 ---https://redmine.uscdcb.com/projects/cdcb-customer-service/wiki/Format_105
CREATE TABLE C19_eliteflat
(
LINE VARCHAR(520)
);

/*
db2 connect to cdcbdb;
db2 load from /home/shared/Data/C19.eliteflat of del insert into C19_eliteflat
*/
 
CREATE TABLE TMP_COW_EVL_TABLE AS
(

select 
cast (0 as int) as ANIM_KEY,
cast (0 as SMALLINT) as EVAL_PDATE,

substring(LINE,1,17) as INT_ID,
substring(LINE,18,17) as SIRE_ID,
substring(LINE,35,17) as DAM_ID,
substring(LINE,52,17) as ALIAS_ID,
substring(LINE,69,8) as BIRTH_DATE,
substring(LINE,77,1) as ELITE_STATUS_CODE,
substring(LINE,78,2) as REGIS_STATUS_CODE,
substring(LINE,80,2) as LAST_DRPC_CODE,
substring(LINE,82,5) as GM_AMT,
substring(LINE,87,2) as LH_STATE_CODE,
substring(LINE,89,2) as LH_COUNTRY_CODE,
substring(LINE,91,4) as LH_HERD_NUMBER,
substring(LINE,95,8) as LH_CALV_DATE,
substring(LINE,103,3) as LH_DIM,
substring(LINE,106,1) as LH_TERM_CODE,
substring(LINE,107,1) as CHANGE_IN_COW_INFO,
substring(LINE,108,1) as CHANGE_IN_COW_ANCESTOR_INFO,
substring(LINE,109,1) as FOREIGN_CNTRB_CODE,
substring(LINE,110,1) as EVAL_CODE,
substring(LINE,111,1) as OWNER_SAMP_DATA_CODE,
substring(LINE,112,1) as LEN_OF_REC_CODE,
substring(LINE,113,1) as REC_IN_PROGRESS_CODE,
substring(LINE,114,2) as INBRD_PCT,
substring(LINE,116,3) as SUM_LACT_WGT_QTY,
substring(LINE,119,2) as NM_PCTL,
substring(LINE,121,2) as YLD_REL_PCT,
substring(LINE,123,5) as PTA_MLK_QTY,
substring(LINE,128,2) as PTA_MF_REL_PCT,
substring(LINE,130,4) as PTA_FAT_QTY,
substring(LINE,134,3) as PTA_FAT_PCT,
substring(LINE,137,2) as PTA_PRO_REL_PCT,
substring(LINE,139,4) as PTA_PRO_QTY,
substring(LINE,143,3) as PTA_PRO_PCT,
substring(LINE,146,3) as PTA_DPR_QTY,
substring(LINE,149,1) as AVAILABLE_FUTURE_USE,
substring(LINE,150,2) as PTA_PL_REL_PCT,
substring(LINE,152,3) as PTA_PL_QTY,
substring(LINE,155,2) as PTA_SCS_REL_PCT,
substring(LINE,157,3) as PTA_SCS_QTY,
substring(LINE,160,2) as NM_REL_PCT,
substring(LINE,162,5) as NM_AMT,
substring(LINE,167,2) as FH_STATE_CODE,
substring(LINE,169,2) as FH_COUNTRY_CODE,
substring(LINE,171,4) as FH_HERD_NUMBER,
substring(LINE,175,5) as FM_AMT,
substring(LINE,180,4) as MF_DAU_QTY,
substring(LINE,184,4) as PRO_DAU_QTY,
substring(LINE,188,1) as MF_HERDS_QTY,
substring(LINE,189,1) as PRO_HERDS_QTY,
substring(LINE,190,1) as GENOMICS_IND,
substring(LINE,191,2) as PARENT_CONTRIBUTE,
substring(LINE,193,2) as PRO_OVERAL_CONTRIBUTE,
substring(LINE,195,3) as PL_AGE_WGT,
substring(LINE,198,1) as LACT_QTY,
substring(LINE,199,1) as PRO_LACT_QTY,
substring(LINE,200,3) as FUTURE_DAU_INBRD_PCT,
substring(LINE,203,3) as MF_AVG_LACT_QTY,
substring(LINE,206,3) as PRO_AVG_LACT_QTY,
substring(LINE,209,5) as CM_AMT,
substring(LINE,214,5) as STD_MLK_QTY,
substring(LINE,219,4) as STD_FAT_QTY,
substring(LINE,223,5) as STD_MP_QTY,
substring(LINE,228,4) as STD_PRO_QTY,
substring(LINE,232,3) as COW_TOTAL_IN_MLK,
substring(LINE,235,3) as STD_SCS_QTY,
substring(LINE,238,4) as STD_DPR_QTY,
substring(LINE,242,2) as PTA_DPR_REL_PCT,
substring(LINE,244,6) as DEV_MLK_QTY,
substring(LINE,250,5) as DEV_FAT_QTY,
substring(LINE,255,6) as DEV_MP_QTY,
substring(LINE,261,5) as DEV_PRO_QTY,
substring(LINE,266,6) as PPA_MLK_QTY,
substring(LINE,272,4) as PPA_FAT_QTY,
substring(LINE,276,4) as PPA_PRO_QTY,
substring(LINE,280,2) as PA_YIELD_REL_PCT,
substring(LINE,282,5) as PA_MLK_QTY,
substring(LINE,287,2) as PA_MF_REL_PCT,
substring(LINE,289,4) as PA_FAT_QTY,
substring(LINE,293,2) as PA_PRO_REL_PCT,
substring(LINE,295,4) as PA_PRO_QTY,
substring(LINE,299,25) as BLANK_FOR_FUTURE,
substring(LINE,324,5) as SC_MLK,
substring(LINE,329,4) as SC_FAT,
substring(LINE,333,4) as SC_PRO,
substring(LINE,337,3) as PA_PL_QTY,
substring(LINE,340,2) as PA_PL_REL_PCT,
substring(LINE,342,3) as PA_SCS_QTY,
substring(LINE,345,2) as PA_SCS_REL_PCT,
substring(LINE,347,3) as PA_DPR_QTY,
substring(LINE,350,2) as PA_DPR_REL_PCT,
substring(LINE,352,5) as PA_NM_AMT,
substring(LINE,357,2) as PA_NM_REL_PCT,
substring(LINE,359,3) as PED_COMP_PCT,
substring(LINE,362,2) as DOMINANT_BREED_CODE,
substring(LINE,364,2) as DOMINANT_BREED_PCT,
substring(LINE,366,3) as HETEROSIS_PCT,
substring(LINE,369,2) as EVAL_BREED_CODE,
substring(LINE,371,3) as INBRD_PCT_1_DECIMAL,
substring(LINE,374,4) as PTA_HCR_QTY,
substring(LINE,378,2) as PTA_HCR_REL_PCT,
substring(LINE,380,4) as PA_HCR_QTY,
substring(LINE,384,2) as PA_HCR_REL_PCT,
substring(LINE,386,4) as PTA_CCR_QTY,
substring(LINE,390,2) as PTA_CCR_REL_PCT,
substring(LINE,392,4) as PA_CCR_QTY,
substring(LINE,396,2) as PA_CCR_REL_PCT,
substring(LINE,398,2) as TYPE_OF_CHIP,
substring(LINE,400,4) as GENOMICS_INBRD_PCT,
substring(LINE,404,4) as FUTURE_GENOMICS_INBRD_PCT,
substring(LINE,408,6) as LAST_ANIM_CONTROL_NUMBER,
substring(LINE,414,4) as PTA_LIV_QTY,
substring(LINE,418,2) as PTA_LIV_REL_PCT,
substring(LINE,420,4) as PA_LIV_QTY,
substring(LINE,424,2) as PA_LIV_REL_PCT,
substring(LINE,426,3) as PTA_GL_QTY,
substring(LINE,429,2) as PTA_GL_REL_PCT,
substring(LINE,431,3) as PA_GL_QTY,
substring(LINE,434,2) as PA_GL_REL_PCT,
substring(LINE,436,4) as PTA_MFV_QTY,
substring(LINE,440,2) as PTA_MFV_REL_PCT,
substring(LINE,442,4) as PA_MFV_QTY,
substring(LINE,446,2) as PA_MFV_REL_PCT,
substring(LINE,448,4) as PTA_DAB_QTY,
substring(LINE,452,2) as PTA_DAB_REL_PCT,
substring(LINE,454,4) as PA_DAB_QTY,
substring(LINE,458,2) as PA_DAB_REL_PCT,
substring(LINE,460,4) as PTA_KET_QTY,
substring(LINE,464,2) as PTA_KET_REL_PCT,
substring(LINE,466,4) as PA_KET_QTY,
substring(LINE,470,2) as PA_KET_REL_PCT,
substring(LINE,472,4) as PTA_MAS_QTY,
substring(LINE,476,2) as PTA_MAS_REL_PCT,
substring(LINE,478,4) as PA_MAS_QTY,
substring(LINE,482,2) as PA_MAS_REL_PCT,
substring(LINE,484,4) as PTA_MET_QTY,
substring(LINE,488,2) as PTA_MET_REL_PCT,
substring(LINE,490,4) as PA_MET_QTY,
substring(LINE,494,2) as PA_MET_REL_PCT,
substring(LINE,496,4) as PTA_RPL_QTY,
substring(LINE,500,2) as PTA_RPL_REL_PCT,
substring(LINE,502,4) as PA_RPL_QTY,
substring(LINE,506,2) as PA_RPL_REL_PCT,
substring(LINE,508,4) as PTA_EFC_QTY,
substring(LINE,512,2) as PTA_EFC_REL_PCT,
substring(LINE,514,4) as PA_EFC_QTY,
substring(LINE,518,2) as PA_EFC_REL_PCT 
from C19_eliteflat 
)DEFINITION ONLY;

ALTER TABLE TMP_COW_EVL_TABLE ADD constraint TMP_COW_EVL_TABLE_PK primary key (ANIM_KEY,EVAL_PDATE);


insert into TMP_COW_EVL_TABLE
select 
id.ANIM_KEY,
21884 as  EVAL_PDATE,

substring(LINE,1,17) as INT_ID,
substring(LINE,18,17) as SIRE_ID,
substring(LINE,35,17) as DAM_ID,
substring(LINE,52,17) as ALIAS_ID,
substring(LINE,69,8) as BIRTH_DATE,
substring(LINE,77,1) as ELITE_STATUS_CODE,
substring(LINE,78,2) as REGIS_STATUS_CODE,
substring(LINE,80,2) as LAST_DRPC_CODE,
substring(LINE,82,5) as GM_AMT,
substring(LINE,87,2) as LH_STATE_CODE,
substring(LINE,89,2) as LH_COUNTRY_CODE,
substring(LINE,91,4) as LH_HERD_NUMBER,
substring(LINE,95,8) as LH_CALV_DATE,
substring(LINE,103,3) as LH_DIM,
substring(LINE,106,1) as LH_TERM_CODE,
substring(LINE,107,1) as CHANGE_IN_COW_INFO,
substring(LINE,108,1) as CHANGE_IN_COW_ANCESTOR_INFO,
substring(LINE,109,1) as FOREIGN_CNTRB_CODE,
substring(LINE,110,1) as EVAL_CODE,
substring(LINE,111,1) as OWNER_SAMP_DATA_CODE,
substring(LINE,112,1) as LEN_OF_REC_CODE,
substring(LINE,113,1) as REC_IN_PROGRESS_CODE,
substring(LINE,114,2) as INBRD_PCT,
substring(LINE,116,3) as SUM_LACT_WGT_QTY,
substring(LINE,119,2) as NM_PCTL,
substring(LINE,121,2) as YLD_REL_PCT,
substring(LINE,123,5) as PTA_MLK_QTY,
substring(LINE,128,2) as PTA_MF_REL_PCT,
substring(LINE,130,4) as PTA_FAT_QTY,
substring(LINE,134,3) as PTA_FAT_PCT,
substring(LINE,137,2) as PTA_PRO_REL_PCT,
substring(LINE,139,4) as PTA_PRO_QTY,
substring(LINE,143,3) as PTA_PRO_PCT,
substring(LINE,146,3) as PTA_DPR_QTY,
substring(LINE,149,1) as AVAILABLE_FUTURE_USE,
substring(LINE,150,2) as PTA_PL_REL_PCT,
substring(LINE,152,3) as PTA_PL_QTY,
substring(LINE,155,2) as PTA_SCS_REL_PCT,
substring(LINE,157,3) as PTA_SCS_QTY,
substring(LINE,160,2) as NM_REL_PCT,
substring(LINE,162,5) as NM_AMT,
substring(LINE,167,2) as FH_STATE_CODE,
substring(LINE,169,2) as FH_COUNTRY_CODE,
substring(LINE,171,4) as FH_HERD_NUMBER,
substring(LINE,175,5) as FM_AMT,
substring(LINE,180,4) as MF_DAU_QTY,
substring(LINE,184,4) as PRO_DAU_QTY,
substring(LINE,188,1) as MF_HERDS_QTY,
substring(LINE,189,1) as PRO_HERDS_QTY,
substring(LINE,190,1) as GENOMICS_IND,
substring(LINE,191,2) as PARENT_CONTRIBUTE,
substring(LINE,193,2) as PRO_OVERAL_CONTRIBUTE,
substring(LINE,195,3) as PL_AGE_WGT,
substring(LINE,198,1) as LACT_QTY,
substring(LINE,199,1) as PRO_LACT_QTY,
substring(LINE,200,3) as FUTURE_DAU_INBRD_PCT,
substring(LINE,203,3) as MF_AVG_LACT_QTY,
substring(LINE,206,3) as PRO_AVG_LACT_QTY,
substring(LINE,209,5) as CM_AMT,
substring(LINE,214,5) as STD_MLK_QTY,
substring(LINE,219,4) as STD_FAT_QTY,
substring(LINE,223,5) as STD_MP_QTY,
substring(LINE,228,4) as STD_PRO_QTY,
substring(LINE,232,3) as COW_TOTAL_IN_MLK,
substring(LINE,235,3) as STD_SCS_QTY,
substring(LINE,238,4) as STD_DPR_QTY,
substring(LINE,242,2) as PTA_DPR_REL_PCT,
substring(LINE,244,6) as DEV_MLK_QTY,
substring(LINE,250,5) as DEV_FAT_QTY,
substring(LINE,255,6) as DEV_MP_QTY,
substring(LINE,261,5) as DEV_PRO_QTY,
substring(LINE,266,6) as PPA_MLK_QTY,
substring(LINE,272,4) as PPA_FAT_QTY,
substring(LINE,276,4) as PPA_PRO_QTY,
substring(LINE,280,2) as PA_YIELD_REL_PCT,
substring(LINE,282,5) as PA_MLK_QTY,
substring(LINE,287,2) as PA_MF_REL_PCT,
substring(LINE,289,4) as PA_FAT_QTY,
substring(LINE,293,2) as PA_PRO_REL_PCT,
substring(LINE,295,4) as PA_PRO_QTY,
substring(LINE,299,25) as BLANK_FOR_FUTURE,
substring(LINE,324,5) as SC_MLK,
substring(LINE,329,4) as SC_FAT,
substring(LINE,333,4) as SC_PRO,
substring(LINE,337,3) as PA_PL_QTY,
substring(LINE,340,2) as PA_PL_REL_PCT,
substring(LINE,342,3) as PA_SCS_QTY,
substring(LINE,345,2) as PA_SCS_REL_PCT,
substring(LINE,347,3) as PA_DPR_QTY,
substring(LINE,350,2) as PA_DPR_REL_PCT,
substring(LINE,352,5) as PA_NM_AMT,
substring(LINE,357,2) as PA_NM_REL_PCT,
substring(LINE,359,3) as PED_COMP_PCT,
substring(LINE,362,2) as DOMINANT_BREED_CODE,
substring(LINE,364,2) as DOMINANT_BREED_PCT,
substring(LINE,366,3) as HETEROSIS_PCT,
substring(LINE,369,2) as EVAL_BREED_CODE,
substring(LINE,371,3) as INBRD_PCT_1_DECIMAL,
substring(LINE,374,4) as PTA_HCR_QTY,
substring(LINE,378,2) as PTA_HCR_REL_PCT,
substring(LINE,380,4) as PA_HCR_QTY,
substring(LINE,384,2) as PA_HCR_REL_PCT,
substring(LINE,386,4) as PTA_CCR_QTY,
substring(LINE,390,2) as PTA_CCR_REL_PCT,
substring(LINE,392,4) as PA_CCR_QTY,
substring(LINE,396,2) as PA_CCR_REL_PCT,
substring(LINE,398,2) as TYPE_OF_CHIP,
substring(LINE,400,4) as GENOMICS_INBRD_PCT,
substring(LINE,404,4) as FUTURE_GENOMICS_INBRD_PCT,
substring(LINE,408,6) as LAST_ANIM_CONTROL_NUMBER,
substring(LINE,414,4) as PTA_LIV_QTY,
substring(LINE,418,2) as PTA_LIV_REL_PCT,
substring(LINE,420,4) as PA_LIV_QTY,
substring(LINE,424,2) as PA_LIV_REL_PCT,
substring(LINE,426,3) as PTA_GL_QTY,
substring(LINE,429,2) as PTA_GL_REL_PCT,
substring(LINE,431,3) as PA_GL_QTY,
substring(LINE,434,2) as PA_GL_REL_PCT,
substring(LINE,436,4) as PTA_MFV_QTY,
substring(LINE,440,2) as PTA_MFV_REL_PCT,
substring(LINE,442,4) as PA_MFV_QTY,
substring(LINE,446,2) as PA_MFV_REL_PCT,
substring(LINE,448,4) as PTA_DAB_QTY,
substring(LINE,452,2) as PTA_DAB_REL_PCT,
substring(LINE,454,4) as PA_DAB_QTY,
substring(LINE,458,2) as PA_DAB_REL_PCT,
substring(LINE,460,4) as PTA_KET_QTY,
substring(LINE,464,2) as PTA_KET_REL_PCT,
substring(LINE,466,4) as PA_KET_QTY,
substring(LINE,470,2) as PA_KET_REL_PCT,
substring(LINE,472,4) as PTA_MAS_QTY,
substring(LINE,476,2) as PTA_MAS_REL_PCT,
substring(LINE,478,4) as PA_MAS_QTY,
substring(LINE,482,2) as PA_MAS_REL_PCT,
substring(LINE,484,4) as PTA_MET_QTY,
substring(LINE,488,2) as PTA_MET_REL_PCT,
substring(LINE,490,4) as PA_MET_QTY,
substring(LINE,494,2) as PA_MET_REL_PCT,
substring(LINE,496,4) as PTA_RPL_QTY,
substring(LINE,500,2) as PTA_RPL_REL_PCT,
substring(LINE,502,4) as PA_RPL_QTY,
substring(LINE,506,2) as PA_RPL_REL_PCT,
substring(LINE,508,4) as PTA_EFC_QTY,
substring(LINE,512,2) as PTA_EFC_REL_PCT,
substring(LINE,514,4) as PA_EFC_QTY,
substring(LINE,518,2) as PA_EFC_REL_PCT 
 
from C19_eliteflat f
inner join id_xref_table id
 on substring(f.LINE,1,17) = id.int_id 
 and id.sex_code ='F'
  AND id.species_code =0
 and id.PREFERRED_CODE =1;
  
 
CREATE TABLE COW_EVL_TABLE
( 
 ANIM_KEY INTEGER NOT NULL,
 EVAL_PDATE SMALLINT NOT NULL,
 INT_ID  VARCHAR(17),
 SIRE_ID  VARCHAR(17),
 DAM_ID  VARCHAR(17),
 ALIAS_ID  VARCHAR(17),
 BIRTH_DATE  VARCHAR(10),
 ELITE_STATUS_CODE  VARCHAR(10),
 REGIS_STATUS_CODE  VARCHAR(10),
 LAST_DRPC_CODE  VARCHAR(10),
 GM_AMT  VARCHAR(10),
 LH_STATE_CODE  VARCHAR(10),
 LH_COUNTRY_CODE  VARCHAR(10),
 LH_HERD_NUMBER  VARCHAR(10),
 LH_DIM  VARCHAR(10),
 LH_CALV_DATE  VARCHAR(10),
 LH_TERM_CODE  VARCHAR(10),
 CHANGE_IN_COW_INFO  VARCHAR(10),
 CHANGE_IN_COW_ANCESTOR_INFO  VARCHAR(10),
 FOREIGN_CNTRB_CODE  VARCHAR(10),
 EVAL_CODE  VARCHAR(10),
 OWNER_SAMP_DATA_CODE  VARCHAR(10),
 LEN_OF_REC_CODE  VARCHAR(10),
 REC_IN_PROGRESS_CODE  VARCHAR(10),
 INBRD_PCT  VARCHAR(10),
 SUM_LACT_WGT_QTY  VARCHAR(10),
 NM_PCTL  VARCHAR(10),
 YLD_REL_PCT  VARCHAR(10),
 PTA_MLK_QTY  VARCHAR(10),
 PTA_MF_REL_PCT  VARCHAR(10),
 PTA_FAT_QTY  VARCHAR(10),
 PTA_FAT_PCT  VARCHAR(10),
 PTA_PRO_REL_PCT  VARCHAR(10),
 PTA_PRO_QTY  VARCHAR(10),
 PTA_PRO_PCT  VARCHAR(10),
 PTA_DPR_QTY  VARCHAR(10),
 AVAILABLE_FUTURE_USE  VARCHAR(10),
 PTA_PL_REL_PCT  VARCHAR(10),
 PTA_PL_QTY  VARCHAR(10),
 PTA_SCS_REL_PCT  VARCHAR(10),
 PTA_SCS_QTY  VARCHAR(10),
 NM_REL_PCT  VARCHAR(10),
 NM_AMT  VARCHAR(10),
 FH_STATE_CODE  VARCHAR(10),
 FH_COUNTRY_CODE  VARCHAR(10),
 FH_HERD_NUMBER  VARCHAR(10),
 FM_AMT  VARCHAR(10),
 MF_DAU_QTY  VARCHAR(10),
 PRO_DAU_QTY  VARCHAR(10),
 MF_HERDS_QTY  VARCHAR(10),
 PRO_HERDS_QTY  VARCHAR(10),
 GENOMICS_IND  VARCHAR(10),
 PARENT_CONTRIBUTE  VARCHAR(10),
 PRO_OVERAL_CONTRIBUTE  VARCHAR(10),
 PL_AGE_WGT  VARCHAR(10),
 LACT_QTY  VARCHAR(10),
 PRO_LACT_QTY  VARCHAR(10),
 FUTURE_DAU_INBRD_PCT  VARCHAR(10),
 MF_AVG_LACT_QTY  VARCHAR(10),
 PRO_AVG_LACT_QTY  VARCHAR(10),
 CM_AMT  VARCHAR(10),
 STD_MLK_QTY  VARCHAR(10),
 STD_FAT_QTY  VARCHAR(10),
 STD_MP_QTY  VARCHAR(10),
 STD_PRO_QTY  VARCHAR(10),
 COW_TOTAL_IN_MLK  VARCHAR(10),
 STD_SCS_QTY  VARCHAR(10),
 STD_DPR_QTY  VARCHAR(10),
 PTA_DPR_REL_PCT  VARCHAR(10),
 DEV_MLK_QTY  VARCHAR(10),
 DEV_FAT_QTY  VARCHAR(10),
 DEV_MP_QTY  VARCHAR(10),
 DEV_PRO_QTY  VARCHAR(10),
 PPA_MLK_QTY  VARCHAR(10),
 PPA_FAT_QTY  VARCHAR(10),
 PPA_PRO_QTY  VARCHAR(10),
 PA_YIELD_REL_PCT  VARCHAR(10),
 PA_MLK_QTY  VARCHAR(10),
 PA_MF_REL_PCT  VARCHAR(10),
 PA_FAT_QTY  VARCHAR(10),
 PA_PRO_REL_PCT  VARCHAR(10),
 PA_PRO_QTY  VARCHAR(10),
 BLANK_FOR_FUTURE  VARCHAR(10),
 SC_MLK  VARCHAR(10),
 SC_FAT  VARCHAR(10),
 SC_PRO  VARCHAR(10),
 PA_PL_QTY  VARCHAR(10),
 PA_PL_REL_PCT  VARCHAR(10),
 PA_SCS_QTY  VARCHAR(10),
 PA_SCS_REL_PCT  VARCHAR(10),
 PA_DPR_QTY  VARCHAR(10),
 PA_DPR_REL_PCT  VARCHAR(10),
 PA_NM_AMT  VARCHAR(10),
 PA_NM_REL_PCT  VARCHAR(10),
 PED_COMP_PCT  VARCHAR(10),
 DOMINANT_BREED_CODE  VARCHAR(10),
 DOMINANT_BREED_PCT  VARCHAR(10),
 HETEROSIS_PCT  VARCHAR(10),
 EVAL_BREED_CODE  VARCHAR(10),
 INBRD_PCT_1_DECIMAL  VARCHAR(10),
 PTA_HCR_QTY  VARCHAR(10),
 PTA_HCR_REL_PCT  VARCHAR(10),
 PA_HCR_QTY  VARCHAR(10),
 PA_HCR_REL_PCT  VARCHAR(10),
 PTA_CCR_QTY  VARCHAR(10),
 PTA_CCR_REL_PCT  VARCHAR(10),
 PA_CCR_QTY  VARCHAR(10),
 PA_CCR_REL_PCT  VARCHAR(10),
 TYPE_OF_CHIP  VARCHAR(10),
 GENOMICS_INBRD_PCT  VARCHAR(10),
 FUTURE_GENOMICS_INBRD_PCT  VARCHAR(10),
 LAST_ANIM_CONTROL_NUMBER  VARCHAR(10),
 PTA_LIV_QTY  VARCHAR(10),
 PTA_LIV_REL_PCT  VARCHAR(10),
 PA_LIV_QTY  VARCHAR(10),
 PA_LIV_REL_PCT  VARCHAR(10),
 PTA_GL_QTY  VARCHAR(10),
 PTA_GL_REL_PCT  VARCHAR(10),
 PA_GL_QTY  VARCHAR(10),
 PA_GL_REL_PCT  VARCHAR(10),
 PTA_MFV_QTY  VARCHAR(10),
 PTA_MFV_REL_PCT  VARCHAR(10),
 PA_MFV_QTY  VARCHAR(10),
 PA_MFV_REL_PCT  VARCHAR(10),
 PTA_DAB_QTY  VARCHAR(10),
 PTA_DAB_REL_PCT  VARCHAR(10),
 PA_DAB_QTY  VARCHAR(10),
 PA_DAB_REL_PCT  VARCHAR(10),
 PTA_KET_QTY  VARCHAR(10),
 PTA_KET_REL_PCT  VARCHAR(10),
 PA_KET_QTY  VARCHAR(10),
 PA_KET_REL_PCT  VARCHAR(10),
 PTA_MAS_QTY  VARCHAR(10),
 PTA_MAS_REL_PCT  VARCHAR(10),
 PA_MAS_QTY  VARCHAR(10),
 PA_MAS_REL_PCT  VARCHAR(10),
 PTA_MET_QTY  VARCHAR(10),
 PTA_MET_REL_PCT  VARCHAR(10),
 PA_MET_QTY  VARCHAR(10),
 PA_MET_REL_PCT  VARCHAR(10),
 PTA_RPL_QTY  VARCHAR(10),
 PTA_RPL_REL_PCT  VARCHAR(10),
 PA_RPL_QTY  VARCHAR(10),
 PA_RPL_REL_PCT  VARCHAR(10),
 PTA_EFC_QTY  VARCHAR(10),
 PTA_EFC_REL_PCT  VARCHAR(10),
 PA_EFC_QTY  VARCHAR(10),
 PA_EFC_REL_PCT  VARCHAR(10),
 CONSTRAINT COW_EVL_TABLE_PK PRIMARY KEY (ANIM_KEY, EVAL_PDATE) 
);
create index COW_EVL_TABLE_INDEX2          on COW_EVL_TABLE           (EVAL_PDATE desc, EVAL_BREED_CODE asc, ANIM_KEY desc) allow reverse scans;
--delete from COW_EVL_TABLE immediate;

INSERT INTO COW_EVL_TABLE
(
  ANIM_KEY
 ,EVAL_PDATE
 ,INT_ID
 ,SIRE_ID
 ,DAM_ID
 ,ALIAS_ID
 ,BIRTH_DATE
 ,ELITE_STATUS_CODE
 ,REGIS_STATUS_CODE
 ,LAST_DRPC_CODE
 ,GM_AMT
 ,LH_STATE_CODE
 ,LH_COUNTRY_CODE
 ,LH_HERD_NUMBER
 ,LH_DIM
 ,LH_CALV_DATE
 ,LH_TERM_CODE
 ,CHANGE_IN_COW_INFO
 ,CHANGE_IN_COW_ANCESTOR_INFO
 ,FOREIGN_CNTRB_CODE
 ,EVAL_CODE
 ,OWNER_SAMP_DATA_CODE
 ,LEN_OF_REC_CODE
 ,REC_IN_PROGRESS_CODE
 ,INBRD_PCT
 ,SUM_LACT_WGT_QTY
 ,NM_PCTL
 ,YLD_REL_PCT
 ,PTA_MF_REL_PCT
 ,PTA_PRO_REL_PCT
 ,AVAILABLE_FUTURE_USE
 ,PTA_PL_REL_PCT
 ,PTA_SCS_REL_PCT
 ,NM_REL_PCT
 ,NM_AMT
 ,FH_STATE_CODE
 ,FH_COUNTRY_CODE
 ,FH_HERD_NUMBER
 ,FM_AMT
 ,MF_DAU_QTY
 ,PRO_DAU_QTY
 ,MF_HERDS_QTY
 ,PRO_HERDS_QTY
 ,GENOMICS_IND
 ,PARENT_CONTRIBUTE
 ,PRO_OVERAL_CONTRIBUTE
 ,PL_AGE_WGT
 ,LACT_QTY
 ,PRO_LACT_QTY
 ,FUTURE_DAU_INBRD_PCT
 ,MF_AVG_LACT_QTY
 ,PRO_AVG_LACT_QTY
 ,CM_AMT
 ,STD_MLK_QTY
 ,STD_FAT_QTY
 ,STD_MP_QTY
 ,STD_PRO_QTY
 ,COW_TOTAL_IN_MLK
 ,STD_SCS_QTY
 ,STD_DPR_QTY
 ,PTA_DPR_REL_PCT
 ,DEV_MLK_QTY
 ,DEV_FAT_QTY
 ,DEV_MP_QTY
 ,DEV_PRO_QTY
 ,PPA_MLK_QTY
 ,PPA_FAT_QTY
 ,PPA_PRO_QTY
 ,PA_YIELD_REL_PCT
 ,PA_MF_REL_PCT
 ,PA_PRO_REL_PCT
 ,BLANK_FOR_FUTURE
 ,SC_MLK
 ,SC_FAT
 ,SC_PRO
 ,PA_PL_REL_PCT
 ,PA_SCS_REL_PCT
 ,PA_DPR_REL_PCT
 ,PA_NM_AMT
 ,PA_NM_REL_PCT
 ,PED_COMP_PCT
 ,DOMINANT_BREED_CODE
 ,DOMINANT_BREED_PCT
 ,HETEROSIS_PCT
 ,EVAL_BREED_CODE
 ,INBRD_PCT_1_DECIMAL
 ,PTA_HCR_REL_PCT
 ,PA_HCR_REL_PCT
 ,PTA_CCR_REL_PCT
 ,PA_CCR_REL_PCT
 ,TYPE_OF_CHIP
 ,GENOMICS_INBRD_PCT
 ,FUTURE_GENOMICS_INBRD_PCT
 ,LAST_ANIM_CONTROL_NUMBER
 ,PTA_LIV_REL_PCT
 ,PA_LIV_REL_PCT
 ,PTA_GL_REL_PCT
 ,PA_GL_REL_PCT
 ,PTA_MFV_REL_PCT
 ,PA_MFV_REL_PCT
 ,PTA_DAB_REL_PCT
 ,PA_DAB_REL_PCT
 ,PTA_KET_REL_PCT
 ,PA_KET_REL_PCT
 ,PTA_MAS_REL_PCT
 ,PA_MAS_REL_PCT
 ,PTA_MET_REL_PCT
 ,PA_MET_REL_PCT
 ,PTA_RPL_REL_PCT
 ,PA_RPL_REL_PCT
 ,PTA_EFC_REL_PCT
 ,PA_EFC_REL_PCT
 ,PTA_MLK_QTY
 ,PTA_FAT_QTY
 ,PTA_PRO_QTY
 ,PTA_PL_QTY
 ,PTA_SCS_QTY
 ,PTA_DPR_QTY
 ,PTA_HCR_QTY
 ,PTA_CCR_QTY
 ,PTA_LIV_QTY
 ,PTA_GL_QTY
 ,PTA_MFV_QTY
 ,PTA_DAB_QTY
 ,PTA_KET_QTY
 ,PTA_MAS_QTY
 ,PTA_MET_QTY
 ,PTA_RPL_QTY
 ,PTA_EFC_QTY
 ,PTA_FAT_PCT
 ,PTA_PRO_PCT    
 ,PA_MLK_QTY
 ,PA_FAT_QTY
 ,PA_PRO_QTY
 ,PA_PL_QTY
 ,PA_SCS_QTY
 ,PA_DPR_QTY
 ,PA_HCR_QTY
 ,PA_CCR_QTY
 ,PA_LIV_QTY
 ,PA_GL_QTY
 ,PA_MFV_QTY
 ,PA_DAB_QTY
 ,PA_KET_QTY
 ,PA_MAS_QTY
 ,PA_MET_QTY
 ,PA_RPL_QTY
 ,PA_EFC_QTY 

)

SELECT    
ANIM_KEY
 ,21884 AS EVAL_PDATE
 ,INT_ID
 ,SIRE_ID
 ,DAM_ID
 ,ALIAS_ID
 ,CASE WHEN BIRTH_DATE ='00000000' THEN NULL   ELSE BIRTH_DATE  END AS BIRTH_DATE
 ,ELITE_STATUS_CODE
 ,REGIS_STATUS_CODE
 ,LAST_DRPC_CODE
 ,CAST(CAST(GM_AMT AS  INT) AS VARCHAR(10)) AS GM_AMT
 ,LH_STATE_CODE
 ,LH_COUNTRY_CODE
 ,CASE WHEN LH_HERD_NUMBER = '0000' THEN NULL ELSE CAST(CAST(LH_HERD_NUMBER AS INT) AS VARCHAR(10))  END AS LH_HERD_NUMBER
 ,CASE WHEN LH_DIM ='000' THEN NULL ELSE CAST(CAST(LH_DIM AS INT) AS VARCHAR(10)) END AS LH_DIM 
 ,CASE WHEN LH_CALV_DATE ='00000000' THEN NULL ELSE LH_CALV_DATE  END AS LH_CALV_DATE  
 ,LH_TERM_CODE
 ,CHANGE_IN_COW_INFO
 ,CHANGE_IN_COW_ANCESTOR_INFO
 ,FOREIGN_CNTRB_CODE
 ,EVAL_CODE
 ,OWNER_SAMP_DATA_CODE
 ,LEN_OF_REC_CODE
 ,REC_IN_PROGRESS_CODE
 ,INBRD_PCT
 ,CAST(CAST(SUM_LACT_WGT_QTY AS INT) AS VARCHAR(10))SUM_LACT_WGT_QTY
 ,NM_PCTL
 ,YLD_REL_PCT
 ,PTA_MF_REL_PCT 
 ,PTA_PRO_REL_PCT
 ,AVAILABLE_FUTURE_USE
 ,PTA_PL_REL_PCT
 ,PTA_SCS_REL_PCT
 ,NM_REL_PCT
 ,CAST(CAST(NM_AMT AS  INT) AS VARCHAR(10)) AS NM_AMT
 ,FH_STATE_CODE
 ,FH_COUNTRY_CODE  
 ,FH_HERD_NUMBER  
 ,CAST(CAST(FM_AMT AS  INT) AS VARCHAR(10)) AS FM_AMT
  ,CAST(CAST(MF_DAU_QTY AS  INT) AS VARCHAR(10)) AS MF_DAU_QTY  
  ,CAST(CAST(PRO_DAU_QTY AS  INT) AS VARCHAR(10)) AS PRO_DAU_QTY 
 ,MF_HERDS_QTY
 ,PRO_HERDS_QTY
 ,GENOMICS_IND
 ,CAST(CAST(PARENT_CONTRIBUTE AS  INT) AS VARCHAR(10)) AS PARENT_CONTRIBUTE
 ,CAST(CAST(PRO_OVERAL_CONTRIBUTE AS  INT) AS VARCHAR(10)) AS PRO_OVERAL_CONTRIBUTE
 ,PL_AGE_WGT
 ,LACT_QTY
 ,PRO_LACT_QTY
 ,CAST(CAST(FUTURE_DAU_INBRD_PCT AS  INT) AS VARCHAR(10)) AS FUTURE_DAU_INBRD_PCT
 ,CAST(CAST(MF_AVG_LACT_QTY AS  INT) AS VARCHAR(10)) AS MF_AVG_LACT_QTY
  ,CAST(CAST(PRO_AVG_LACT_QTY AS  INT) AS VARCHAR(10)) AS PRO_AVG_LACT_QTY
 ,CAST(CAST(CM_AMT AS  INT) AS VARCHAR(10)) AS CM_AMT
 ,CAST(CAST(STD_MLK_QTY AS  INT) AS VARCHAR(10)) AS STD_MLK_QTY
 ,CAST(CAST(STD_FAT_QTY AS  INT) AS VARCHAR(10)) AS STD_FAT_QTY
 ,CAST(CAST(STD_MP_QTY AS  INT) AS VARCHAR(10)) AS STD_MP_QTY
 ,CAST(CAST(STD_PRO_QTY AS  INT) AS VARCHAR(10)) AS STD_PRO_QTY
 ,COW_TOTAL_IN_MLK
 ,STD_SCS_QTY
 ,STD_DPR_QTY
 ,PTA_DPR_REL_PCT
 ,DEV_MLK_QTY
 ,DEV_FAT_QTY
 ,DEV_MP_QTY
 ,DEV_PRO_QTY
 ,PPA_MLK_QTY
 ,PPA_FAT_QTY
 ,PPA_PRO_QTY
 ,PA_YIELD_REL_PCT
 ,PA_MF_REL_PCT
 ,PA_PRO_REL_PCT
 ,BLANK_FOR_FUTURE
 ,SC_MLK
 ,SC_FAT
 ,SC_PRO
 ,PA_PL_REL_PCT
 ,PA_SCS_REL_PCT
 ,PA_DPR_REL_PCT
 ,PA_NM_AMT 
 ,PA_NM_REL_PCT
 ,PED_COMP_PCT
 ,DOMINANT_BREED_CODE
 ,DOMINANT_BREED_PCT
 ,HETEROSIS_PCT
 ,EVAL_BREED_CODE
 ,INBRD_PCT_1_DECIMAL
 ,PTA_HCR_REL_PCT
 ,PA_HCR_REL_PCT
 ,PTA_CCR_REL_PCT
 ,PA_CCR_REL_PCT
 ,TYPE_OF_CHIP
 ,GENOMICS_INBRD_PCT
 ,FUTURE_GENOMICS_INBRD_PCT
 ,LAST_ANIM_CONTROL_NUMBER
 ,PTA_LIV_REL_PCT
 ,PA_LIV_REL_PCT
 ,PTA_GL_REL_PCT
 ,PA_GL_REL_PCT
 ,PTA_MFV_REL_PCT
 ,PA_MFV_REL_PCT
 ,PTA_DAB_REL_PCT
 ,PA_DAB_REL_PCT
 ,PTA_KET_REL_PCT
 ,PA_KET_REL_PCT
 ,PTA_MAS_REL_PCT
 ,PA_MAS_REL_PCT
 ,PTA_MET_REL_PCT
 ,PA_MET_REL_PCT
 ,PTA_RPL_REL_PCT
 ,PA_RPL_REL_PCT
 ,PTA_EFC_REL_PCT
 ,PA_EFC_REL_PCT 
 , FLOAT2CHAR(PTA_MLK_QTY*1,1) AS PTA_MLK_QTY
 ,FLOAT2CHAR(PTA_FAT_QTY*1,1) AS PTA_FAT_QTY
 ,FLOAT2CHAR(PTA_PRO_QTY*1,1) AS PTA_PRO_QTY
 ,FLOAT2CHAR(PTA_PL_QTY*0.1,0.1) AS PTA_PL_QTY
 ,FLOAT2CHAR(PTA_SCS_QTY*0.01,0.01) AS PTA_SCS_QTY
 ,FLOAT2CHAR(PTA_DPR_QTY*0.1,0.1) AS PTA_DPR_QTY
 ,FLOAT2CHAR(PTA_HCR_QTY*0.1,0.1) AS PTA_HCR_QTY
 ,FLOAT2CHAR(PTA_CCR_QTY*0.1,0.1) AS PTA_CCR_QTY
 ,FLOAT2CHAR(PTA_LIV_QTY*0.1,0.1) AS PTA_LIV_QTY
 ,FLOAT2CHAR(PTA_GL_QTY*0.1,0.1) AS PTA_GL_QTY
 ,FLOAT2CHAR(PTA_MFV_QTY*0.1,0.1) AS PTA_MFV_QTY
 ,FLOAT2CHAR(PTA_DAB_QTY*0.1,0.1) AS PTA_DAB_QTY
 ,FLOAT2CHAR(PTA_KET_QTY*0.1,0.1) AS PTA_KET_QTY
 ,FLOAT2CHAR(PTA_MAS_QTY*0.1,0.1) AS PTA_MAS_QTY
 ,FLOAT2CHAR(PTA_MET_QTY*0.1,0.1) AS PTA_MET_QTY
 ,FLOAT2CHAR(PTA_RPL_QTY*0.1,0.1) AS PTA_RPL_QTY
 ,FLOAT2CHAR(PTA_EFC_QTY*0.1,0.1) AS PTA_EFC_QTY
 ,FLOAT2CHAR(PTA_FAT_PCT*0.01,0.01) AS PTA_FAT_PCT
 ,FLOAT2CHAR(PTA_PRO_PCT*0.01,0.01) AS PTA_PRO_PCT 
  ,FLOAT2CHAR(PA_MLK_QTY*1,1) AS PA_MLK_QTY
 ,FLOAT2CHAR(PA_FAT_QTY*1,1) AS PA_FAT_QTY
 ,FLOAT2CHAR(PA_PRO_QTY*1,1) AS PA_PRO_QTY
 ,FLOAT2CHAR(PA_PL_QTY*0.1,0.1) AS PA_PL_QTY
 ,FLOAT2CHAR(PA_SCS_QTY*0.01,0.01) AS PA_SCS_QTY
 ,FLOAT2CHAR(PA_DPR_QTY*0.1,0.1) AS PA_DPR_QTY
 ,FLOAT2CHAR(PA_HCR_QTY*0.1,0.1) AS PA_HCR_QTY
 ,FLOAT2CHAR(PA_CCR_QTY*0.1,0.1) AS PA_CCR_QTY
 ,FLOAT2CHAR(PA_LIV_QTY*0.1,0.1) AS PA_LIV_QTY
 ,FLOAT2CHAR(PA_GL_QTY*0.1,0.1) AS PA_GL_QTY
 ,FLOAT2CHAR(PA_MFV_QTY*0.1,0.1) AS PA_MFV_QTY
 ,FLOAT2CHAR(PA_DAB_QTY*0.1,0.1) AS PA_DAB_QTY
 ,FLOAT2CHAR(PA_KET_QTY*0.1,0.1) AS PA_KET_QTY
 ,FLOAT2CHAR(PA_MAS_QTY*0.1,0.1) AS PA_MET_QTY
 ,FLOAT2CHAR(PA_MET_QTY*0.1,0.1) AS PA_MET_QTY
 ,FLOAT2CHAR(PA_RPL_QTY*0.1,0.1) AS PA_RPL_QTY 
 ,FLOAT2CHAR(PA_EFC_QTY*0.1,0.1) AS PA_EFC_QTY
 

 FROM TMP_COW_EVL_TABLE;

UPDATE COW_EVL_TABLE SET LH_HERD_NUMBER = NULL WHERE LH_HERD_NUMBER = '0000';
UPDATE COW_EVL_TABLE SET LH_DIM = NULL WHERE LH_DIM = '0';
UPDATE COW_EVL_TABLE SET LH_HERD_NUMBER = CAST(CAST(LH_HERD_NUMBER AS INT) AS VARCHAR(10))