

	DECLARE GLOBAL TEMPORARY TABLE SESSION.TMP_FIELD
	(
		feature_name varchar(300), 
		component_name varchar(300), 
		field_name varchar(300) 
	
	) WITH REPLACE ON COMMIT PRESERVE ROWS;

INSERT INTO SESSION.TMP_FIELD 
(
	feature_name,
	component_name,
	field_name
)
VALUES ('Queries >> Cattle - Errors','Animal Box','DOB'),
('Queries >> Cattle - Errors','Animal Box','Multi-Birth Code'),
('Queries >> Cattle - Errors','Animal Box','Name'),
('Queries >> Cattle - Errors','Animal Box','Preferred ID'),
('Queries >> Cattle - Errors','Animal Box','Sex'),
('Queries >> Cattle - Errors','Animal Box','Source Code'),
('Queries >> Cattle - Errors','Error 1 Information','Cross references'),
('Queries >> Cattle - Errors','Error 1 Information','Date Processed'),
('Queries >> Cattle - Errors','Error 1 Information','Description'),
('Queries >> Cattle - Errors','Error 1 Information','Disposition Code'),
('Queries >> Cattle - Errors','Error 1 Information','DOB'),
('Queries >> Cattle - Errors','Error 1 Information','DRPC'),
('Queries >> Cattle - Errors','Error 1 Information','Error Code'),
('Queries >> Cattle - Errors','Error 1 Information','File Name'),
('Queries >> Cattle - Errors','Error 1 Information','Herd'),
('Queries >> Cattle - Errors','Error 1 Information','ID'),
('Queries >> Cattle - Errors','Error 1 Information','ID Change Code'),
('Queries >> Cattle - Errors','Error 1 Information','Multi-Birth Code'),
('Queries >> Cattle - Errors','Error 1 Information','Parental Change Code'),
('Queries >> Cattle - Errors','Error 1 Information','Processing Date'),
('Queries >> Cattle - Errors','Error 1 Information','Record Type'),
('Queries >> Cattle - Errors','Error 1 Information','Sire'),
('Queries >> Cattle - Errors','Error 1 Information','Source Code'),
('Queries >> Cattle - Errors','Error 1 Information','Source Code'),
('Queries >> Cattle - Errors','Error 1 Information','Verification code'),
('Queries >> Cattle - Errors','Error 4 Information','Affilication'),
('Queries >> Cattle - Errors','Error 4 Information','Breeding Date'),
('Queries >> Cattle - Errors','Error 4 Information','Calving Date'),
('Queries >> Cattle - Errors','Error 4 Information','Control Number'),
('Queries >> Cattle - Errors','Error 4 Information','Cross references'),
('Queries >> Cattle - Errors','Error 4 Information','Date Processed'),
('Queries >> Cattle - Errors','Error 4 Information','Days3x'),
('Queries >> Cattle - Errors','Error 4 Information','Description'),
('Queries >> Cattle - Errors','Error 4 Information','Disposition Code'),
('Queries >> Cattle - Errors','Error 4 Information','DIM'),
('Queries >> Cattle - Errors','Error 4 Information','DOB'),
('Queries >> Cattle - Errors','Error 4 Information','Dry'),
('Queries >> Cattle - Errors','Error 4 Information','DRPC'),
('Queries >> Cattle - Errors','Error 4 Information','Error Code'),
('Queries >> Cattle - Errors','Error 4 Information','Fat'),
('Queries >> Cattle - Errors','Error 4 Information','File Name'),
('Queries >> Cattle - Errors','Error 4 Information','Herd'),
('Queries >> Cattle - Errors','Error 4 Information','Herd'),
('Queries >> Cattle - Errors','Error 4 Information','ID'),
('Queries >> Cattle - Errors','Error 4 Information','ID Change Code'),
('Queries >> Cattle - Errors','Error 4 Information','Initiation Code'),
('Queries >> Cattle - Errors','Error 4 Information','Lact'),
('Queries >> Cattle - Errors','Error 4 Information','Lact Type'),
('Queries >> Cattle - Errors','Error 4 Information','Lact Ver'),
('Queries >> Cattle - Errors','Error 4 Information','Milk'),
('Queries >> Cattle - Errors','Error 4 Information','Multi-Birth Code'),
('Queries >> Cattle - Errors','Error 4 Information','Parental Change Code'),
('Queries >> Cattle - Errors','Error 4 Information','Processing Date'),
('Queries >> Cattle - Errors','Error 4 Information','Progeny'),
('Queries >> Cattle - Errors','Error 4 Information','Protein'),
('Queries >> Cattle - Errors','Error 4 Information','Record Type'),
('Queries >> Cattle - Errors','Error 4 Information','SCS'),
('Queries >> Cattle - Errors','Error 4 Information','Sire'),
('Queries >> Cattle - Errors','Error 4 Information','Source Code'),
('Queries >> Cattle - Errors','Error 4 Information','Source Code'),
('Queries >> Cattle - Errors','Error 4 Information','Termination Code'),
('Queries >> Cattle - Errors','Error 4 Information','Test Day Data'),
('Queries >> Cattle - Errors','Error 4 Information','TOT'),
('Queries >> Cattle - Errors','Error 4 Information','Verification code'),
('Queries >> Cattle - Errors','Error 5 Information','Affilication'),
('Queries >> Cattle - Errors','Error 5 Information','Calving Date'),
('Queries >> Cattle - Errors','Error 5 Information','Control Number'),
('Queries >> Cattle - Errors','Error 5 Information','Cross references'),
('Queries >> Cattle - Errors','Error 5 Information','Date Processed'),
('Queries >> Cattle - Errors','Error 5 Information','Description'),
('Queries >> Cattle - Errors','Error 5 Information','Disposition Code'),
('Queries >> Cattle - Errors','Error 5 Information','DOB'),
('Queries >> Cattle - Errors','Error 5 Information','DRPC'),
('Queries >> Cattle - Errors','Error 5 Information','Error Code'),
('Queries >> Cattle - Errors','Error 5 Information','File Name'),
('Queries >> Cattle - Errors','Error 5 Information','Herd'),
('Queries >> Cattle - Errors','Error 5 Information','Herd'),
('Queries >> Cattle - Errors','Error 5 Information','ID'),
('Queries >> Cattle - Errors','Error 5 Information','ID Change Code'),
('Queries >> Cattle - Errors','Error 5 Information','Lact Type'),
('Queries >> Cattle - Errors','Error 5 Information','Lact Ver'),
('Queries >> Cattle - Errors','Error 5 Information','Multi-Birth Code'),
('Queries >> Cattle - Errors','Error 5 Information','Parental Change Code'),
('Queries >> Cattle - Errors','Error 5 Information','Processing Date'),
('Queries >> Cattle - Errors','Error 5 Information','Record Type'),
('Queries >> Cattle - Errors','Error 5 Information','Reproductive Event'),
('Queries >> Cattle - Errors','Error 5 Information','Sire'),
('Queries >> Cattle - Errors','Error 5 Information','Source Code'),
('Queries >> Cattle - Errors','Error 5 Information','Source Code'),
('Queries >> Cattle - Errors','Error 5 Information','Verification code'),
('Queries >> Cattle - Errors','Error 6 Information','Affilication'),
('Queries >> Cattle - Errors','Error 6 Information','Calving Date'),
('Queries >> Cattle - Errors','Error 6 Information','Control Number'),
('Queries >> Cattle - Errors','Error 6 Information','Cross references'),
('Queries >> Cattle - Errors','Error 6 Information','Date Processed'),
('Queries >> Cattle - Errors','Error 6 Information','Description'),
('Queries >> Cattle - Errors','Error 6 Information','Disposition Code'),
('Queries >> Cattle - Errors','Error 6 Information','DOB'),
('Queries >> Cattle - Errors','Error 6 Information','DRPC'),
('Queries >> Cattle - Errors','Error 6 Information','Error Code'),
('Queries >> Cattle - Errors','Error 6 Information','File Name'),
('Queries >> Cattle - Errors','Error 6 Information','Heath Event'),
('Queries >> Cattle - Errors','Error 6 Information','Herd'),
('Queries >> Cattle - Errors','Error 6 Information','Herd'),
('Queries >> Cattle - Errors','Error 6 Information','ID'),
('Queries >> Cattle - Errors','Error 6 Information','ID Change Code'),
('Queries >> Cattle - Errors','Error 6 Information','Lact Type'),
('Queries >> Cattle - Errors','Error 6 Information','Lact Ver'),
('Queries >> Cattle - Errors','Error 6 Information','Multi-Birth Code'),
('Queries >> Cattle - Errors','Error 6 Information','Parental Change Code'),
('Queries >> Cattle - Errors','Error 6 Information','Processing Date'),
('Queries >> Cattle - Errors','Error 6 Information','Record Type'),
('Queries >> Cattle - Errors','Error 6 Information','Sire'),
('Queries >> Cattle - Errors','Error 6 Information','Source Code'),
('Queries >> Cattle - Errors','Error 6 Information','Source Code'),
('Queries >> Cattle - Errors','Error 6 Information','Verification code'),
('Queries >> Cattle - Errors','Evaluation Run/Breed','Evaluation Breed'),
('Queries >> Cattle - Errors','Evaluation Run/Breed','RUN'),
('Queries >> Cattle - Errors','Pedigree Tree','Dam'),
('Queries >> Cattle - Errors','Pedigree Tree','Sire'),
('Queries >> Cattle - Evaluation','Animal Box ','Cross references'),
('Queries >> Cattle - Evaluation','Animal Box ','DOB'),
('Queries >> Cattle - Evaluation','Animal Box ','Genomic'),
('Queries >> Cattle - Evaluation','Animal Box ','Indicator'),
('Queries >> Cattle - Evaluation','Animal Box ','Long Name'),
('Queries >> Cattle - Evaluation','Animal Box ','Multi-Birth Code'),
('Queries >> Cattle - Evaluation','Animal Box ','Pedigree Comp %'),
('Queries >> Cattle - Evaluation','Animal Box ','Preferred ID'),
('Queries >> Cattle - Evaluation','Animal Box ','Recessive codes'),
('Queries >> Cattle - Evaluation','Animal Box ','Short Name'),
('Queries >> Cattle - Evaluation','Animal Box ','Source Code'),
('Queries >> Cattle - Evaluation','Bull History Evaluation','%US'),
('Queries >> Cattle - Evaluation','Bull History Evaluation','DAUS'),
('Queries >> Cattle - Evaluation','Bull History Evaluation','Eval Date'),
('Queries >> Cattle - Evaluation','Bull History Evaluation','Gen Ind'),
('Queries >> Cattle - Evaluation','Bull History Evaluation','HERDS'),
('Queries >> Cattle - Evaluation','Bull History Evaluation','MACE'),
('Queries >> Cattle - Evaluation','Bull History Evaluation','NM$'),
('Queries >> Cattle - Evaluation','Bull History Evaluation','PTA'),
('Queries >> Cattle - Evaluation','Country Contribution  ','DCE'),
('Queries >> Cattle - Evaluation','Country Contribution  ','DPR'),
('Queries >> Cattle - Evaluation','Country Contribution  ','DSB'),
('Queries >> Cattle - Evaluation','Country Contribution  ','MAS'),
('Queries >> Cattle - Evaluation','Country Contribution  ','Prod Life'),
('Queries >> Cattle - Evaluation','Country Contribution  ','SCE'),
('Queries >> Cattle - Evaluation','Country Contribution  ','SCS'),
('Queries >> Cattle - Evaluation','Country Contribution  ','SSB'),
('Queries >> Cattle - Evaluation','Country Contribution  ','Yield'),
('Queries >> Cattle - Evaluation','Evaluation  ','DAUS'),
('Queries >> Cattle - Evaluation','Evaluation  ','HERDS'),
('Queries >> Cattle - Evaluation','Evaluation  ','Name'),
('Queries >> Cattle - Evaluation','Evaluation  ','PA'),
('Queries >> Cattle - Evaluation','Evaluation  ','PTA'),
('Queries >> Cattle - Evaluation','Evaluation  ','REL'),
('Queries >> Cattle - Evaluation','Evaluation  ','RELPA'),
('Queries >> Cattle - Evaluation','Evaluation  ','SRC'),
('Queries >> Cattle - Evaluation','Evaluation  ','Unit'),
('Queries >> Cattle - Evaluation','Evaluation Run/Breed','Evaluation Breed'),
('Queries >> Cattle - Evaluation','Evaluation Run/Breed','Run or History'),
('Queries >> Cattle - Evaluation','Inbreeding  ','(%)'),
('Queries >> Cattle - Evaluation','Inbreeding  ','Expected Future Inbreeding'),
('Queries >> Cattle - Evaluation','Inbreeding  ','Type'),
('Queries >> Cattle - Evaluation','Merit  Table','Name'),
('Queries >> Cattle - Evaluation','Merit  Table','NM$ Percentile'),
('Queries >> Cattle - Evaluation','Merit  Table','PA'),
('Queries >> Cattle - Evaluation','Merit  Table','PTA'),
('Queries >> Cattle - Evaluation','Merit  Table','REL'),
('Queries >> Cattle - Evaluation','Merit  Table','RELPA'),
('Queries >> Cattle - Evaluation','Merit  Table','Unit'),
('Queries >> Cattle - Evaluation','NAAB ','Control Stud'),
('Queries >> Cattle - Evaluation','NAAB ','Current Status'),
('Queries >> Cattle - Evaluation','NAAB ','Enterred AI'),
('Queries >> Cattle - Evaluation','NAAB ','Original Stud'),
('Queries >> Cattle - Evaluation','NAAB ','Primary NAAB Code'),
('Queries >> Cattle - Evaluation','NAAB ','Sampling Status'),
('Queries >> Cattle - Evaluation','Pedigree Tree','Dam'),
('Queries >> Cattle - Evaluation','Pedigree Tree','Sire'),
('Queries >> Cattle - Evaluation','Sire Conception Rate','Breedings'),
('Queries >> Cattle - Evaluation','Sire Conception Rate','PTA'),
('Queries >> Cattle - Evaluation','Sire Conception Rate','REL'),
('Queries >> Cattle - Evaluation','Type Summary Evaluation','PTA'),
('Queries >> Cattle - Evaluation','Type Summary Evaluation','REL'),
('Queries >> Cattle - Evaluation','Type Summary Evaluation','Trait'),
('Queries >> Cattle - Genotype','Animal Box','Blend Code'),
('Queries >> Cattle - Genotype','Animal Box','DOB'),
('Queries >> Cattle - Genotype','Animal Box','Multi-Birth Code'),
('Queries >> Cattle - Genotype','Animal Box','Name'),
('Queries >> Cattle - Genotype','Animal Box','Preferred ID'),
('Queries >> Cattle - Genotype','Animal Box','Sex'),
('Queries >> Cattle - Genotype','Animal Box','Source Code'),
('Queries >> Cattle - Genotype','Genotype Confirmations and Genotype Conflicts ','Genotype Confirmations'),
('Queries >> Cattle - Genotype','Genotype Confirmations and Genotype Conflicts ','Genotype Conflicts'),
('Queries >> Cattle - Genotype','Nomination Status','FEE'),
('Queries >> Cattle - Genotype','Nomination Status','FEE'),
('Queries >> Cattle - Genotype','Nomination Status','Group/Herd'),
('Queries >> Cattle - Genotype','Nomination Status','Group/Herd'),
('Queries >> Cattle - Genotype','Nomination Status','Herd Code Different Reason Code'),
('Queries >> Cattle - Genotype','Nomination Status','Herd Code Different Reason Code'),
('Queries >> Cattle - Genotype','Nomination Status','Mod Date'),
('Queries >> Cattle - Genotype','Nomination Status','Mod Date'),
('Queries >> Cattle - Genotype','Nomination Status','Nom.Date'),
('Queries >> Cattle - Genotype','Nomination Status','Nom.Date'),
('Queries >> Cattle - Genotype','Nomination Status','Requester'),
('Queries >> Cattle - Genotype','Nomination Status','Requester'),
('Queries >> Cattle - Genotype','Pedigree Tree','Dam'),
('Queries >> Cattle - Genotype','Pedigree Tree','Maternal Grandsire'),
('Queries >> Cattle - Genotype','Pedigree Tree','Sire'),
('Queries >> Cattle - Genotype','Sample Status','Barcode & Position'),
('Queries >> Cattle - Genotype','Sample Status','Breed SNP Conflicts'),
('Queries >> Cattle - Genotype','Sample Status','Chip Name'),
('Queries >> Cattle - Genotype','Sample Status','Conflicts'),
('Queries >> Cattle - Genotype','Sample Status','Dam Status'),
('Queries >> Cattle - Genotype','Sample Status','FEE'),
('Queries >> Cattle - Genotype','Sample Status','Geno Arrival Date'),
('Queries >> Cattle - Genotype','Sample Status','Lab'),
('Queries >> Cattle - Genotype','Sample Status','Pending'),
('Queries >> Cattle - Genotype','Sample Status','Progeny Count'),
('Queries >> Cattle - Genotype','Sample Status','Requester'),
('Queries >> Cattle - Genotype','Sample Status','Sample ID'),
('Queries >> Cattle - Genotype','Sample Status','Sire Status'),
('Queries >> Cattle - Genotype','Sample Status','SNP Read'),
('Queries >> Cattle - Genotype','Sample Status','Tissue Source'),
('Queries >> Cattle - Genotype','Sample Status','Usability Ind.'),
('Queries >> Cattle - Herd - Cow Lactation ','Cow Lactation Records','Ctrl No'),
('Queries >> Cattle - Herd - Cow Lactation ','Cow Lactation Records','DIM'),
('Queries >> Cattle - Herd - Cow Lactation ','Cow Lactation Records','DRC'),
('Queries >> Cattle - Herd - Cow Lactation ','Cow Lactation Records','Fresh Date'),
('Queries >> Cattle - Herd - Cow Lactation ','Cow Lactation Records','Herd'),
('Queries >> Cattle - Herd - Cow Lactation ','Cow Lactation Records','Lact'),
('Queries >> Cattle - Herd - Cow Lactation ','Cow Lactation Records','LI'),
('Queries >> Cattle - Herd - Cow Lactation ','Cow Lactation Records','LT'),
('Queries >> Cattle - Herd - Cow Lactation ','Cow Lactation Records','Mk'),
('Queries >> Cattle - Herd - Cow Lactation ','Cow Lactation Records','Mod Date'),
('Queries >> Cattle - Herd - Cow Lactation ','Cow Lactation Records','Opn'),
('Queries >> Cattle - Herd - Cow Lactation ','Cow Lactation Records','OS%'),
('Queries >> Cattle - Herd - Cow Lactation ','Cow Lactation Records','PC'),
('Queries >> Cattle - Herd - Cow Lactation ','Cow Lactation Records','Proc Date'),
('Queries >> Cattle - Herd - Cow Lactation ','Cow Lactation Records','SCS'),
('Queries >> Cattle - Herd - Cow Lactation ','Cow Lactation Records','TC'),
('Queries >> Cattle - Herd - Cow Lactation ','Cow Lactation Records','TC2'),
('Queries >> Cattle - Herd - Cow Lactation ','Herd Information  ','Mod Date'),
('Queries >> Cattle - Herd - Cow Lactation ','Herd Information  ','Requested Herd ID'),
('Queries >> Cattle - Herd - Data Collection Rating','Herd Information  ','Mod Date'),
('Queries >> Cattle - Herd - Data Collection Rating','Herd Information  ','Requested Herd ID'),
('Queries >> Cattle - Herd - Data Collection Rating','Herd Test Information ','Animals'),
('Queries >> Cattle - Herd - Data Collection Rating','Herd Test Information ','DCA'),
('Queries >> Cattle - Herd - Data Collection Rating','Herd Test Information ','DIM'),
('Queries >> Cattle - Herd - Data Collection Rating','Herd Test Information ','Freq'),
('Queries >> Cattle - Herd - Data Collection Rating','Herd Test Information ','MRD'),
('Queries >> Cattle - Herd - Data Collection Rating','Herd Test Information ','Sampled'),
('Queries >> Cattle - Herd - Data Collection Rating','Herd Test Information ','Supv'),
('Queries >> Cattle - Herd - Data Collection Rating','Herd Test Information ','Test Day'),
('Queries >> Cattle - Herd - Data Collection Rating','Herd Test Information ','Weighed'),
('Queries >> Cattle - Herd - Herd Info','Get Fee  ','Fee code'),
('Queries >> Cattle - Herd - Herd Info','Get Fee  ','Health'),
('Queries >> Cattle - Herd - Herd Info','Get Fee  ','RUN'),
('Queries >> Cattle - Herd - Herd Info','Get Fee  ','Type'),
('Queries >> Cattle - Herd - Herd Info','Get Fee  ','Yield'),
('Queries >> Cattle - Herd - Herd Info','Herd Information  ','Address'),
('Queries >> Cattle - Herd - Herd Info','Herd Information  ','Center'),
('Queries >> Cattle - Herd - Herd Info','Herd Information  ','Farm name'),
('Queries >> Cattle - Herd - Herd Info','Herd Information  ','Herd Owner'),
('Queries >> Cattle - Herd - Herd Info','Herd Information  ','Mod Date'),
('Queries >> Cattle - Herd - Herd Info','Herd Information  ','Privacy'),
('Queries >> Cattle - Herd - Herd Info','Herd Information  ','Requested Herd ID'),
('Queries >> Cattle - Herd - Herd Info','Testing Characteristics','Age'),
('Queries >> Cattle - Herd - Herd Info','Testing Characteristics','Breed'),
('Queries >> Cattle - Herd - Herd Info','Testing Characteristics','Center'),
('Queries >> Cattle - Herd - Herd Info','Testing Characteristics','Cows'),
('Queries >> Cattle - Herd - Herd Info','Testing Characteristics','DHI'),
('Queries >> Cattle - Herd - Herd Info','Testing Characteristics','Fat'),
('Queries >> Cattle - Herd - Herd Info','Testing Characteristics','Freq'),
('Queries >> Cattle - Herd - Herd Info','Testing Characteristics','Good ID'),
('Queries >> Cattle - Herd - Herd Info','Testing Characteristics','In File'),
('Queries >> Cattle - Herd - Herd Info','Testing Characteristics','Method'),
('Queries >> Cattle - Herd - Herd Info','Testing Characteristics','Milk'),
('Queries >> Cattle - Herd - Herd Info','Testing Characteristics','MRD'),
('Queries >> Cattle - Herd - Herd Info','Testing Characteristics','Plan'),
('Queries >> Cattle - Herd - Herd Info','Testing Characteristics','Prot'),
('Queries >> Cattle - Herd - Herd Info','Testing Characteristics','QC'),
('Queries >> Cattle - Herd - Herd Info','Testing Characteristics','Sample'),
('Queries >> Cattle - Herd - Herd Info','Testing Characteristics','SCS'),
('Queries >> Cattle - Herd - Herd Info','Testing Characteristics','Ship%'),
('Queries >> Cattle - Herd - Herd Info','Testing Characteristics','Species'),
('Queries >> Cattle - Herd - Herd Info','Testing Characteristics','Supv'),
('Queries >> Cattle - Herd - Herd Info','Testing Characteristics','Test Date'),
('Queries >> Cattle - Herd - Herd Info','Testing Characteristics','Updated'),
('Queries >> Cattle - Herd - Herd Info','Testing Characteristics','Weigh'),
('Queries >> Cattle - Herd - List of Cows','Herd Information  ','Mod Date'),
('Queries >> Cattle - Herd - List of Cows','Herd Information  ','Requested Herd ID'),
('Queries >> Cattle - Herd - List of Cows','List of Cows by Termination Code','Animal'),
('Queries >> Cattle - Herd - List of Cows','List of Cows by Termination Code','DOB'),
('Queries >> Cattle - Herd - List of Cows','List of Cows by Termination Code','Name'),
('Queries >> Cattle - Herd - List of Cows','List of Cows by Termination Code','Termination code'),
('Queries >> Cattle - Herd - Test Day','Error Message','Error messages'),
('Queries >> Cattle - Herd - Test Day','Herd Information  ','Mod Date'),
('Queries >> Cattle - Herd - Test Day','Herd Information  ','Requested Herd ID'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','Age'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','Breed'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','Cross'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','Ctr'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','Date'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','DHI'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','Fat'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','Freq'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','GoodID'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','In File'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','Lab'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','Method'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','Milk'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','MRD'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','Mtr'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','Plant'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','Prot'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','QC'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','Sample'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','SCS'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','Ship%'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','Species'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','Supv'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','Updated'),
('Queries >> Cattle - Herd - Test Day','Herd Test-day Information','Weight'),
('Queries >> Cattle - ID/Pedigree','Animal Box','DOB'),
('Queries >> Cattle - ID/Pedigree','Animal Box','Long Name'),
('Queries >> Cattle - ID/Pedigree','Animal Box','Mod Date'),
('Queries >> Cattle - ID/Pedigree','Animal Box','Multi-Birth Code'),
('Queries >> Cattle - ID/Pedigree','Animal Box','Preferred ID'),
('Queries >> Cattle - ID/Pedigree','Animal Box','Registry Status'),
('Queries >> Cattle - ID/Pedigree','Animal Box','Requested Information'),
('Queries >> Cattle - ID/Pedigree','Animal Box','Sex'),
('Queries >> Cattle - ID/Pedigree','Animal Box','Source Code'),
('Queries >> Cattle - ID/Pedigree','Clonal Family Members of (DNA ID) ','Member'),
('Queries >> Cattle - ID/Pedigree','Clonal Family Members of (DNA ID) ','Mod Date'),
('Queries >> Cattle - ID/Pedigree','Clonal Family Members of (DNA ID) ','Source code'),
('Queries >> Cattle - ID/Pedigree','Cross References','ID'),
('Queries >> Cattle - ID/Pedigree','Cross References','Long Name'),
('Queries >> Cattle - ID/Pedigree','Cross References','Mod Date'),
('Queries >> Cattle - ID/Pedigree','Cross References','Reg'),
('Queries >> Cattle - ID/Pedigree','Cross References','Sex'),
('Queries >> Cattle - ID/Pedigree','Pedigree Tree','Paternal Grandam'),
('Queries >> Cattle - ID/Pedigree','Pedigree Tree','Patnernal Grandsire'),
('Queries >> Cattle - ID/Pedigree','Pedigree Tree','Sire'),
('Queries >> Cattle - ID/Pedigree','Pedigree Validation Record','Parentage Validation Record'),
('Queries >> Cattle - Lactations ','Animal Box','DOB'),
('Queries >> Cattle - Lactations ','Animal Box','Multi-Birth Code'),
('Queries >> Cattle - Lactations ','Animal Box','Name'),
('Queries >> Cattle - Lactations ','Animal Box','Preferred ID'),
('Queries >> Cattle - Lactations ','Animal Box','Sex'),
('Queries >> Cattle - Lactations ','Animal Box','Source Code'),
('Queries >> Cattle - Lactations ','Evaluation Run/Breed','Evaluation Breed'),
('Queries >> Cattle - Lactations ','Evaluation Run/Breed','Run'),
('Queries >> Cattle - Lactations ','Lactation Information - Standards, DCR, Actual for Yield Trait','Actual'),
('Queries >> Cattle - Lactations ','Lactation Information - Standards, DCR, Actual for Yield Trait','DCR'),
('Queries >> Cattle - Lactations ','Lactation Information - Standards, DCR, Actual for Yield Trait','Standard'),
('Queries >> Cattle - Lactations ','Lactation Information - Test Day','Adjusted Yield'),
('Queries >> Cattle - Lactations ','Lactation Information - Test Day','DIM'),
('Queries >> Cattle - Lactations ','Lactation Information - Test Day','Fat%'),
('Queries >> Cattle - Lactations ','Lactation Information - Test Day','Freq'),
('Queries >> Cattle - Lactations ','Lactation Information - Test Day','Milk'),
('Queries >> Cattle - Lactations ','Lactation Information - Test Day','NTD'),
('Queries >> Cattle - Lactations ','Lactation Information - Test Day','Prot%'),
('Queries >> Cattle - Lactations ','Lactation Information - Test Day','SCS'),
('Queries >> Cattle - Lactations ','Lactation Information - Test Day','Test Date'),
('Queries >> Cattle - Lactations ','Lactation Information - Test Day','Test No'),
('Queries >> Cattle - Lactations ','Lactation Information Records','Bth'),
('Queries >> Cattle - Lactations ','Lactation Information Records','Ctrl No'),
('Queries >> Cattle - Lactations ','Lactation Information Records','DIM'),
('Queries >> Cattle - Lactations ','Lactation Information Records','DRPC'),
('Queries >> Cattle - Lactations ','Lactation Information Records','Fresh Date'),
('Queries >> Cattle - Lactations ','Lactation Information Records','Herd'),
('Queries >> Cattle - Lactations ','Lactation Information Records','Lact'),
('Queries >> Cattle - Lactations ','Lactation Information Records','LI'),
('Queries >> Cattle - Lactations ','Lactation Information Records','LT'),
('Queries >> Cattle - Lactations ','Lactation Information Records','Mk'),
('Queries >> Cattle - Lactations ','Lactation Information Records','Mod Date'),
('Queries >> Cattle - Lactations ','Lactation Information Records','NTD'),
('Queries >> Cattle - Lactations ','Lactation Information Records','Opn'),
('Queries >> Cattle - Lactations ','Lactation Information Records','OS%'),
('Queries >> Cattle - Lactations ','Lactation Information Records','PC'),
('Queries >> Cattle - Lactations ','Lactation Information Records','Proc Date'),
('Queries >> Cattle - Lactations ','Lactation Information Records','TC'),
('Queries >> Cattle - Lactations ','Lactation Information Records','TC2'),
('Queries >> Cattle - Lactations ','Lactation Information Records','Usable'),
('Queries >> Cattle - Lactations ','Pedigree Tree','Dam'),
('Queries >> Cattle - Lactations ','Pedigree Tree','Sire'),
('Queries >> Cattle - Progeny','Animal Box','DOB'),
('Queries >> Cattle - Progeny','Animal Box','Long Name'),
('Queries >> Cattle - Progeny','Animal Box','Multi-Birth Code'),
('Queries >> Cattle - Progeny','Animal Box','Preferred ID'),
('Queries >> Cattle - Progeny','Animal Box','Sex'),
('Queries >> Cattle - Progeny','Animal Box','Source Code'),
('Queries >> Cattle - Progeny','Daughter List','Calving Date'),
('Queries >> Cattle - Progeny','Daughter List','Codes'),
('Queries >> Cattle - Progeny','Daughter List','Daughter'),
('Queries >> Cattle - Progeny','Daughter List','DIM'),
('Queries >> Cattle - Progeny','Daughter List','DOB'),
('Queries >> Cattle - Progeny','Daughter List','Eval Breed'),
('Queries >> Cattle - Progeny','Daughter List','Herd'),
('Queries >> Cattle - Progeny','Daughter List','Heterosis(%)'),
('Queries >> Cattle - Progeny','Daughter List','Lact'),
('Queries >> Cattle - Progeny','Daughter List','TC'),
('Queries >> Cattle - Progeny','Daughter List','Trait'),
('Queries >> Cattle - Progeny','Daughter List','Yield'),
('Queries >> Cattle - Progeny','Evaluation Run/Breed','Evaluation Breed'),
('Queries >> Cattle - Progeny','Evaluation Run/Breed','Run'),
('Queries >> Cattle - Progeny','Pedigree Tree','Dam'),
('Queries >> Cattle - Progeny','Pedigree Tree','Sire'),
('Queries >> Cattle - Progeny','Progeny Information','DOB'),
('Queries >> Cattle - Progeny','Progeny Information','Fresh Date'),
('Queries >> Cattle - Progeny','Progeny Information','Genotyped'),
('Queries >> Cattle - Progeny','Progeny Information','Grandsire Status'),
('Queries >> Cattle - Progeny','Progeny Information','Herd'),
('Queries >> Cattle - Progeny','Progeny Information','Lact'),
('Queries >> Cattle - Progeny','Progeny Information','Multi-Birth Code'),
('Queries >> Cattle - Progeny','Progeny Information','Progeny'),
('Queries >> Cattle - Progeny','Progeny Information','Sex'),
('Queries >> Cattle - Progeny','Progeny Information','Sire'),
('Queries >> Cattle - Progeny','Progeny Information','Source Code'),
('Queries >> Goat - Errors','Animal Box','DOB'),
('Queries >> Goat - Errors','Animal Box','Multi-Birth Code'),
('Queries >> Goat - Errors','Animal Box','Name'),
('Queries >> Goat - Errors','Animal Box','Preferred ID'),
('Queries >> Goat - Errors','Animal Box','Sex'),
('Queries >> Goat - Errors','Animal Box','Source Code'),
('Queries >> Goat - Errors','Error 1 Information','Cross references'),
('Queries >> Goat - Errors','Error 1 Information','Date Processed'),
('Queries >> Goat - Errors','Error 1 Information','Description'),
('Queries >> Goat - Errors','Error 1 Information','Disposition Code'),
('Queries >> Goat - Errors','Error 1 Information','DOB'),
('Queries >> Goat - Errors','Error 1 Information','DRPC'),
('Queries >> Goat - Errors','Error 1 Information','Error Code'),
('Queries >> Goat - Errors','Error 1 Information','File Name'),
('Queries >> Goat - Errors','Error 1 Information','Herd'),
('Queries >> Goat - Errors','Error 1 Information','ID'),
('Queries >> Goat - Errors','Error 1 Information','ID Change Code'),
('Queries >> Goat - Errors','Error 1 Information','Multi-Birth Code'),
('Queries >> Goat - Errors','Error 1 Information','Parental Change Code'),
('Queries >> Goat - Errors','Error 1 Information','Processing Date'),
('Queries >> Goat - Errors','Error 1 Information','Record Type'),
('Queries >> Goat - Errors','Error 1 Information','Sire'),
('Queries >> Goat - Errors','Error 1 Information','Source Code'),
('Queries >> Goat - Errors','Error 1 Information','Source Code'),
('Queries >> Goat - Errors','Error 1 Information','Verification code'),
('Queries >> Goat - Errors','Error 4 Information','Affilication'),
('Queries >> Goat - Errors','Error 4 Information','Breeding Date'),
('Queries >> Goat - Errors','Error 4 Information','Calving Date'),
('Queries >> Goat - Errors','Error 4 Information','Control Number'),
('Queries >> Goat - Errors','Error 4 Information','Cross references'),
('Queries >> Goat - Errors','Error 4 Information','Date Processed'),
('Queries >> Goat - Errors','Error 4 Information','Days3x'),
('Queries >> Goat - Errors','Error 4 Information','Description'),
('Queries >> Goat - Errors','Error 4 Information','Disposition Code'),
('Queries >> Goat - Errors','Error 4 Information','DIM'),
('Queries >> Goat - Errors','Error 4 Information','DOB'),
('Queries >> Goat - Errors','Error 4 Information','Dry'),
('Queries >> Goat - Errors','Error 4 Information','DRPC'),
('Queries >> Goat - Errors','Error 4 Information','Error Code'),
('Queries >> Goat - Errors','Error 4 Information','Fat'),
('Queries >> Goat - Errors','Error 4 Information','File Name'),
('Queries >> Goat - Errors','Error 4 Information','Herd'),
('Queries >> Goat - Errors','Error 4 Information','Herd'),
('Queries >> Goat - Errors','Error 4 Information','ID'),
('Queries >> Goat - Errors','Error 4 Information','ID Change Code'),
('Queries >> Goat - Errors','Error 4 Information','Initiation Code'),
('Queries >> Goat - Errors','Error 4 Information','Lact'),
('Queries >> Goat - Errors','Error 4 Information','Lact Type'),
('Queries >> Goat - Errors','Error 4 Information','Lact Ver'),
('Queries >> Goat - Errors','Error 4 Information','Milk'),
('Queries >> Goat - Errors','Error 4 Information','Multi-Birth Code'),
('Queries >> Goat - Errors','Error 4 Information','Parental Change Code'),
('Queries >> Goat - Errors','Error 4 Information','Processing Date'),
('Queries >> Goat - Errors','Error 4 Information','Progeny'),
('Queries >> Goat - Errors','Error 4 Information','Protein'),
('Queries >> Goat - Errors','Error 4 Information','Record Type'),
('Queries >> Goat - Errors','Error 4 Information','SCS'),
('Queries >> Goat - Errors','Error 4 Information','Sire'),
('Queries >> Goat - Errors','Error 4 Information','Source Code'),
('Queries >> Goat - Errors','Error 4 Information','Source Code'),
('Queries >> Goat - Errors','Error 4 Information','Termination Code'),
('Queries >> Goat - Errors','Error 4 Information','Test Day Data'),
('Queries >> Goat - Errors','Error 4 Information','TOT'),
('Queries >> Goat - Errors','Error 4 Information','Verification code'),
('Queries >> Goat - Errors','Error 5 Information ','Affilication'),
('Queries >> Goat - Errors','Error 5 Information ','Affilication'),
('Queries >> Goat - Errors','Error 5 Information ','Calving Date'),
('Queries >> Goat - Errors','Error 5 Information ','Calving Date'),
('Queries >> Goat - Errors','Error 5 Information ','Control Number'),
('Queries >> Goat - Errors','Error 5 Information ','Control Number'),
('Queries >> Goat - Errors','Error 5 Information ','Cross references'),
('Queries >> Goat - Errors','Error 5 Information ','Cross references'),
('Queries >> Goat - Errors','Error 5 Information ','Date Processed'),
('Queries >> Goat - Errors','Error 5 Information ','Date Processed'),
('Queries >> Goat - Errors','Error 5 Information ','Description'),
('Queries >> Goat - Errors','Error 5 Information ','Description'),
('Queries >> Goat - Errors','Error 5 Information ','Disposition Code'),
('Queries >> Goat - Errors','Error 5 Information ','Disposition Code'),
('Queries >> Goat - Errors','Error 5 Information ','DOB'),
('Queries >> Goat - Errors','Error 5 Information ','DOB'),
('Queries >> Goat - Errors','Error 5 Information ','DRPC'),
('Queries >> Goat - Errors','Error 5 Information ','DRPC'),
('Queries >> Goat - Errors','Error 5 Information ','Error Code'),
('Queries >> Goat - Errors','Error 5 Information ','File Name'),
('Queries >> Goat - Errors','Error 5 Information ','File Name'),
('Queries >> Goat - Errors','Error 5 Information ','Heath Event'),
('Queries >> Goat - Errors','Error 5 Information ','Herd'),
('Queries >> Goat - Errors','Error 5 Information ','Herd'),
('Queries >> Goat - Errors','Error 5 Information ','Herd'),
('Queries >> Goat - Errors','Error 5 Information ','Herd'),
('Queries >> Goat - Errors','Error 5 Information ','ID'),
('Queries >> Goat - Errors','Error 5 Information ','ID'),
('Queries >> Goat - Errors','Error 5 Information ','ID Change Code'),
('Queries >> Goat - Errors','Error 5 Information ','ID Change Code'),
('Queries >> Goat - Errors','Error 5 Information ','Lact Type'),
('Queries >> Goat - Errors','Error 5 Information ','Lact Type'),
('Queries >> Goat - Errors','Error 5 Information ','Lact Ver'),
('Queries >> Goat - Errors','Error 5 Information ','Lact Ver'),
('Queries >> Goat - Errors','Error 5 Information ','Multi-Birth Code'),
('Queries >> Goat - Errors','Error 5 Information ','Multi-Birth Code'),
('Queries >> Goat - Errors','Error 5 Information ','Parental Change Code'),
('Queries >> Goat - Errors','Error 5 Information ','Parental Change Code'),
('Queries >> Goat - Errors','Error 5 Information ','Processing Date'),
('Queries >> Goat - Errors','Error 5 Information ','Processing Date'),
('Queries >> Goat - Errors','Error 5 Information ','Record Type'),
('Queries >> Goat - Errors','Error 5 Information ','Record Type'),
('Queries >> Goat - Errors','Error 5 Information ','Reproductive Event'),
('Queries >> Goat - Errors','Error 5 Information ','Sire'),
('Queries >> Goat - Errors','Error 5 Information ','Sire'),
('Queries >> Goat - Errors','Error 5 Information ','Source Code'),
('Queries >> Goat - Errors','Error 5 Information ','Source Code'),
('Queries >> Goat - Errors','Error 5 Information ','Source Code'),
('Queries >> Goat - Errors','Error 5 Information ','Source Code'),
('Queries >> Goat - Errors','Error 5 Information ','Verification code'),
('Queries >> Goat - Errors','Error 5 Information ','Verification code'),
('Queries >> Goat - Errors','Evaluation Run/Breed','Evaluation Breed'),
('Queries >> Goat - Errors','Evaluation Run/Breed','RUN'),
('Queries >> Goat - Errors','Evaluation Run/Breed','Sire'),
('Queries >> Goat - Errors','Pedigree Tree','Dam'),
('Queries >> Goat - Evaluation','Animal Box ','Cross references'),
('Queries >> Goat - Evaluation','Animal Box ','DOB'),
('Queries >> Goat - Evaluation','Animal Box ','Herd With Herd Daughters'),
('Queries >> Goat - Evaluation','Animal Box ','Long Name'),
('Queries >> Goat - Evaluation','Animal Box ','Multi-Birth Code'),
('Queries >> Goat - Evaluation','Animal Box ','Number of Daughters'),
('Queries >> Goat - Evaluation','Animal Box ','Preferred ID'),
('Queries >> Goat - Evaluation','Animal Box ','Recessive codes'),
('Queries >> Goat - Evaluation','Animal Box ','Short Name'),
('Queries >> Goat - Evaluation','Animal Box ','Source Code'),
('Queries >> Goat - Evaluation','Buck History Evaluation','DAUS'),
('Queries >> Goat - Evaluation','Buck History Evaluation','Eval Date'),
('Queries >> Goat - Evaluation','Buck History Evaluation','HERDS'),
('Queries >> Goat - Evaluation','Buck History Evaluation','MFP$'),
('Queries >> Goat - Evaluation','Buck History Evaluation','PTA'),
('Queries >> Goat - Evaluation','Evaluation  ','DAUS'),
('Queries >> Goat - Evaluation','Evaluation  ','HERDS'),
('Queries >> Goat - Evaluation','Evaluation  ','LACT/DAUS'),
('Queries >> Goat - Evaluation','Evaluation  ','MEAN'),
('Queries >> Goat - Evaluation','Evaluation  ','NAME'),
('Queries >> Goat - Evaluation','Evaluation  ','PTA'),
('Queries >> Goat - Evaluation','Evaluation  ','PTA%'),
('Queries >> Goat - Evaluation','Evaluation  ','REL'),
('Queries >> Goat - Evaluation','Evaluation  ','UNIT'),
('Queries >> Goat - Evaluation','Evaluation Run/Breed','Evaluation Breed'),
('Queries >> Goat - Evaluation','Evaluation Run/Breed','RUN'),
('Queries >> Goat - Evaluation','Inbreeding  ','(%)'),
('Queries >> Goat - Evaluation','Inbreeding  ','Type'),
('Queries >> Goat - Evaluation','Merit  Table','Name'),
('Queries >> Goat - Evaluation','Merit  Table','NM$ Percentile'),
('Queries >> Goat - Evaluation','Merit  Table','PTA'),
('Queries >> Goat - Evaluation','Merit  Table','Unit'),
('Queries >> Goat - Evaluation','Pedigree Tree ','Dam'),
('Queries >> Goat - Evaluation','Pedigree Tree ','Sire'),
('Queries >> Goat - Evaluation','Type Summary Evaluation','Appraisais'),
('Queries >> Goat - Evaluation','Type Summary Evaluation','Dau Score'),
('Queries >> Goat - Evaluation','Type Summary Evaluation','Dau/hd'),
('Queries >> Goat - Evaluation','Type Summary Evaluation','Daus'),
('Queries >> Goat - Evaluation','Type Summary Evaluation','Herds'),
('Queries >> Goat - Evaluation','Type Summary Evaluation','PTA'),
('Queries >> Goat - Evaluation','Type Summary Evaluation','REL'),
('Queries >> Goat - Evaluation','Type Summary Evaluation','States'),
('Queries >> Goat - Evaluation','Type Summary Evaluation','Trait'),
('Queries >> Goat - Herd - Doe Lactation','Doe Lactation Records  ','Ctrl No'),
('Queries >> Goat - Herd - Doe Lactation','Doe Lactation Records  ','DCR'),
('Queries >> Goat - Herd - Doe Lactation','Doe Lactation Records  ','DCR'),
('Queries >> Goat - Herd - Doe Lactation','Doe Lactation Records  ','DIM'),
('Queries >> Goat - Herd - Doe Lactation','Doe Lactation Records  ','Doe'),
('Queries >> Goat - Herd - Doe Lactation','Doe Lactation Records  ','Fat'),
('Queries >> Goat - Herd - Doe Lactation','Doe Lactation Records  ','Fresh Date'),
('Queries >> Goat - Herd - Doe Lactation','Doe Lactation Records  ','Lact'),
('Queries >> Goat - Herd - Doe Lactation','Doe Lactation Records  ','LI'),
('Queries >> Goat - Herd - Doe Lactation','Doe Lactation Records  ','LT'),
('Queries >> Goat - Herd - Doe Lactation','Doe Lactation Records  ','Milk'),
('Queries >> Goat - Herd - Doe Lactation','Doe Lactation Records  ','Mk'),
('Queries >> Goat - Herd - Doe Lactation','Doe Lactation Records  ','Mod Date'),
('Queries >> Goat - Herd - Doe Lactation','Doe Lactation Records  ','Opn'),
('Queries >> Goat - Herd - Doe Lactation','Doe Lactation Records  ','OS%'),
('Queries >> Goat - Herd - Doe Lactation','Doe Lactation Records  ','PC'),
('Queries >> Goat - Herd - Doe Lactation','Doe Lactation Records  ','Proc Date'),
('Queries >> Goat - Herd - Doe Lactation','Doe Lactation Records  ','Prot'),
('Queries >> Goat - Herd - Doe Lactation','Doe Lactation Records  ','SCS'),
('Queries >> Goat - Herd - Doe Lactation','Doe Lactation Records  ','TC'),
('Queries >> Goat - Herd - Doe Lactation','Herd Information  ','Mod Date'),
('Queries >> Goat - Herd - Doe Lactation','Herd Information  ','Requested Herd ID'),
('Queries >> Goat - Herd - Errors','Error Information ','Affilication'),
('Queries >> Goat - Herd - Errors','Error Information ','Breeding Date'),
('Queries >> Goat - Herd - Errors','Error Information ','Calving Date'),
('Queries >> Goat - Herd - Errors','Error Information ','Control Number'),
('Queries >> Goat - Herd - Errors','Error Information ','Cross references'),
('Queries >> Goat - Herd - Errors','Error Information ','Date Processed'),
('Queries >> Goat - Herd - Errors','Error Information ','Days3x'),
('Queries >> Goat - Herd - Errors','Error Information ','Description'),
('Queries >> Goat - Herd - Errors','Error Information ','Disposition Code'),
('Queries >> Goat - Herd - Errors','Error Information ','DIM'),
('Queries >> Goat - Herd - Errors','Error Information ','DOB'),
('Queries >> Goat - Herd - Errors','Error Information ','Dry'),
('Queries >> Goat - Herd - Errors','Error Information ','DRPC'),
('Queries >> Goat - Herd - Errors','Error Information ','Error Code'),
('Queries >> Goat - Herd - Errors','Error Information ','Fat'),
('Queries >> Goat - Herd - Errors','Error Information ','File Name'),
('Queries >> Goat - Herd - Errors','Error Information ','Herd'),
('Queries >> Goat - Herd - Errors','Error Information ','Herd'),
('Queries >> Goat - Herd - Errors','Error Information ','ID'),
('Queries >> Goat - Herd - Errors','Error Information ','ID Change Code'),
('Queries >> Goat - Herd - Errors','Error Information ','Initiation Code'),
('Queries >> Goat - Herd - Errors','Error Information ','Lact'),
('Queries >> Goat - Herd - Errors','Error Information ','Lact Type'),
('Queries >> Goat - Herd - Errors','Error Information ','Lact Ver'),
('Queries >> Goat - Herd - Errors','Error Information ','Milk'),
('Queries >> Goat - Herd - Errors','Error Information ','Multi-Birth Code'),
('Queries >> Goat - Herd - Errors','Error Information ','Parental Change Code'),
('Queries >> Goat - Herd - Errors','Error Information ','Processing Date'),
('Queries >> Goat - Herd - Errors','Error Information ','Progeny'),
('Queries >> Goat - Herd - Errors','Error Information ','Protein'),
('Queries >> Goat - Herd - Errors','Error Information ','Record Type'),
('Queries >> Goat - Herd - Errors','Error Information ','SCS'),
('Queries >> Goat - Herd - Errors','Error Information ','Sire'),
('Queries >> Goat - Herd - Errors','Error Information ','Source Code'),
('Queries >> Goat - Herd - Errors','Error Information ','Source Code'),
('Queries >> Goat - Herd - Errors','Error Information ','Termination Code'),
('Queries >> Goat - Herd - Errors','Error Information ','Test Day Data'),
('Queries >> Goat - Herd - Errors','Error Information ','TOT'),
('Queries >> Goat - Herd - Errors','Error Information ','Verification code'),
('Queries >> Goat - Herd - Errors','Herd Information  ','Mod Date'),
('Queries >> Goat - Herd - Errors','Herd Information  ','Requested Herd ID'),
('Queries >> Goat - Herd - Herd Info','Herd Information  ','Address'),
('Queries >> Goat - Herd - Herd Info','Herd Information  ','Center'),
('Queries >> Goat - Herd - Herd Info','Herd Information  ','Farm Name'),
('Queries >> Goat - Herd - Herd Info','Herd Information  ','Mod Date'),
('Queries >> Goat - Herd - Herd Info','Herd Information  ','Privacy'),
('Queries >> Goat - Herd - Herd Info','Herd Information  ','Requested Herd ID'),
('Queries >> Goat - Herd - Herd Info','Testing Characteristics','Age'),
('Queries >> Goat - Herd - Herd Info','Testing Characteristics','Breed'),
('Queries >> Goat - Herd - Herd Info','Testing Characteristics','Center'),
('Queries >> Goat - Herd - Herd Info','Testing Characteristics','DHI'),
('Queries >> Goat - Herd - Herd Info','Testing Characteristics','Does'),
('Queries >> Goat - Herd - Herd Info','Testing Characteristics','Fat'),
('Queries >> Goat - Herd - Herd Info','Testing Characteristics','Freq'),
('Queries >> Goat - Herd - Herd Info','Testing Characteristics','Good ID'),
('Queries >> Goat - Herd - Herd Info','Testing Characteristics','In File'),
('Queries >> Goat - Herd - Herd Info','Testing Characteristics','Method'),
('Queries >> Goat - Herd - Herd Info','Testing Characteristics','Milk'),
('Queries >> Goat - Herd - Herd Info','Testing Characteristics','MRD'),
('Queries >> Goat - Herd - Herd Info','Testing Characteristics','Plan'),
('Queries >> Goat - Herd - Herd Info','Testing Characteristics','Prot'),
('Queries >> Goat - Herd - Herd Info','Testing Characteristics','QC'),
('Queries >> Goat - Herd - Herd Info','Testing Characteristics','Sample'),
('Queries >> Goat - Herd - Herd Info','Testing Characteristics','SCS'),
('Queries >> Goat - Herd - Herd Info','Testing Characteristics','Ship%'),
('Queries >> Goat - Herd - Herd Info','Testing Characteristics','Species'),
('Queries >> Goat - Herd - Herd Info','Testing Characteristics','Supv'),
('Queries >> Goat - Herd - Herd Info','Testing Characteristics','Test Date'),
('Queries >> Goat - Herd - Herd Info','Testing Characteristics','Updated'),
('Queries >> Goat - Herd - Herd Info','Testing Characteristics','Weigh'),
('Queries >> Goat - Herd - Test Day','Herd Information  ','Mod Date'),
('Queries >> Goat - Herd - Test Day','Herd Information  ','Requested Herd ID'),
('Queries >> Goat - Herd - Test Day','Herd Test-Day Information  ','Age'),
('Queries >> Goat - Herd - Test Day','Herd Test-Day Information  ','Breed'),
('Queries >> Goat - Herd - Test Day','Herd Test-Day Information  ','Count'),
('Queries >> Goat - Herd - Test Day','Herd Test-Day Information  ','Cross'),
('Queries >> Goat - Herd - Test Day','Herd Test-Day Information  ','Ctr'),
('Queries >> Goat - Herd - Test Day','Herd Test-Day Information  ','Date'),
('Queries >> Goat - Herd - Test Day','Herd Test-Day Information  ','DHI'),
('Queries >> Goat - Herd - Test Day','Herd Test-Day Information  ','Fat'),
('Queries >> Goat - Herd - Test Day','Herd Test-Day Information  ','Freq'),
('Queries >> Goat - Herd - Test Day','Herd Test-Day Information  ','GoodID'),
('Queries >> Goat - Herd - Test Day','Herd Test-Day Information  ','Lab'),
('Queries >> Goat - Herd - Test Day','Herd Test-Day Information  ','Method'),
('Queries >> Goat - Herd - Test Day','Herd Test-Day Information  ','Milk'),
('Queries >> Goat - Herd - Test Day','Herd Test-Day Information  ','MRD'),
('Queries >> Goat - Herd - Test Day','Herd Test-Day Information  ','Mtr'),
('Queries >> Goat - Herd - Test Day','Herd Test-Day Information  ','Plant'),
('Queries >> Goat - Herd - Test Day','Herd Test-Day Information  ','Prot'),
('Queries >> Goat - Herd - Test Day','Herd Test-Day Information  ','Sample'),
('Queries >> Goat - Herd - Test Day','Herd Test-Day Information  ','SCS'),
('Queries >> Goat - Herd - Test Day','Herd Test-Day Information  ','Ship%'),
('Queries >> Goat - Herd - Test Day','Herd Test-Day Information  ','Species'),
('Queries >> Goat - Herd - Test Day','Herd Test-Day Information  ','Supv'),
('Queries >> Goat - Herd - Test Day','Herd Test-Day Information  ','Updated'),
('Queries >> Goat - Herd - Test Day','Herd Test-Day Information  ','Weight'),
('Queries >> Goat - ID/Pedigree','Animal Box','DOB'),
('Queries >> Goat - ID/Pedigree','Animal Box','Long Name'),
('Queries >> Goat - ID/Pedigree','Animal Box','Member'),
('Queries >> Goat - ID/Pedigree','Animal Box','Mod Date'),
('Queries >> Goat - ID/Pedigree','Animal Box','Mod Date'),
('Queries >> Goat - ID/Pedigree','Animal Box','Multi-Birth Code'),
('Queries >> Goat - ID/Pedigree','Animal Box','Preferred ID'),
('Queries >> Goat - ID/Pedigree','Animal Box','Registry Status'),
('Queries >> Goat - ID/Pedigree','Animal Box','Requested Information'),
('Queries >> Goat - ID/Pedigree','Animal Box','Sex'),
('Queries >> Goat - ID/Pedigree','Animal Box','Source code'),
('Queries >> Goat - ID/Pedigree','Animal Box','Source Code'),
('Queries >> Goat - ID/Pedigree','Cross References','ID'),
('Queries >> Goat - ID/Pedigree','Cross References','Long Name'),
('Queries >> Goat - ID/Pedigree','Cross References','Mod Date'),
('Queries >> Goat - ID/Pedigree','Cross References','Reg'),
('Queries >> Goat - ID/Pedigree','Cross References','Sex'),
('Queries >> Goat - ID/Pedigree','Pedigree Tree ','Paternal Grandam'),
('Queries >> Goat - ID/Pedigree','Pedigree Tree ','Patnernal Grandsire'),
('Queries >> Goat - ID/Pedigree','Pedigree Tree ','Sire'),
('Queries >> Goat - Lactations','Animal Box','DOB'),
('Queries >> Goat - Lactations','Animal Box','Multi-Birth Code'),
('Queries >> Goat - Lactations','Animal Box','Name'),
('Queries >> Goat - Lactations','Animal Box','Parentage Validation Record'),
('Queries >> Goat - Lactations','Animal Box','Preferred ID'),
('Queries >> Goat - Lactations','Animal Box','Sex'),
('Queries >> Goat - Lactations','Animal Box','Source Code'),
('Queries >> Goat - Lactations','Evaluation Run/Breed','Evaluation Breed'),
('Queries >> Goat - Lactations','Evaluation Run/Breed','RUN'),
('Queries >> Goat - Lactations','Lactation Information - Standards, DCR, Actual for Yield Trait','DCR'),
('Queries >> Goat - Lactations','Lactation Information - Test Day','DIM'),
('Queries >> Goat - Lactations','Lactation Information - Test Day','Fat%'),
('Queries >> Goat - Lactations','Lactation Information - Test Day','Fred'),
('Queries >> Goat - Lactations','Lactation Information - Test Day','Milk'),
('Queries >> Goat - Lactations','Lactation Information - Test Day','Prot%'),
('Queries >> Goat - Lactations','Lactation Information - Test Day','SCB'),
('Queries >> Goat - Lactations','Lactation Information - Test Day','Test Date'),
('Queries >> Goat - Lactations','Lactation Information - Test Day','Test No'),
('Queries >> Goat - Lactations','Lactation Information Records','Bth'),
('Queries >> Goat - Lactations','Lactation Information Records','Ctrl No'),
('Queries >> Goat - Lactations','Lactation Information Records','DIM'),
('Queries >> Goat - Lactations','Lactation Information Records','DRPC'),
('Queries >> Goat - Lactations','Lactation Information Records','Fresh Date'),
('Queries >> Goat - Lactations','Lactation Information Records','Herd'),
('Queries >> Goat - Lactations','Lactation Information Records','Lact'),
('Queries >> Goat - Lactations','Lactation Information Records','LI'),
('Queries >> Goat - Lactations','Lactation Information Records','LT'),
('Queries >> Goat - Lactations','Lactation Information Records','Mk'),
('Queries >> Goat - Lactations','Lactation Information Records','Mod Date'),
('Queries >> Goat - Lactations','Lactation Information Records','NTD'),
('Queries >> Goat - Lactations','Lactation Information Records','Opn'),
('Queries >> Goat - Lactations','Lactation Information Records','OS%'),
('Queries >> Goat - Lactations','Lactation Information Records','PC'),
('Queries >> Goat - Lactations','Lactation Information Records','Proc Date'),
('Queries >> Goat - Lactations','Lactation Information Records','TC'),
('Queries >> Goat - Lactations','Lactation Information Records','TC2'),
('Queries >> Goat - Lactations','Lactation Information Records','Usable'),
('Queries >> Goat - Lactations','Pedigree Tree','Dam'),
('Queries >> Goat - Lactations','Pedigree Tree','Sire'),
('Queries >> Goat - Progeny','Animal Box','DOB'),
('Queries >> Goat - Progeny','Animal Box','Long Name'),
('Queries >> Goat - Progeny','Animal Box','Multi-Birth Code'),
('Queries >> Goat - Progeny','Animal Box','Preferred ID'),
('Queries >> Goat - Progeny','Animal Box','Sex'),
('Queries >> Goat - Progeny','Animal Box','Source Code'),
('Queries >> Goat - Progeny','Evaluation Run/Breed','Evaluation Breed'),
('Queries >> Goat - Progeny','Evaluation Run/Breed','RUN'),
('Queries >> Goat - Progeny','Pedigree Tree','Sire'),
('Queries >> Goat - Progeny','Progeny Information ','Dam'),
('Queries >> Goat - Progeny','Progeny Information ','DOB'),
('Queries >> Goat - Progeny','Progeny Information ','Fresh Date'),
('Queries >> Goat - Progeny','Progeny Information ','Herd'),
('Queries >> Goat - Progeny','Progeny Information ','Lact'),
('Queries >> Goat - Progeny','Progeny Information ','Multi-Birth Code'),
('Queries >> Goat - Progeny','Progeny Information ','Name'),
('Queries >> Goat - Progeny','Progeny Information ','Progeny'),
('Queries >> Goat - Progeny','Progeny Information ','Sex'),
('Queries >> Goat - Progeny','Progeny Information ','Source Code'),
('Special Section >>  Get Fee','Get Fee by Animal ID (17 bytes)  ','Animal'),
('Special Section >>  Get Fee','Get Fee by Animal ID (17 bytes)  ','Dam'),
('Special Section >>  Get Fee','Get Fee by Herd ID  ','Fee Code'),
('Special Section >>  Get Fee','Get Fee by Herd ID  ','Health'),
('Special Section >>  Get Fee','Get Fee by Herd ID  ','Herd'),
('Special Section >>  Get Fee','Get Fee by Herd ID  ','Type'),
('Special Section >>  Get Fee','Get Fee by Herd ID  ','Yield'),
('Special Section >> Check fmt1 Record','Comparision between the input file and CDCB file ','Animal'),
('Special Section >> Check fmt1 Record','Comparision between the input file and CDCB file ','Dam'),
('Special Section >> Check fmt1 Record','Comparision between the input file and CDCB file ','DOB'),
('Special Section >> Check fmt1 Record','Comparision between the input file and CDCB file ','Input'),
('Special Section >> Check fmt1 Record','Comparision between the input file and CDCB file ','Multi-Birth Code'),
('Special Section >> Check fmt1 Record','Comparision between the input file and CDCB file ','Name'),
('Special Section >> Check fmt1 Record','Comparision between the input file and CDCB file ','Sex'),
('Special Section >> Check fmt1 Record','Comparision between the input file and CDCB file ','Sire'),
('Special Section >> Check fmt1 Record','Comparision between the input file and CDCB file ','Source Code'),
('Special Section >> History of Genotype','History of Genotype by Animal ID/Sample ID/Barcode&Position','Animal'),
('Special Section >> History of Genotype','History of Genotype by Animal ID/Sample ID/Barcode&Position','Barcode and position'),
('Special Section >> History of Genotype','History of Genotype by Animal ID/Sample ID/Barcode&Position','Sample ID'),
('Special Section >> History of Genotype','History of Genotype by Animal ID/Sample ID/Barcode&Position','Sex'),
('Special Section >> History of Genotype','History of Genotype by Animal ID/Sample ID/Barcode&Position','Timestamp'),
('Special Section >> ID Range','Special Section >> ID Range','Animal'),
('Special Section >> ID Range','Special Section >> ID Range','Date Entered'),
('Special Section >> ID Range','Special Section >> ID Range','Number'),
('Special Section >> ID Range','Special Section >> ID Range','Source'),
('Special Section >> Move Genotype','Special Section >> Move Genotype','Animal'),
('Special Section >> Move Genotype','Special Section >> Move Genotype','Barcode and position'),
('Special Section >> Move Genotype','Special Section >> Move Genotype','Chip Number'),
('Special Section >> Move Genotype','Special Section >> Move Genotype','Move to'),
('Special Section >> Move Genotype','Special Section >> Move Genotype','Requester'),
('Special Section >> Move Genotype','Special Section >> Move Genotype','Sample ID'),
('Special Section >> Move Genotype','Special Section >> Move Genotype','Usability Ind'),
('Special Section >> Nominate Genotype','Create Animal and Nominate  ','Animal'),
('Special Section >> Nominate Genotype','Create Animal and Nominate  ','Dam'),
('Special Section >> Nominate Genotype','Create Animal and Nominate  ','DOB'),
('Special Section >> Nominate Genotype','Create Animal and Nominate  ','Fee'),
('Special Section >> Nominate Genotype','Create Animal and Nominate  ','G/H'),
('Special Section >> Nominate Genotype','Create Animal and Nominate  ','HRC'),
('Special Section >> Nominate Genotype','Create Animal and Nominate  ','MBC'),
('Special Section >> Nominate Genotype','Create Animal and Nominate  ','Name'),
('Special Section >> Nominate Genotype','Create Animal and Nominate  ','Ped Verif'),
('Special Section >> Nominate Genotype','Create Animal and Nominate  ','Rec Ver'),
('Special Section >> Nominate Genotype','Create Animal and Nominate  ','Reg Stat'),
('Special Section >> Nominate Genotype','Create Animal and Nominate  ','Requester'),
('Special Section >> Nominate Genotype','Create Animal and Nominate  ','Sample ID'),
('Special Section >> Nominate Genotype','Create Animal and Nominate  ','Sex'),
('Special Section >> Nominate Genotype','Create Animal and Nominate  ','Sire'),
('Special Section >> Performance Metrics ','Get Laboratory Performance Metrics based on Lab ID','Historical Months'),
('Special Section >> Performance Metrics ','Get Laboratory Performance Metrics based on Lab ID','Metric'),
('Special Section >> Performance Metrics ','Get Laboratory Performance Metrics based on Lab ID','Threshold'),
('Special Section >> Performance Metrics ','Get Nomination Performance Metrics based on Requester ID','Historical Months'),
('Special Section >> Performance Metrics ','Get Nomination Performance Metrics based on Requester ID','Metric'),
('Special Section >> Performance Metrics ','Get Nomination Performance Metrics based on Requester ID','Threshold'),
('Special Section >> Reports','Get Animals with genotypes that conflict with imputed dam genotypes','Animal'),
('Special Section >> Reports','Get Animals with genotypes that conflict with imputed dam genotypes','Dam'),
('Special Section >> Reports','Get Animals with genotypes that conflict with imputed dam genotypes','Geno Arrival Date'),
('Special Section >> Reports','Get Animals with genotypes that conflict with imputed dam genotypes','Sample ID'),
('Special Section >> Reports','Get Animals with unlikely grandsire (and no other conflict) in the past 6 months','Animal'),
('Special Section >> Reports','Get Animals with unlikely grandsire (and no other conflict) in the past 6 months','MGS Status Code'),
('Special Section >> Reports','Get Animals with unlikely grandsire (and no other conflict) in the past 6 months','PGS Status Code'),
('Special Section >> Reports','Get Check for missing pedigree of animals nominated in the past 75 days','Animal'),
('Special Section >> Reports','Get Check for missing pedigree of animals nominated in the past 75 days','Dam'),
('Special Section >> Reports','Get Conflicts for genotypes loaded in the past 45 days','Animal'),
('Special Section >> Reports','Get Conflicts for genotypes loaded in the past 45 days','Conflict ID'),
('Special Section >> Reports','Get Conflicts for genotypes loaded in the past 45 days','Conflict Name'),
('Special Section >> Reports','Get Conflicts for genotypes loaded in the past 45 days','Conflict Type'),
('Special Section >> Reports','Get Conflicts for genotypes loaded in the past 45 days','Long Name'),
('Special Section >> Reports','Get Conflicts for genotypes loaded in the past 45 days','Requester'),
('Special Section >> Reports','Get Conflicts for genotypes loaded in the past 45 days','Sample ID'),
('Special Section >> Reports','Get Conflicts for genotypes loaded in the past 45 days','Source Code'),
('Special Section >> Reports','Get Fee codes for genotypes loaded since the last invoice','Animal'),
('Special Section >> Reports','Get Fee codes for genotypes loaded since the last invoice','Fee code'),
('Special Section >> Reports','Get Fee codes for genotypes loaded since the last invoice','Geno Arrival Date'),
('Special Section >> Reports','Get Fee codes for genotypes loaded since the last invoice','Group/ Herd'),
('Special Section >> Reports','Get Fee codes for genotypes loaded since the last invoice','Reason'),
('Special Section >> Reports','Get Fee codes for genotypes loaded since the last invoice','Sample ID'),
('Special Section >> Reports','Get Fee codes for genotypes loaded since the last invoice','Usability Ind'),
('Special Section >> Reports','Get List conflicting genotypes within animal (negative keys)','Animal'),
('Special Section >> Reports','Get List conflicting genotypes within animal (negative keys)','Chip Number'),
('Special Section >> Reports','Get List conflicting genotypes within animal (negative keys)','Geno Arrival Date'),
('Special Section >> Reports','Get List conflicting genotypes within animal (negative keys)','Sample ID'),
('Special Section >> Reports','Get Lists genotypes with fee code=N loaded in the past 6 months','Animal'),
('Special Section >> Reports','Get Lists genotypes with fee code=N loaded in the past 6 months','Fee code'),
('Special Section >> Reports','Get Lists genotypes with fee code=N loaded in the past 6 months','Geno Arrival Date'),
('Special Section >> Reports','Get Lists genotypes with fee code=N loaded in the past 6 months','Group/ Herd'),
('Special Section >> Reports','Get Lists genotypes with fee code=N loaded in the past 6 months','Sample ID'),
('Special Section >> Reports','Get Lists genotypes with fee code=N loaded in the past 6 months','Usability Ind'),
('Special Section >> Reports','Get Lists parentage only genotypes since the previous genomic run','Animal'),
('Special Section >> Reports','Get Lists parentage only genotypes since the previous genomic run','Fee code'),
('Special Section >> Reports','Get Lists parentage only genotypes since the previous genomic run','Geno Arrival Date'),
('Special Section >> Reports','Get Lists parentage only genotypes since the previous genomic run','Group/ Herd'),
('Special Section >> Reports','Get Lists parentage only genotypes since the previous genomic run','Sample ID'),
('Special Section >> Reports','Get Lists parentage only genotypes since the previous genomic run','Usability Ind'),
('Special Section >> Reports','Get Parentage verification records for genotypes loaded in the past','Animal'),
('Special Section >> Reports','Get Parentage verification records for genotypes loaded in the past','Animal Source Code'),
('Special Section >> Reports','Get Parentage verification records for genotypes loaded in the past','Chip Name'),
('Special Section >> Reports','Get Parentage verification records for genotypes loaded in the past','Fee code'),
('Special Section >> Reports','Get Parentage verification records for genotypes loaded in the past','Geno Arrival Date'),
('Special Section >> Reports','Get Parentage verification records for genotypes loaded in the past','Gets Eval'),
('Special Section >> Reports','Get Parentage verification records for genotypes loaded in the past','PI'),
('Special Section >> Reports','Get Parentage verification records for genotypes loaded in the past','Requester'),
('Special Section >> Reports','Get Parentage verification records for genotypes loaded in the past','Sample ID'),
('Special Section >> Reports','Get Parentage verification records for genotypes loaded in the past','Usability Ind'),
('Special Section >> Reports','Get Reports missing animal ID for a requester','Chip Number'),
('Special Section >> Reports','Get Reports missing animal ID for a requester','Geno Arrival Date'),
('Special Section >> Reports','Get Reports missing animal ID for a requester','Sample ID'),
('Special Section >> Sample ID Look Up','Sample ID Look Up by Animal ID/Sample ID','Animal Information'),
('Special Section >> Sample ID Look Up','Sample ID Look Up by Animal ID/Sample ID','Genotype Information'),
('Special Section >> Sample ID Look Up','Sample ID Look Up by Animal ID/Sample ID','Pedigree Information'),
('Special Section >> Suggested Dam','Special Section >> Suggested Dam','Animal'),
('Special Section >> Suggested Dam','Special Section >> Suggested Dam','Candidate Dam'),
('Special Section >> Suggested Dam','Special Section >> Suggested Dam','Comment')
;

 
 
 INSERT INTO FIELD_TABLE
 (
 COMPONENT_KEY,
 FIELD_NAME,
 CREATED_TIME,
 MODIFIED_TIME
 )
select  
         fc.COMPONENT_KEY,
		 field.FIELD_NAME,
		 current timestamp as CREATED_TIME,
		 current timestamp as MODIFIED_TIME 
from SESSION.TMP_FIELD field
inner join FEATURE_COMPONENT_TABLE fc
on field.COMPONENT_NAME = fc.COMPONENT_NAME
inner join FEATURE_TABLE f
on fc.FEATURE_KEY = f.FEATURE_KEY
and field.FEATURE_NAME = f.FEATURE_NAME
order by f.feature_name,
		fc.component_name, 
		field.field_name 
 ;
 
   