CREATE OR REPLACE FUNCTION fn_Split_String
--======================================================
--Author: Nghi Ta
--Created Date: 2020-04-06
--Description:Split string value with delimiter char into
--list of value
--======================================================
(

    @INPUT_VALUE VARCHAR(10000) 
  , @DELIMITER VARCHAR(1)    

) 
RETURNS TABLE (LEVEL INT, ITEM VARCHAR(128) )

LANGUAGE SQL

RETURN

 
WITH R1 (LEVEL,ITEM, REMINDER) AS 
(SELECT 1 AS LEVEL, SUBSTR(@INPUT_VALUE||',', 1, LOCATE(@DELIMITER, @INPUT_VALUE||',')-1) AS ITEM, 
SUBSTR(@INPUT_VALUE||',', LOCATE(@DELIMITER, @INPUT_VALUE||',')+1, LENGTH(@INPUT_VALUE||',')) REMINDER
FROM SYSIBM.SYSDUMMY1

UNION ALL

SELECT LEVEL+ 1 AS LEVEL, SUBSTR(REMINDER, 1, LOCATE(@DELIMITER, REMINDER)-1) AS ITEM, 
SUBSTR(REMINDER, LOCATE(@DELIMITER, REMINDER)+1, LENGTH(REMINDER)) REMINDER 
FROM R1 WHERE LOCATE(@DELIMITER, REMINDER) > 0 AND LEVEL<10000
)

SELECT LEVEL, LTRIM(RTRIM(ITEM)) 
FROM R1
WHERE  LTRIM(RTRIM(ITEM))<>','


